### ISSUE TITLE
Excessive spacing when extracting text from PDF

### ISSUE THREAD

**Issue by mush42** [pymupdf/PyMuPDF#364] opened 2019-09-15 09:58 UTC
Hello,

Thanks for this awesome work. I'm using PyMuPDF to provide blind people with accessible eBook reading experience with [Bookworm](https://github.com/mush42/bookworm/).

## Describe the bug (mandatory)
PyMuPDf v1.16.0 and up introduced a weired bug with certain PDF documents. When using text extraction functions., excessive spaces are inserted between characters. The extracted text is just a blob of characters. I have to admit that this problem is rare, it happens with some kind of PDF documents. In v1.14X versions the text is extracted correctly.

## To Reproduce (mandatory)
Here is the text extraction function straight from the FitzDocument backend:

```python
def _text_from_page(page):
    bloks = page.getTextBlocks()
    text = [blk[4].replace("\n", " ") for blk in bloks]
    return "\r\n".join(text)
```

## Expected behavior (optional)
The text is extracted preserving its basic structure (words and paragraphs).

## Your configuration (mandatory)
 - Operating system: Windows 10 Pro, 64-bit
 - Python: Python 3.7.4 64-bit/32-bit
 - PyMuPDF version: v1.16.0, installed from PyPI

## Additional context (optional)
The problem still happens with the latest version of PyMuPDF (v1.16.2). Playing with text extraction flags didn't help, it gives several variations none of which solves the issue.

This problem happens with the Dart specs document, and several others. As an example, the Dart language specs is attached.
[DartLangSpec-v2.2.pdf](https://github.com/pymupdf/PyMuPDF/files/3613623/DartLangSpec-v2.2.pdf)

**Comment by JorjMcKie** [comment] 2019-09-15 13:26
Hi,
any particular page where this happens, so I don't need to search within 206 of them?

**Comment by JorjMcKie** [comment] 2019-09-15 13:42
I have tried page 6 and I believe I understand what you mean.

If printing with this command (page=5 in zero-based count):
```python
>>> for b in page.getText("blocks", flags=1+2):  # flags=3 corresponds to default in earlier versions
	print(b[4])
```
We get this
```
D ar t P r ogr am m i n g Lan gu age S p e c i ﬁ c at i on 6
1 Sco pe
e c m a Sc o pe
T h i s E c m a s t an d ar d s p e c i ﬁ e s t h e s y n t ax an d s e m an t i c s of t h e D ar t p r ogr am -
m i n g l an gu age . I t d oe s n ot s p e c i f y t h e AP I s of t h e D ar t l i b r ar i e s e x c e p t w h e r e
t h os e l i b r ar y e l e m e n t s ar e e s s e n t i al t o t h e c or r e c t f u n c t i on i n g of t h e l an gu age
i t s e l f ( e . g. , t h e e x i s t e n c e of c l as s Object w i t h m e t h od s s u c h as noSuchMethod,
runtimeType) .
2 C o nf o r m a nce
e c m a C o nf o r m a nc e
< excess data omitted >
```

**Comment by JorjMcKie** [comment] 2019-09-15 13:48
When printing with:
```python
>>> for b in page.getText("blocks", flags=1+2+8):
	print(b[4])
```
We get
```
DartProgram m ingLanguageSpeciﬁcation 6
1 Scope
ecm aScope
ThisEcm astandard speciﬁesthesyntaxand sem anticsoftheDartprogram -
m inglanguage.Itdoesnotspecify theAPIsoftheDartlibrariesexceptwhere
those library elem entsare essentialtothe correctfunctioningofthe language
itself(e.g.,the existence ofclassObjectwith m ethodssuch asnoSuchMethod,
runtimeType).
2 C onform ance
ecm aC onform ance
Aconform ingim plem entation oftheDartprogram m inglanguagem ustpro-
videandsupportalltheAPIs(libraries,types,functions,getters,setters,whether
top-level,static,instanceorlocal)m andated in thisspeciﬁcation.
...
```
Which is less than satisfying, but better ...
(Oh, btw. I have been using my new patch version 1.16.3, which directly supports getTextBlocks in that way - do not try this with your version).

**Comment by JorjMcKie** [comment] 2019-09-15 14:05
As a crosscheck I extracted that page with ``"mutool draw -o page6.html DartLangSpec-v2.2.pdf"``. Just to trace who is doing the crime.
This results in a html page looking like this:

![grafik](https://user-images.githubusercontent.com/8290722/64922558-894f7000-d79e-11e9-963d-f37135d39588.png)

And indeed: versions based on MuPDF v1.14 do it "correctly" ... annoying.

Let me check if one of my utilities can be a help ... "I'll be back" (quotation).

**Comment by JorjMcKie** [comment] 2019-09-15 16:29
I'm afraid I have to give up. There seems to be no way of recovering a behaviour similar to MuPDF v1.14.
We need to submit an issue to MuPDF (Artifex), which I did just now.
If you want to refer to this, go to this web site: https://bugs.ghostscript.com/show_bug.cgi?id=701602.

If you want, you can also emphasize your interest in resolving it on that site - give it a try ...

**Comment by mush42** [comment] 2019-09-15 17:01
Hi @JorjMcKie

Thanks. It is really frustrating when something used to work correctly suddenly breaks.

When I've tried to rollback the version from 1.16 to 1.14, pip could not find a suitable distribution for that version. Could you please provide away to install older versions of PyMuPDF. It is really, really important to have an archive of previous versions for some critical applications.

Kind Regards,

**Comment by JorjMcKie** [comment] 2019-09-15 17:14
The unavailability of 1.14 versions on PyPI is my fault. Here are 2 recreated from source. Please let me know if you require other versions ...
You need to rename them from *.zip to *.whl (Github restriction).
[PyMuPDF-1.14.20-cp37-cp37m-win32.zip](https://github.com/pymupdf/PyMuPDF/files/3614028/PyMuPDF-1.14.20-cp37-cp37m-win32.zip)

[PyMuPDF-1.14.20-cp37-cp37m-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/3614027/PyMuPDF-1.14.20-cp37-cp37m-win_amd64.zip)

**Comment by JorjMcKie** [comment] 2019-09-15 22:05
@mush42  - did this work for you?

**Comment by JorjMcKie** [comment] 2019-09-16 08:40
I have just uploaded an official intermediate version 1.14.21 to PyPI.
I hope you can use this while we are waiting for a fix from upstream.

**Comment by mush42** [comment] 2019-09-16 17:17
Yes it works. Thank you.

**Comment by sshustov** [comment] 2019-09-16 21:07
I noticed same behaviour in some PDF documents. It may be related or not related to the same bug.
[some_table.pdf](https://github.com/pymupdf/PyMuPDF/files/3618165/some_table.pdf)

For some reason fitz 1.16 and higher is merging 'Description of' into 'Descriptionof'. 
It happens in getText() and getTextWords().
Version 1.14.20 text generated correctly.

**Comment by nirvantosh** [comment] 2019-11-28 11:05
I am not sure if this is relevant at this thread anymore or not, but I have got some observation too regarding same. 

I have tried to convert an XPS file to PDF file using PyMuPDF. I have done this on two types of files, one with text embedded in them which you can just copy directly from xps file and other where its an image and no embedded text. 

When converted to PDF, the one with image converts exactly the same. But with text embedded xps, the converted pdf contains spaces between chars similar to this bug. 

I have attached PDF docs for both (xps file not getting attached here). imagePdf for image based and textPdf for text embedded doc.

Also, this doesn't happen with 1.14.20 version but happens with 1.16 onwards. Is this solved yet? I can not use 1.14 versions due to some other issue in that.

[imagePdf.pdf](https://github.com/pymupdf/PyMuPDF/files/3901274/imagePdf.pdf)

[textPdf.pdf](https://github.com/pymupdf/PyMuPDF/files/3901275/textPdf.pdf)

**Comment by JorjMcKie** [comment] 2019-11-28 11:36
@nirvantosh - no, the issue does still exist. Submitted a bug to MuPDF, but they haven't reacted yet.

**Comment by JorjMcKie** [comment] 2019-12-09 00:30
For everyone who likes to follow up what happens at MuPDF's issue management, here is the  relevant URL: https://bugs.ghostscript.com/show_bug.cgi?id=701602

As can be seen there, other users have observed and confirmed similar issues.
Based on my experience, I recommend to confirm on that website, that you too are having this issue. This will help convince MuPDF that it is a relevant issue.
If you decide to do so, please restrict yourself to examples exclusively using MuPDF's command line tools (or even your C program using MuPDF directly). Referring to PyMuPDF would be counterproductive, because it would - from MuPDF's perspective - introduce another unknown into the equation.

**Comment by JorjMcKie** [comment] 2020-01-08 13:28
Artifex / MuPDF have reported the bug to **_their_** upstream, see here:

![grafik](https://user-images.githubusercontent.com/8290722/71981660-33914e80-31f9-11ea-822c-cb8afb9741dd.png)

**Comment by JorjMcKie** [comment] 2020-04-26 01:10
Hi,
just checked your example with the new version about to be release: 1.17.
It looks like it will solve this problem.

**Comment by JorjMcKie** [comment] 2020-06-03 14:47
Although maybe not resolved for every imaginable case, the published version 1.17.0 does resolve your provided example.
So I will close this issue for the time being.

**Closed by JorjMcKie** 2020-06-03 14:47 UTC
Labels: postpone, upstream bug

**Comment by mush42** [comment] 2020-06-14 05:09
Hi @JorjMcKie ,

Sorry for being late!
Currently, I'm living in a rural area without adequate internet access. I'll try the new version, and give feedback as soon as I'm back online.

Regards,

**Comment by Elucin** [comment] 2020-06-14 15:07
This resolved it for me. Thanks!
