### ISSUE TITLE
Missing space characters using text extraction

### ISSUE THREAD

**Issue by corryms1993** [pymupdf/PyMuPDF#456] opened 2020-03-03 14:46 UTC
Hi there,

I've noticed that when running text extraction there are sometimes spaces missing in the outputted text. This appears to apply specifically to headings within PDFs.

Example PDF: (https://www.cqc.org.uk/sites/default/files/new_reports/AAAG0004.pdf)

For example, for the above PDF, the text: "Mental Health Act responsibilities and Mental Capacity Act and Deprivation of Liberty" 

is outputted as: "MentalHealthActresponsibilitiesandMentalCapacityActandDeprivationofLiberty" 

I've tried using other PDF text extraction tools such as PDF Box which do not show this behaviour.

Hopefully someone is able to determine the cause of the problem.

Configuration
 - Windows 10 x64
 - Python 3.6
 - PyMuPDF version 1.16.11 (have tried older versions too)

Screenshots:

![image](https://user-images.githubusercontent.com/49235569/75786793-b8ae6500-5d5d-11ea-9473-7ff1ea861b99.png)

![image](https://user-images.githubusercontent.com/49235569/75786829-c6fc8100-5d5d-11ea-8cf8-7ed7dea83746.png)

Many thanks,

Corry

**Comment by JorjMcKie** [comment] 2020-03-03 15:25
Duplicate of #364

**Comment by JorjMcKie** [comment] 2020-03-03 15:27
MuPDF from Artifex have identified the error cause: it is a bug in **_their_** upstream component ``freetext``.
They are working on this.

**Comment by corryms1993** [comment] 2020-03-03 15:35
Thanks for getting back to me. I had noticed #364 before however I tried following the temporary fix of downgrading to 1.14.21 but the issue still persists. Do you think this is definitely the same issue?

Many thanks

**Comment by JorjMcKie** [comment] 2020-03-03 17:12
> downgrading to 1.14.21 but the issue still persists.

Oops, if that's the case: then no.
Can you share the example PDF - just one page would suffice?

What you can try in the meantime:
Use ``mutool draw -o test.html input.pdf n``, where ``n`` is a 1-based page number.
This directly uses the base library (not PyMuPDF) to produce a HTML version of that page. If the text appears awkward there, too, then it is another upstream error, and I can probably do nothing about it.
Please directly report to their bug system https://bugs.ghostscript.com/enter_bug.cgi.
Do not base your example on PyMuPDF, because they would not accept it that way. Take the ``mutool`` test case.
You should as well try out both cases MuPDF v1.14 and MuPDF 1.16.

**Comment by corryms1993** [comment] 2020-03-03 17:24
I've tried using MuPDF in v1.14 and 1.16 and the problem is visible there too. I'll report this is a bug in MuPDF. Thanks for your help!

**Comment by JorjMcKie** [comment] 2020-06-03 14:50
There is some improvement in version 1.17.0 of MuPDF.
Allthough maybe not completely resolved for all imaginable cases, I am going to close this issue for now.

**Closed** 2020-06-03 14:50 UTC
Labels: postpone, upstream bug
