### ISSUE TITLE
Page.apply_redactions() removes more text than expected in the pdf document.

### ISSUE THREAD

**Issue by dameyerdave** [pymupdf/PyMuPDF#3433] opened 2024-05-02 12:50 UTC
### Description of the bug

As soon as I apply the reductions all the text and graphics get lost from the pdf.

Source:

<img width="955" alt="Receipt pdf" src="https://github.com/pymupdf/PyMuPDF/assets/5663605/d9b129f3-a8ba-4ea6-a8f1-4f37d5027af1">

Annotated:

<img width="955" alt="Receipt_annot" src="https://github.com/pymupdf/PyMuPDF/assets/5663605/b0216795-d835-4746-b5de-947e3cf8745a">

After `apply_reductions()`:

<img width="977" alt="Screenshot 2024-05-02 at 14 40 02" src="https://github.com/pymupdf/PyMuPDF/assets/5663605/c596e4f4-c529-4360-94e8-302b2c19638a">

### How to reproduce the bug

This is the code I wrote to come tho this:

```python
doc = fitz.open("./Receipt.pdf")
for page in doc:
    for text in some_text_array:
        for area in page.search_for(text, quads=True):
            reduction = page.add_redact_annot(
                area,
                fill=(0, 0, 0),
            )
            reduction.update()

    # here it happens
    page.apply_redactions(0,0,0)

doc.save("./redacted.pdf")
doc.close()
```

### PyMuPDF version

1.24.2

### Operating system

MacOS

### Python version

3.10

**Comment by JorjMcKie** [comment] 2024-05-02 14:28
Please provide all mandatory information - in this case, the reproducing file is missing.

**Comment by dameyerdave** [comment] 2024-05-03 06:54
I'm sorry for that. These are the files:

- [original.pdf](https://github.com/pymupdf/PyMuPDF/files/15196946/original.pdf)
- [redacted.pdf](https://github.com/pymupdf/PyMuPDF/files/15196952/redacted.pdf)

**Comment by JorjMcKie** [comment] 2024-05-03 10:01
Thanks for the examples.
Sorry I cannot find a problem. Made a redaction to remove "David Meyer" and it simply worked!
```python
for r in page.search_for("david meyer"):
    page.add_redact_annot(r)

    
'Redact' annotation on page 0 of original.pdf
page.apply_redactions(0,0,0)
True
doc.ez_save("x-1.24.2.pdf")
```
![image](https://github.com/pymupdf/PyMuPDF/assets/8290722/228e6914-8a6f-4bdf-82f1-f35228cdcd2a)

**Comment by aleem75321** [comment] 2024-05-05 20:30
HI @JorjMcKie  I have faced the same issue while applying Redaction. they remove images which should not be removed or changing text.
[test.pdf](https://github.com/pymupdf/PyMuPDF/files/15214448/test.pdf)
[test2.pdf](https://github.com/pymupdf/PyMuPDF/files/15214449/test2.pdf)

I have attached  both pdf to reproduce the issue  


![test_Original_image](https://github.com/pymupdf/PyMuPDF/assets/69341817/ec7dc337-2ae0-41e5-88e4-bdd6d395c52b)
![test_after_redacttion](https://github.com/pymupdf/PyMuPDF/assets/69341817/ba8e172b-4ebe-4efd-8916-919daa2b3992)

![test2_Original_image](https://github.com/pymupdf/PyMuPDF/assets/69341817/c6b831c4-f684-47f8-8ed4-41b6c0f73f1c)
![test2_after_redacttion](https://github.com/pymupdf/PyMuPDF/assets/69341817/d835d183-c6ee-4968-baf4-1d78d0133d8c)
![test2_Original_text_issue](https://github.com/pymupdf/PyMuPDF/assets/69341817/8da54053-e0ed-45c6-808e-d4232214bf4e)
![test2_after_redact_text_issue](https://github.com/pymupdf/PyMuPDF/assets/69341817/0317d4f8-2d3d-4a8e-8ebb-473cffaa42de)

**Comment by JorjMcKie** [comment] 2024-05-06 07:55
@aleem75321 please submit this as a different issue - this is too confusing in this context.
When you do, please save the PDF when you have inserted all redactions - before applying them. I need to confirm where your code has put them - without the need to understand your code.
**_Then_** attach this PDF to confirm that bad things happen on applying redactions.

**Comment by aleem75321** [comment] 2024-05-06 09:13
Facing Issues after applying redactions they delete some Images or Icons #3439

**Comment by dameyerdave** [comment] 2024-05-06 15:05
I reduced the application to the bare minimum. I still encounter the same issue. I tried it on mac M3 and on ubuntu linux (Intel) as well as in a docker container with `platform: linux/amd64` without success.

```python
import fitz

doc = fitz.open("./original.pdf")
for page in doc:
    for r in page.search_for("David Meyer"):
        page.add_redact_annot(r)

    page.apply_redactions(0, 0)
    doc.ez_save("redacted.pdf")
```

With the following files:

[original.pdf](https://github.com/pymupdf/PyMuPDF/files/15222511/original.pdf)
[redacted.pdf](https://github.com/pymupdf/PyMuPDF/files/15222524/redacted.pdf)

I don't know what to try now... If you have another good idea, please let me know...

**Comment by JorjMcKie** [comment] 2024-05-06 15:27
@dameyerdave we (a colleague of mine and I) have tried on all 3 platforms now Mac, Linux, Win with `fitz.version=('1.24.2', '1.24.1', '20240417000001')` and are getting the correct, flawless result.
🤷‍♂️

**Comment by JorjMcKie** [comment] 2024-05-06 15:30
My only advice is to re-install 1.24.2.
There has been a redaction issue previously. I will try with 1 or 2 previous versions.

**Comment by JorjMcKie** [comment] 2024-05-06 15:36
No such luck:
At least on windows, all versions back to 1.23.26 do work correctly.
So you probably best re-install with the latest version.

**Comment by luchux** [comment] 2024-05-06 21:15
We are facing exactly the same as everybody posting the bug in this thread. 
Our version in the env is
Name: PyMuPDF
Version: 1.24.0

I tried removing the apply_redaction(images=0) and also used all the combos possible for the parameter. 
Also tried removing garbage collectors, and deflates when saving. 

Exactly the same error as other people:

Original PDF before redaction
<img width="496" alt="Screenshot 2024-05-06 at 6 13 11 PM" src="https://github.com/pymupdf/PyMuPDF/assets/1475656/3c65db94-878f-4dbe-bd8f-903b2a2c5446">

After apply.redaction to text "Origin" 
<img width="710" alt="Screenshot 2024-05-06 at 6 14 09 PM" src="https://github.com/pymupdf/PyMuPDF/assets/1475656/0e46d5d2-01c7-434c-966a-a57c30f84b79">


We would love to know if you are aware of this bug and a stable version that works properly without this bug. Thanks a lot!

**Comment by luchux** [comment] 2024-05-06 21:59
Another example. 
Now tested 2 versions: 1.24.0 and 1.24.2 both failing. 

Original before redaction: 
<img width="769" alt="Screenshot 2024-05-06 at 6 58 14 PM" src="https://github.com/pymupdf/PyMuPDF/assets/1475656/17e0c336-1373-46e6-8a31-f37559a251d3">

After text redacted: 
<img width="732" alt="Screenshot 2024-05-06 at 6 58 32 PM" src="https://github.com/pymupdf/PyMuPDF/assets/1475656/3abbd69d-46df-4505-9dbe-badef0933efc">

**Comment by JorjMcKie** [comment] 2024-05-07 08:21
@luchux - "A picture is worth a thousand words."

Certainly true. But a thousand pictures are **_not_** worth a million words! 
Please add an example **_file_** and no  more pictures if we should confirm that yours is another duplicate of #3376.

Please also note, that the problem of **_this_** post is yet not reproducible and thus unclear whether it is a bug at all.

**Comment by JorjMcKie** [comment] 2024-06-22 08:37
Closing this for lack of information since a long time.

**Closed by JorjMcKie** 2024-06-22 08:37 UTC
Labels: Waiting for information
