### ISSUE TITLE
Memory leak when opening an invalid PDF with no %%EOF in tail

### ISSUE THREAD

**Issue by cmyers009** [pymupdf/PyMuPDF#3344] opened 2024-04-04 18:47 UTC
### Description of the bug

If the file bytes are prematurely cut-off, then fitz will open the PDF file with 0 pages, but at the same time, cause a memory leak.

### How to reproduce the bug

You can reproduce this bug by taking a large PDF file, and remove the last 50% of the bytes.

If you repeatably load files like this, there will be a memory leak even with a doc.close()

You can add a check if the file has an %%EOF with this code.  If you call it before the doc.open() code, then you can return 0 pages without the need to produce the memory leak.

`def has_eof_marker(file_path):
    try:
        with open(file_path, 'rb') as file:
            # Seek to the last 1KB of the file
            file.seek(-1024, os.SEEK_END)
            # Read the last 1KB
            tail = file.read()
            # Check if `%%EOF` is in the last 1KB
            return b'%%EOF' in tail
    except Exception as e:
        print(f"Error reading file: {e}")
        return False`
        
        
        PyMuPDF 1.23.4

### PyMuPDF version

1.23.8 or earlier

### Operating system

Windows

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment] 2024-04-04 20:45
I cannot reproduce this with the current version, PyMuPDF-1.24.1. What version of PyMuPDF are you using?

**Comment by cmyers009** [comment] 2024-04-04 22:29
I am using 1.23.4

**Comment by julian-smith-artifex-com** [comment] 2024-04-05 07:22
There have been quite a few improvements to memory handling since 1.23.4 and so it would be worth retrying with the latest version, 1.24.1.

**Comment by cmyers009** [comment] 2024-04-05 18:04
Ok, I'll check it out.

**Comment by julian-smith-artifex-com** [comment] 2024-05-22 20:49
Closing this because waiting for information for over a month.

**Closed by julian-smith-artifex-com** 2024-05-22 20:49 UTC
Labels: Waiting for information
