### ISSUE TITLE
Getting "object is not a stream" error after cleaning the document

### ISSUE THREAD

**Issue by tigrankh** [pymupdf/PyMuPDF#812] opened 2021-01-07 07:54 UTC
Hi,

I'm getting errors for a specific document when I call scrub() method.
Right after scrub() is called I get this:
`mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream
mupdf: object is not a stream`

Then I call getPixmap() and this exception is raised:

`Traceback (most recent call last):
  File "scrub_issue_testcase/script.py", line 29, in <module>
    item = page.getPixmap(matrix=mat)
  File "virtualenvs/lib/python3.8/site-packages/fitz/utils.py", line 594, in getPixmap
    dl = page.getDisplayList(annots=annots)
  File "lib/python3.8/site-packages/fitz/fitz.py", line 5518, in getDisplayList
    val = _fitz.Page_getDisplayList(self, annots)
RuntimeError: object is not a stream`

When I comment out scrub(), pixmap is successfully generated, so I assume something wrong is happening in scrub.

To reproduce the error, please use the testcase attached

I tried with PyMuPDF v1.18.4 and 1.18.5

Could you please help with this?

thanks,
Tigran
[scrub_issue_testcase.tar.gz](https://github.com/pymupdf/PyMuPDF/files/5780240/scrub_issue_testcase.tar.gz)

**Comment by JorjMcKie** [comment] 2021-01-07 08:39
Duplicate of #785 
Will be fixed with next version 1.18.6 coming soon. If there is urgency, please consider what I recommended in #785.

**Comment by tigrankh** [comment] 2021-01-07 08:45
thanks for the reply. 
Sorry for not mentioning it. I already tried that recommendation, but it didn't fix my issue.

**Comment by JorjMcKie** [comment] 2021-01-07 10:26
Found the problem - an interesting one!
Deleting objects must be handled with extreme care obviously ...
I will include the fix with the next version.

**Comment by tigrankh** [comment] 2021-01-07 10:28
great, thank you.
Do you think there's a workaround I could apply?

**Comment by JorjMcKie** [comment] 2021-01-07 10:45
>  Do you think there's a workaround I could apply?

I will generate pre-version wheels anyway. Once finished (within an hour or so), you can download & install it.
Are you Linux?

Maybe an immediate help could also be:
Within the scrub method there is a loop over the pages, which comes after XML / JavaScript cleaning.
Thats the problem! Put it before and things should go ok for the moment.

**Comment by tigrankh** [comment] 2021-01-07 13:00
I'm on Mac. wheels will be very helpful thanks. I'll now try out manual change

**Comment by JorjMcKie** [comment] 2021-01-07 13:07
Fixed by new version currently being uploaded.

**Closed** 2021-01-07 13:12 UTC
Labels: bug
