### ISSUE TITLE
Document.save garbage parameter not working in PyMuPDF 1.21.0

### ISSUE THREAD

**Issue by jogoertzen-stantec** [pymupdf/PyMuPDF#2057] opened 2022-11-17 17:43 UTC
## Describe the bug (mandatory)

`Document.save()` appears to be ignoring the `garbage=4` parameter in version 1.21.0 of PyMuPDF.

## To Reproduce (mandatory)

1. Download the example project below.
2. Run `install_PyMuPDF_1_21_0.sh`.
3. Run `python3.7 run.py` and observe file size is ~44 MB.
4. Run `install_PyMuPDF_1_20_2.sh`.
5. Run `python3.7 run.py` again and observe file size is ~9 MB.

[PyMuPDF_bug.zip](https://github.com/pymupdf/PyMuPDF/files/10034154/PyMuPDF_bug.zip)

## Your configuration (mandatory)
 - Windows 10 WSL2 Ubuntu 20.04 64 bit
 - Python 3.7 64 bit
 - PyMuPDF 1.21.0 and 1.20.2 **wheel**

**Comment by JorjMcKie** [comment] 2022-11-18 15:22
Thank you for reporting this.
I can confirm your observation. The issue is located in the base library MuPDF, not in PyMuPDF.
Confirm this by doing `mutool clean -ggg doc.pdf out3.pdf` versus `mutool clean -gggg doc.pdf out4.pdf`. Both will have same file sizes in MuPDF v1.21.0, out4.pdf is smaller when created with MuPDF v1.20.0.

We are workinbg on this already, so expect a solution in next patch version.

**Comment by julian-smith-artifex-com** [comment] 2022-11-22 22:00
Upstream bug is: https://bugs.ghostscript.com/show_bug.cgi?id=706094

**Comment by julian-smith-artifex-com** [comment] 2022-12-13 14:59
Fixed in PyMuPDF-1.21.1 (but omitted from changelog by mistake.)

**Closed by julian-smith-artifex-com** 2022-12-13 14:59 UTC
Labels: upstream bug
