### ISSUE TITLE
Again: you removed released releases

### ISSUE THREAD

**Issue by zopyx** [pymupdf/PyMuPDF#349] opened 2019-08-21 05:58 UTC
```
bin/pip install PyMuPDF==1.14.19
Collecting PyMuPDF==1.14.19
  Could not find a version that satisfies the requirement PyMuPDF==1.14.19 (from versions: 1.11.2, 1.12.5, 1.13.20, 1.14.19.post2, 1.14.19.2, 1.14.20)
No matching distribution found for PyMuPDF==1.14.19
``` 

You replaced this release with 1.14.19post2.

It is  completely unhelpful removing released release.

Released is released. Point.

You are breaking dependencies of other projects!

See also here:

https://www.zopyx.com/andreas-jung/contents/released-is-released

**Comment by JorjMcKie** [comment] 2019-08-21 07:07
well, in this case you will have to forgive me:
This version contained a severe bug, so I either had to replace the source (you cannot have two sub-versions of them) or leave you with an unusable version.
Please use 1.14.20

**Comment by zopyx** [comment] 2019-08-21 08:12
Again, released is released even when the release is buggy. That's why we have .post release.

And in this case the 1.14.19 was working at least for the functionality we needed.

It is annonying when your CI breaks just because of a disappeared package.

Please read my blog post.

**Comment by edrogersamfam** [comment] 2019-08-23 14:50
@JorjMcKie

First and foremost, thanks for being an open source contributor. It helps the whole community when people like you are willing to volunteer their efforts to create tools we can all use.

That said, I wanted to also express disappointment that my team can't use PyMuPDF for our projects any longer. We require reproducibility, and the ability to load old versions from PyPI in an automated way is part of that. I appreciate your concern for keeping up-to-date with new releases of SWIG. But as a user, I'd appreciate the trust that I can update my version of PyMuPDF as I see fit.

Thanks all the same.

**Comment by zopyx** [comment] 2019-08-23 14:53
Again, read my blog post. Released is released. Point.

**Comment by JorjMcKie** [comment] 2019-08-24 12:16
@zopyx - understood, you have made your point clear enough by now. As mentioned I didn't try do (again) **_remove_** anything with my last change. Just wanted to replace a faulty source. If I understand the situation correctly, I should have named that corrected source file differently. 
In an effort to find back to a constructive communication: Any way to heal this?

@edrogersamfam - in the end, it of course is your decision to no longer use this package, which I would nevertheless regret.
The recent problem I caused does however **not** go back to the SWIG upgrade. Ignoring my last lapsus for a moment, then the content of _source_ distribution file in PyPI will always be as the same as it has been, namely containing the files ``__init__.py``, `fitz.py`, `fitz_wrap.c` and `utils.py` and a fitting ``setup.py``. That, and an installed MuPDF continues to be all you need.
The Github source directory however, will **no longer** contain files `fitz.py` and `fitz_wrap.c` - they must be created by a locally installed SWIG. The ``setup.py`` accompanying this contains appropriate instructions to do this automatically. I think that the decision to do it this way is well founded and aimed to support esp. Linux package creators. They have major issues in dealing with those generated files.

**Comment by guoyunhe** [comment] 2019-09-05 22:19
@zopyx 

Despite the question itself makes sense, communication on GitHub should be friendly. Behave like you are talking to a person in real life.

Just like many other open source software, this software doesn't give you any warranty. [Read the license](https://github.com/pymupdf/PyMuPDF/blob/master/GNU%20AFFERO%20GPL%20V3#L94).

GitHub and PyPI **allows** owners to delete releases. [Read PyPI Help](https://pypi.org/help/). You should have considered this in your development process and not lock it to a very specific version.

Software engineering is a collaboration process. We all benefit from open source. If some package has a problem, you can report it but try to be polite. We should be thankful when using their work in ours. We never pay them anything. But, at least, pay some respect.

**Comment by JorjMcKie** [comment] 2019-09-06 07:51
@guoyunhe - I appreciate your comment, thank you very much indeed.
I had tried to explain my motives - but I see now the unintended consequences caused for some others.

As for the deleted patch releases in question: they cannot be recovered in any way.
So I am going to close this specific issue in that sense.

**Closed** 2019-09-06 07:51 UTC
Labels: bug, wontfix

**Comment by zopyx** [comment] 2020-07-09 07:59
And you did it again with 1.14.19.2 - there is a hell....
