### ISSUE TITLE
CFF Fonts display gibberish on Apple Preview (iOS and Mac OS)

### ISSUE THREAD

**Issue by clark-archer** [pymupdf/PyMuPDF#1095] opened 2021-06-17 18:02 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
When viewing a PDF with content generated using the TextWriter append and fill_textbox methods on Apple iOS or a Macintosh with the default Apple PDF viewer, any text written using the above methods looks like gibberish.

## To Reproduce (mandatory)
Write text to the page using TextWriter append or fill_textbox methods. 
```
from fitz import *

doc = fitz.open()
w, h = fitz.paper_size('Letter')
page = doc.new_page(width=w, height=h)
writer = fitz.TextWriter(page.rect)

# these work fine 
page.insert_text(Point(100, 100), 'page.insert_text')
page.insert_textbox(Rect(100, 200, 500, 300), 'page.insert_textbox')

# these come out garbled
writer.append(Point(100, 380), 'writer.append')
writer.fill_textbox(Rect(100, 400, 500, 500), 'writer.fill_textbox')

writer.write_text(page)
doc.save('test.pdf')
```

## Screenshots (optional)
![pdf-screenshot](https://user-images.githubusercontent.com/1437527/122449774-da8c2500-cf6b-11eb-8ab4-5a88453ce6f6.png)

## Your configuration (mandatory)
3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] 
 linux 
PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.8 on linux (64-bit).
installed using wheel method

## Additional context (optional)
This is an issue when people try to look at the resulting PDFs on iPhone iOS 14.6 or the Apple Preview app on Macintosh, multiple OS versions.

**Comment by JorjMcKie** [comment] 2021-06-18 06:33
Weird.
It seems to be an Apple issue though. When not using Base-14 fonts, but e.g. Droid Sans Regular, everything works fine.
Also literally **_al otherl_** PDF viewers I am using on Windows and Linux (evince) have no problem at all.

**Comment by JorjMcKie** [comment] 2021-06-18 06:35
Try the new test PDFs [here](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/textwriter): test.pdf, test-droid.pdf.
Both are created with `TextWriter`.
So who knows what problem iOS has here.

**Comment by JorjMcKie** [comment] 2021-06-18 07:27
There are important technical differences between TextWriter output and output via ``insert_text``/``insert_textbox``:
* TextWriter **_always embeds_** the used fonts. This forces the PDF reader to use the appearance as defined by the embedded font program. The Base-14 fonts are implemented by using a number of CFF (compact font format) font files, created by company URW. Droid Sans Regular and the like are TTF / OTF fonts.
* ``insert_text`` does not embed any Base-14 fonts. The PDF reader software therefore has full control - even responsibility - over the appearance. This is why your example works in these cases. If you would use a CFF font file instead, you would **_probably_** have the same issue.

**Comment by JorjMcKie** [comment] 2021-06-18 07:55
> you would probably have the same issue.

**Confirmed!!** Look at file ``cff-test.pdf`` in that same folder. I am using font ``NimbusSans-Regular.cff`` with ``insert_text()`` there, which is the embeddable version of Helvetica.
You will see that the iOS reader will again produce garbled appearance.
So this is now confirmed as an iOS issue.

**Comment by JorjMcKie** [comment] 2021-06-18 12:31
Assuming I can close this issue. Please comment or re-open as needed.

**Closed by JorjMcKie** 2021-06-18 12:31 UTC
Labels: not a bug, wontfix

**Comment by clark-archer** [comment] 2021-06-18 21:19
OK thanks for checking this out. I am not familiar with the inner workings of PDFs so I didn't know where to start. I think in this case I'll just have to avoid TextWriter (or make something similar that doesn't embed the fonts). I'll let you know if I come up with anything. While I agree it's an Apple problem, unfortunately I need people to be able to view my PDFs on iPad and similar. :/

**Comment by clark-archer** [comment] 2021-06-18 21:26
Oh, both test.pdf and test-droid.pdf look fine on my Apple devices. Are you saying I can avoid the issue by simply using a TTF? I'm going to try that and see if it avoids this issue. I really prefer coding with TextWriter!

**Comment by JorjMcKie** [comment] 2021-06-18 21:42
> I can avoid the issue by simply using a TTF?

Yes, exactly. Presumably you don't want to wait for years until Apple resolves this 😉.
TextWriter itself has nothing to do with. As I wrote: ``insert_text`` also fails when using CFF.
The following TTF / OTF fonts are readily available in PyMuPDF, potentially after also installing `pymupdf-fonts`:
* `fitz.Font("cjk")` - large font supporting all Latin, Chinese, Korean, Japanese. No bold, italic available. Definitely use `doc.subset_fonts()`before saving.
* `fitz.Font("figo")`- nice sans serif, bold & italics under names "figbo", "figit", "figbi"
* `fitz.Font("spacemo")` - mono-spaced, all weights also available.
* Or any OTF / TTF font you can make available via `fitz.Font(fontfile="xyz.ttf")`.

You should always use `doc.subset_fonts()` when using TTF / OTF fonts. Will reduce file size significantly.

**Comment by clark-archer** [comment] 2021-06-18 22:05
Thanks so much! I already tested it out using 'notos' and the problem vanished.

**Comment by JorjMcKie** [comment] 2021-06-18 22:21
Excellent.
Another drawback of CFF fonts is, that package `fontTools` cannot build subset fonts for them, so `doc.subset_fonts()` has no effect on them.
But it works for TTF / OTF, so "notos" and friends behave well in that respect, too.
