### ISSUE TITLE
Copying image streams to new PDF without size increase

### ISSUE THREAD

**Issue by mikkelee** [pymupdf/PyMuPDF#258] opened 2019-02-28 10:23 UTC
I'm having problems copying images from a 2.8MB PDF to a new document without it ballooning in size, even though the documentation for `extractImage()` says _"This method avoids using pixmaps wherever possible to present the image in its original format (e.g. as JPEG)"_.

```python
pdf_original = fitz.open(in_path)
pdf_new = fitz.open()

for page in pdf_original:
	newpage = pdf_new.newPage(-1)
	for image_info in page.getImageList():
		xref = image_info[0]
		img = pdf_original.extractImage(xref)
		newpage.insertImage(page.rect, stream=img['image'])

pdf_new.save(out_path, garbage=4, deflate=True)
```

The new file becomes huge -- 91 MB (without `garbage=4, deflate=True` it was even bigger at ~160 MB). I tried with the inner loop being:

```python
		 xref = image_info[0]
		 img = pdf_original._getXrefStream(xref)
		 newpage.insertImage(page.rect, stream=img)
```

Which gave a more reasonable size (3.3MB) but several of the images were either plain black or white (some worked though?!).

The images in the original PDF are 6 png files.

How do I solve this?

**Comment by JorjMcKie** [comment] 2019-02-28 11:45
Hm, I think I need to solve a problem in ``insertImage``. It does currently not re-compress images correctly, after it has read them.
Background is, that I must find out if the image has an alpha channel, so I need to convert them to pixmaps. If alpha is there, I need to store an extra SMask image containing the alpha info, etc.

Your second solution works in cases where the PNG has no transparency. If it does, you probably see these awkward results, because your method ignores the SMask. Check this with the ``getPageImageList`` method: the second item in each line is the xref of an SMask if non-zero.

After experimenting a little you try this workaround:

1. Read an image from source_pdf via ``extractImage`` as you did originally.
2. Make an **image document** from it: ``imgdoc = fitz.open(img["ext"], img["image"])``
3. Then convert this document to a PDF:

```python
pdfbytes = imgdoc.convertToPDF()
imgpdf = fitz.open("pdf", pdfbytes)
```

4. In the target PDF, use page method ``showPDFpage(rect, imgpdf, 0, ...)``. This will display the image similar to ``insertImage`` ... but hopefully better compressed. It did work in the cases I tried.

Please let me know this works in your case. If confidentiality permits, you can also send me your PDF and have me trying some things ...

**Comment by mikkelee** [comment] 2019-02-28 12:42
Thanks! I've just tried your `.convertToPDF()` workaround with the same results. It seems perhaps the problem happens when extracting the image from the PDF. `len(img['image'])` of the extracted images is in the range 8-11 MB.

I'm sending you a copy of the PDF to the email in your github profile.

**Comment by JorjMcKie** [comment] 2019-02-28 13:32
Your assumption is right. Actually, these are JPX images, which should be extracted as such - not as PNG. But they are converted to PNG in the base library (MuPDF), for some reason I don't know yet.
Investifating further ...

**Comment by mikkelee** [comment] 2019-02-28 14:12
It seems if I save the `_getXrefStream()` into a .jpx file, I can open that fine in an image editor. Perhaps it is not recognized properly when added as a stream in a PDF? 

This actually works:
```python
    for image_info in page.getImageList():
        xref = image_info[0]
        data = pdf_original._getXrefStream(xref)
        with open(f'{xref}.jpx', 'wb') as f:
            f.write(data)
        newpage.insertImage(page.rect, filename=f'{xref}.jpx')
```

**Comment by JorjMcKie** [comment] 2019-02-28 14:27
Ok, here are the findings:
MuPDF itself creates the problem: it converts JPX formats to PNG for whatever reason. This happens everywhere - even if you use any of their native CLI tools this converter to html: ``mutool draw -o page1.html 6148.pdf 1``. 
I can't do anything about that, _lamentablemente_.

I tried using PIL / Pillow. This guy at least offers a conversion to JPEG (somewhat close to JPX). The image length there is ``853.059`` instead of the PNG size ``9.815.089`` (image of page 0).

Let me check what happens if I insert PIL output in a PDF ...

**Comment by JorjMcKie** [comment] 2019-02-28 14:56
Got it. This what you can do ... with some embarrasment that you would need an additional tool :-(

```python
import fitz
import io
from PIL import Image
# ...
img = doc.extractImage(xref)
bio_in = io.BytesIO(img["image"]) # just to create a file-like object
pil = Image.open(bio_in)  # to be used for Pillow 
bio_out = io.BytesIO() # the output file-like
pil.save(bio_out, format="jpeg") # write to it in a space-saving format
imgdoc = fitz.open("jpg", bio_out.getvalue()) # open it as a PyMuPDF document
pdfbytes = imgdoc.convertToPDF() # return the PDF image of that
# ... and so on like in one of the previous posts
```

But as you also observed: if you directly read the XrefStream, then MuPDF does not know what this is.
You could then try and open that as a document similar to before via ``fitz.open("jpx", <image bytes>). This worked in my case and avoided PIL as well ...
Then go on and use showPDFpage method ...

That was a effective discussion! Thank you!
I think I will add a chapter in my documentation discussing this.

The question remains: how do I know, which extension to use in the statement ``fitz.open("jpx", ...)``?
MuPDF has no function to determine this from the file content ...
Maybe a tool like ``filetype`` could help here (pure Python on PyPI)

**Comment by JorjMcKie** [comment] 2019-02-28 14:58
Directly using ``doc.getPageImageList()`` should **always** work like that, if the smask xref is 0 (no pesky alpha considerations).

**Comment by JorjMcKie** [comment] 2019-02-28 15:15
A quick an dirty way could be to inspect the object source of the stream via ``doc._getXrefString(xref)``. At least in all cases of the example PDF the parameter ``JPXDecode`` is present ...
But using ``filetype`` is definitely cleaner.

**Comment by mikkelee** [comment] 2019-02-28 15:41
Thanks for the help, I've got some good stuff to work with now :)

**Comment by JorjMcKie** [comment] 2019-02-28 15:57
Just found out that filetype does not support JPX / JPEG2000 yet. I will send them an issue if possible.
If you want to quickly check yourself: the image should contain ``\x00\x00\x00\x0c`` in the first 4 bytes and ``img[16:24] == b"ftypjp2 "`` must be true.

**Comment by mikkelee** [comment] 2019-02-28 16:40
Excellent, that'll work. I'm fairly sure all the files I'm working with have JPX-files, so I'll just do a check and `raise SystemExit(-1)` if these bytes are wrong.

**Comment by JorjMcKie** [comment] 2019-03-03 15:29
Still working ... just for you ;-)

I found a way to circumvent that MuPDF weakness. The next PyMuPDF version (1.14.9) will return the original compression and filetype of JPX images.

Thanks again for your feedback. This is the second improvement identified based on your submissions!

**Comment by mikkelee** [comment] 2019-03-04 15:46
Excellent, thank you! :)

**Comment by mikkelee** [comment] 2019-03-09 13:18
I'm getting the JPX images from `.extractImage` now. There seems to be a weird intermittent issue with copying the stream though. If I just copy one page, the resulting PDF is fine, but if I copy multiple pages, only some of them will show up...?

**Comment by JorjMcKie** [comment] 2019-03-09 14:15
can I reproduce this with your example PDF?
What I would do:
create a new PDF, take JPX from source PDF page 0, make page 0 of new PDF and insert JPX into it, etc. for all source pages?

**Comment by mikkelee** [comment] 2019-03-09 15:17
Yes, try this:

```python
import fitz

pdf_original = fitz.open('original/6148.pdf')
pdf_a = fitz.open()

print('Copying images using stream directly')
for page in pdf_original:
    print(f'(page {page.number})')
    newpage_a = pdf_a.newPage(-1)
    for image_info in page.getImageList():
        xref = image_info[0]
        stream = pdf_original.extractImage(xref)['image']
        assert stream[0:4] == b'\x00\x00\x00\x0c' and stream[16:24] == b'ftypjp2 '
        newpage_a.insertImage(page.rect, stream=stream)

pdf_a.save('6148-streamcopy.pdf')

pdf_b = fitz.open()

print('Copying images using intermediate file')
for page in pdf_original:
    print(f'(page {page.number})')
    newpage_b = pdf_b.newPage(-1)
    for image_info in page.getImageList():
        xref = image_info[0]
        stream = pdf_original.extractImage(xref)['image']
        assert stream[0:4] == b'\x00\x00\x00\x0c' and stream[16:24] == b'ftypjp2 '
        tmp = f'{xref}.jpx'
        with open(tmp, 'wb') as f:
            f.write(stream)
        newpage_b.insertImage(page.rect, filename=tmp)

pdf_b.save('6148-filecopy.pdf')
```

The `filecopy` PDF works correctly for me, but the `streamcopy` PDF has blank/white pages...

**Comment by JorjMcKie** [comment] 2019-03-09 15:32
I have tried this script with success:

```python
import fitz

doc = fitz.open("6148.pdf")
out = fitz.open()

for page in doc:
    outpage = out.newPage(width=page.rect.width, height=page.rect.height)
    xref = doc.getPageImageList(page.number)[0][0]
    img = doc.extractImage(xref)
    imgdoc = fitz.open(img["ext"], img["image"])
    pdfbytes = imgdoc.convertToPDF()
    imgpdf = fitz.open("pdf", pdfbytes)
    outpage.showPDFpage(outpage.rect, imgpdf, 0)

out.save("new-6148.pdf")
```
So I have avoided `insertImage `and instead took the detour over `showPDFpage`. The resulting PDF had the same size (even a bit smaller, but probably because I copied just the images, not the text).

And as you say: if I use insertImage for just one page, it works fine.
I will investigate now, what may go wrong with `insertImage` - it obviously is not the `extractImage` part ...

**Comment by mikkelee** [comment] 2019-03-09 15:42
Just checked to see if it might be a buffer getting overwritten, by copying the stream using `bytes()` on it when inserting the image, but that doesn't make a difference.

**Comment by JorjMcKie** [comment] 2019-03-09 15:47
getting closer - this script worked, it saves the extracted images to disk and then inserts from those files:

```python
import fitz

doc = fitz.open("6148.pdf")
out = fitz.open()

for page in doc:
    outpage = out.newPage(width=page.rect.width, height=page.rect.height)
    xref = doc.getPageImageList(page.number)[0][0]
    img = doc.extractImage(xref)
    ofn = str(xref) + "." + img["ext"]
    fout = open(ofn, "wb")
    fout.write(img["image"])
    fout.close()
    outpage.insertImage(outpage.rect, filename=ofn)

out.save("files-6148.pdf")
```

**Comment by JorjMcKie** [comment] 2019-03-09 15:49
so there must be an issue when inserting from a bytes image buffer.
let's see ...

**Comment by JorjMcKie** [comment] 2019-03-09 16:18
Got it!!!
The bytes object handed in to the C-level part of the function was freed by the Python level, so it must be copied to a MuPDF buffer instead of just pointing to the underlying memory area.
The following script nows works as I would have expected:

```python
import fitz

doc = fitz.open("6148.pdf")
out = fitz.open()

for page in doc:
    outpage = out.newPage(width=page.rect.width, height=page.rect.height)
    xref = doc.getPageImageList(page.number)[0][0]
    img = doc.extractImage(xref)
    outpage.insertImage(outpage.rect, stream=img["image"])

out.save("new-6148.pdf")
```

Can't imagine why this never popped up before ...

**Comment by mikkelee** [comment] 2019-03-09 16:21
Aha, this sounds like it requires an internal PyMuPDF change?

**Comment by JorjMcKie** [comment] 2019-03-09 16:23
Yes, unfortunately. There is nothing to be changed on your side. Although you will (probably) have to do another `python setup.py install` for PyMuPDF.

I am going to prepare a new patch for this now.
It will take me the rest of the weekend I suppose, because I want to include another new feature, which is still under construction.
OK with you?

**Comment by JorjMcKie** [comment] 2019-03-09 16:24
I could also publish the current state now and another version 2 days later.

**Comment by mikkelee** [comment] 2019-03-09 16:41
Alright, that is fine. I will just use the intermediate file method for now, there's no deadline on my end :)

**Comment by JorjMcKie** [comment] 2019-03-09 17:48
ok thanks!

**Comment by JorjMcKie** [comment] 2019-03-10 17:34
Just uploaded to PyPI. Hope the most recent issue is fixed with it.

**Comment by mikkelee** [comment] 2019-03-11 04:44
I can confirm that it works for me. Thanks for excellent support! :)

**Comment by JorjMcKie** [comment] 2019-03-11 06:16
Glad to read that - thanks!

**Closed by JorjMcKie** 2019-03-11 06:16 UTC
Labels: enhancement, postpone

**Comment by jerrymamachao** [comment] 2019-09-12 06:06
Happen to have an application needing extract pages from PDF and save as new PDF file. With fitz doc object, by selecting pages and save, the file size is almost as big as original file. That's not good for me to attach the new files up to 40MB in total to email. So I searched around in Google and was led to here. Actually JorjMcKie was almost there, except one annoying bug from PYMUPDF. doc.getPageImageList(page.number) doesn't work as it reads (or intends). no matter what page# you passed to it, it always return you the xref for whole doc. That's why I got new pdf files with pages always be the 1st page of original pdf. so I altered it little bit to bypass the issue. Hope it works for you.

Thanks to JorjMcKie's great work on this. It lead me to the right direction.

import fitz

doc = fitz.open("6148.pdf")
out = fitz.open()

xref = doc.getPageImageList(0)

for page in range(len(doc)):
    img = doc.extractImage(xref[page][0])
    imgdoc = fitz.open(img["ext"], img["image"])
    pdfbytes = imgdoc.convertToPDF()
    imgpdf = fitz.open("pdf", pdfbytes)
    outpdf.insertPDF(imgpdf)

out.save("new-6148.pdf")
doc.close()
out.close()

I passed this on my windows + python 3.7.4 + pymupdf 1.16.1.
