### ISSUE TITLE
PDF file not updated after incremental save

### ISSUE THREAD

**Issue by raphael715** [pymupdf/PyMuPDF#3136] opened 2024-02-06 15:42 UTC
### Description of the bug

Based on an existing PDF file, my aim is to remove empty/blank pages and save the result into the original PDF file. But when opening it on the web (Edge, Chrome) I have the original number of pages wwhile with Adobe there has been a page correctly removed.

### How to reproduce the bug

 I have written the following code that does the job : 

`doc = fitz.open(self.filepath)
 pages_to_remove = []

  for i in range(doc.page_count):
       pg = doc[i]
       pg_rect = pg.rect
       text_margin = pg_rect + (0, 50, 0, -50)
       img_margin = pg_rect + (0, 40, 0, -40)
       # Check existence of texts, images or tables
       img_clip = [pg_img for pg_img in pg.get_images() if pg_img[1] > img_margin[1]]
       text_clip = pg.get_textpage(text_margin).extractText()
       text_clip = re.sub(r'[^a-zA-Z0-9]', '', text_clip).replace("\n", "").replace("\t", "").replace(" ", "")
       table_clip = pg.find_tables().tables

       if not img_clip and not table_clip and not text_clip:
           pages_to_remove.append(i)
         
      for page_index in reversed(pages_to_remove):
          doc.delete_page(page_index)
      
      doc.save(self.filepath, incremental=True, encryption=0)
      doc.close()`

However, when performing incremental saving I faced two issue : 

- My changes modify the file encryption so I have to google and see that fixing encryption to 0 fix the issue but it is very unclear why this happened ;
- When runing my code and printing the number of pages after the removal, I have the original number of pages minus 1 so perfect ! But when I open the file in the web (Edge or chrome) the file has the original number of pages and there is still a blank page. And if opened with Adobe, the file contains only one image. I guess there is a cache issue but how can I fixe it.

Thanks for help

### PyMuPDF version

1.23.20

### Operating system

Windows

### Python version

3.8

### Test file
[test_pdf.pdf](https://github.com/pymupdf/PyMuPDF/files/14229706/test_pdf.pdf)

**Comment by JorjMcKie** [comment] 2024-02-07 06:42
You did not include data for issue reproduction, so we cannot accept this as a bug report.
Otherwise, I have tested page deletion with incremental save both, with encrypted and non-encrypted files, confirming that this works, and that the usual PDF viewers (Adobe, browsers, ...) take appropriate note of that and correctly reflect e.g. the page count.
When saving incrementally, the encryption cannot be changed, which you correctly ensured via setting `PDF_ENCRYPT_KEEP`. You could have used the shorter `doc.saveIncr()`.

I am sure you are aware that incremental save does not remove anything physically - only changed objects are appended to the file, which in this case are any affected page object arrays from within the PDF's page tree.

On another note, your page emptiness check is incomplete and contain unnecessary checks:
* you should also check for the absence of links, annotations and fields via asserting `page.first_annot == page.first_link == page.first_widget == None`.
* you do not need to check for the absence of tables, because "no text" implies "no table"
* you did not check for the absence of vector graphics: `page.get_drawings() == []`.
* The most complete and efficient check for image presence is using the variant of `get_text("blocks", flags=fitz.TEXTFLAGS_DICT)`. If (any type of!) images exist on page then this list contains items with block type 1. The same list can be used for text presence (block type 0). If there are any text blocks, then the string must only contain white space characters.

**Comment by JorjMcKie** [comment] 2024-02-10 14:11
Just as a reminder:
Without reproducing data, we will need to close this issue on 2024-02-12.

**Comment by raphael715** [comment] 2024-02-10 15:44
> Just as a reminder: Without reproducing data, we will need to close this issue on 2024-02-12.

Sorry about that, but I thing the mentionned bug isn't linked to the pdf file because I have tested the approach for several files and the same phenomenon occurs.I have also tested the script on different computer. 
You will find a test file in my original comment. Thanks

**Comment by JorjMcKie** [comment] 2024-02-11 07:58
This attached file is unusable, because it only has 1 page:
You can delete that page, but you cannot it save anymore, because a PDF with 0 pages cannot be save - not incrementally, not otherwise.

**Comment by JorjMcKie** [comment] 2024-02-11 08:25
I gave it another try:
* Took your PDF and added 2 empty pages: one before the existing page, the other at the end.
* save incrementally, closed, re-opened
* deleted pages via `doc.delete_pages([0, 2])`.
* save incrementally
* viewed the resulting file using:
   - SumatraPDF, MuPDF
   - Adobe
   - PDF XChange Viewer
   - Nitro PDF viewer
   - Foxit Reader
   - evince (Linux)
   - MS Edge
   - Firefox (Linux)

Result:
**_All above viewers_** showed the correct result - namely 1 page -  **_except MS Edge_** which showed 2 pages.

So this clearly seems to be an MS Edge problem (resp. the PDF plugin it uses).
Please talk to them.

**Closed by JorjMcKie** 2024-02-11 08:25 UTC
Labels: not a bug
