### ISSUE TITLE
keeping page ref after close leads to crashes in 1.17.1 (but not in 1.16.xx)

### ISSUE THREAD

**Issue by cbm755** [pymupdf/PyMuPDF#533] opened 2020-06-20 08:19 UTC
If I take a page ref, then close the doc, I eventually (after repeating a couple times) I get:
  * a zero-len doc
  * crashes
This look related to #16.

## To Reproduce

Consider this code to crawls a directory of pdf files (their content seems unimportant).
```
from glob import glob
import fitz

for i, f in enumerate(glob("*.pdf")):
    print("i={}, file={}".format(i, f))

    doc = fitz.open(f)

    print("  {} pages".format(len(doc)))

    front_page = doc[0]   # remove this line and no crash

    doc.close()
```
I'm not sure if that is supposed to work or not but it reliably did work in 1.16.xx.  Even if its invalid it probably shouldn't be segfaulting!

## 
Sometimes I get crashes:
```
i=0, file=more4.pdf
  20 pages
i=1, file=more0.pdf
  0 pages
Traceback (most recent call last):
  File "foo.py", line 12, in <module>
    front_page = doc[0]   # remove this line and no crash
  File "/home/cbm/.local/lib/python3.8/site-packages/fitz/fitz.py", line 3577, in __getitem__
    raise IndexError("page not in document")
IndexError: page not in document
fish: Job 2, “python foo.py” terminated by signal SIGSEGV (Address boundary error)
```
other times just the IndexError (note: I'm using multiple copies of the same PDF file for this MWE).

## Expected behavior

I'm not sure but the MWE runs without error on 1.16.18.

## configuration
 - Fedora 32
```
3.8.3 (default, May 15 2020, 00:00:00) 
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] 
 linux 
 
PyMuPDF 1.17.1: Python bindings for the MuPDF 1.17.0 library.
Version date: 2020-06-13 07:54:31.
Built for Python 3.8 on linux (64-bit).
```

## other info

Downstream issue: https://gitlab.com/plom/plom/-/issues/919

**Comment by cbm755** [comment] 2020-06-20 08:23
update: the MWE seems ok (i.e., does not crash) on 1.17.0 as well

**Comment by JorjMcKie** [comment] 2020-06-20 09:26
Thanks for submitting this! Weird.
No problems either if I do ``page = None`` before the ``doc.close()``.

**Comment by JorjMcKie** [comment] 2020-06-20 11:08
Found the cause. My effort to improve inline documentation caused deletion of a critical piece of code ... 😡, which is responsible for keeping the parent-child relationship between document and its pages in sync.
Thanks again for spotting this.

**Comment by cbm755** [comment] 2020-06-20 19:48
Happy to help!

May I ask if its ok to close an pdf after inserting it into a new pdf (but before saving that new PDF).  I.e., something like:
```
bigdoc = fitz.open()

for f in ...
    doc = fitz.open(f)
    front_page = doc[0]
    # ... do some manipulation, adding text or images
    bigdoc.insertPDF(doc)
    del front_page    # (workaround https://github.com/pymupdf/PyMuPDF/issues/533)
    doc.close()
doc2.save(...)
```

**Comment by JorjMcKie** [comment] 2020-06-20 20:27
The error you detected, only (fingers crossed) pertains to the ``close()`` method of the ``Dpcument`` class.

If you just **_don't_** close, everything should be fine: all resources will still be feed / dropped, just at some other point in time. E.g. the "close" (meaning dropping associated resources) will simply occur when you assign the next ``Document`` to ``doc``. At that point, ``front_page``-associated resources will also be freed, if you hadn't deleted it earlier.

The last "version" of variable ``doc`` will be freed at your script's end.

**Comment by cbm755** [comment] 2020-06-20 21:26
Is `close` called on GC?  If so, seems to me 1.17.1 would be still susceptible to this bug right?

Are you saying it would be a better pattern to not call `.close()` even in absence of this bug?

**Comment by JorjMcKie** [comment] 2020-06-20 22:24
> Is close called on GC?

No. But still all resource freeing will take place - no memory leakage will occur. Using it is completely optional and only needed if you want to control the point in time when resources are freed, or when you need to remove the OS lock on the filename or so.

This bug really only occurs if the method is invoked explicitely.

**Comment by cbm755** [comment] 2020-06-23 07:18
The context manager version of this pattern *also* exhibits this bug:
```
bigdoc = fitz.open()
for f in ...
    with fitz.open(f) as doc:
        front_page = doc[0]
        # ... do some manipulation, adding text or images
        bigdoc.insertPDF(doc)
bigdoc.save(...)
```

I did that b/c I was worried about exhausting file handles without the explicit close and it seemed more pythonic.

**Comment by JorjMcKie** [comment] 2020-06-23 09:44
That's true: the context manager (which I coded, obviously) **_does_** use close.
If you are concerned about resource consumption, you can use ``doc = None`` instead of close for the time being.

**Comment by JorjMcKie** [comment] 2020-06-23 10:29
But actually there is no reason for concern:
The document's file handle is kept inside MuPDF. The release of resources including file handles is automatically executed if the Python variable ``doc`` is assigned to something else (or even deleted via ``del doc``).
So the worst think happening in your example is the somewhat extended lifetime of the **_last_** ``doc`` if you don't actively ``close`` or re-assign it.
The Python-C-interface generator software, SWIG, provides a "deletion" slot for for Python classes which are based on some C constructs. This is the point where the resp. MuPDF destructor is invoked whenever Python deletes a document instance, i.e. invokes its ``__del__``.
So in PyMuPDF there are several ways to achieve this: re-assigning the instance variable, deleting it or invoking ``close``.

**Comment by cbm755** [comment] 2020-06-24 02:52
Thanks, that's a weight off my mind: I shall just remove `.close()` for now.

(And eventually switch to the context manager approach, after 1.17.2).

**Comment by JorjMcKie** [comment] 2020-06-24 16:38
Just uploaded v1.17.2 to PyPI. Hope this issue is fixed by it.

**Closed** 2020-06-24 16:38 UTC
Labels: bug

**Comment by cbm755** [comment] 2020-06-24 16:59
thanks, tested and works good for me!

**Comment by wodegithubzh** [comment] 2024-03-21 03:56
pdfDoc = fitz.open(path)
for p in list(pdfDoc)[:]:#OK
    pass
print('OK')
for p in pdfDoc[:]:#IndexError: page not in document
    pass

**Comment by wodegithubzh** [comment] 2024-03-21 04:07
`pdfDoc = fitz.open(path)
for p in pdfDoc:#OK
    pass
print('OK')
for p in list(pdfDoc)[:]:#OK
    pass
print('OK')
for p in pdfDoc[:]:#IndexError: page not in document
    pass`

**Comment by wodegithubzh** [comment] 2024-03-21 04:09
```python
pdfDoc = fitz.open(path)
for p in pdfDoc:#OK
    pass
print('OK')
for p in list(pdfDoc)[:]:#OK
    pass
print('OK')
for p in pdfDoc[:]:#IndexError: page not in document
    pass
```

**Comment by julian-smith-artifex-com** [comment] 2024-03-21 11:46
Thanks for this. I have added support for slices to the Document class, in my tree. This allows `pdfDoc[:]` to work properly. Depending on reviews and timing this fix may be in the next release.
