### ISSUE TITLE
Problematic PDF causing fitz.open to freeze and memory usage to spike

### ISSUE THREAD

**Issue by vbanos** [pymupdf/PyMuPDF#1007] opened 2021-04-13 18:44 UTC
This issue occurs when trying to open the following PDF file:
http://web.archive.org/web/20041108002108id_/http://24.73.239.154:8081/DOCS/mt/2/PDF/AS17_CM.PDF

We download the file and try to `fitz.open` it in out Python program.
The program gets stuck on `fitz.open` and memory usage increases until system memory usage reaches 100% and the program gets terminated.

To reproduce it, download the file and try to open it using `fitz.open`.

Note that Google Chrome doesn't render the file properly as well but `pdftotext` works and some text is extracted.

We are using Ubuntu 18.04 LTS, Python 3.7.9 and PyMuPDF 1.18.10. The installation method is `wheel`.

**Comment by JorjMcKie** [comment] 2021-04-13 19:11
That's problematic in more than one sense:
* cannot download using Firefox
* cannot download using MS Edge
* I am not using Chrome, so that is not an option.

I hope it is a reasonable file size at all?
Did you try Adobe Acrobat or other viewers?
Did you try the MuPDF viewer or ``mutool draw -o page1.pdf problem.pdf 1``?
This will convert and copy the first page of the file to a new PDF. If **_this does not work_**  you have detected an issue that can only be addressed by MuPDF and you should submit an issue to their bug system: https://bugs.ghostscript.com/enter_bug.cgi.

**Comment by JorjMcKie** [comment] 2021-04-13 21:15
New status:
I found a different web site to download from directly - instead of using a browser-builtin PDF viewer.
So this seems to be a NASA voice transscript in some scanned format and with an OCR-ed text layer.
It can be displayed by several viewers like Adobe Acrobat and PDF XChange.
It **_cannot be displayed by the MuPDF viewer_**! It abnormally exits - obviously with memory issues as you indicated. There was some effort to send a warning, which however was not successful either.

The PDF can however be converted via `mutool draw -o converted.pdf AS17_CM.PDF` to a new PDF which is then easily displayable.
The converted PDF can also be opened by PyMuPDF, MuPDF, SumatraPDF, etc., without any problems, and text can also be extracted.

So suspicion confirmed that it is an **_upstream issue_**, which you should submit to MuPDF's bug system, mentioned in my previous post.

**Closed** 2021-04-14 08:29 UTC
Labels: upstream bug, wontfix

**Comment by vbanos** [comment] 2021-04-15 20:02
I submitted a bug to MuPDF bug system. Thank you for looking into this!
https://bugs.ghostscript.com/show_bug.cgi?id=703789

**Comment by JorjMcKie** [comment] 2021-04-15 23:52
Thanks a lot for the information!
