### ISSUE TITLE
Problems adding a text widget that runs a script when a field is changed

### ISSUE THREAD

**Issue by Seth-Bullock** [pymupdf/PyMuPDF#1935] opened 2022-09-21 21:27 UTC
When I add a new text Widget that includes javascript in the script_calc element, it appears as a regular form field that I can enter text into instead of an auto-calculated field pre-filled with the result of the javascript calculation.

The following code iterates over the existing Widgets on the page until it finds one called "Total". Ultimately, we want to replace this field with one that auto-calculates the value. Since I can't delete the Widget either, for now, we create a new widget 40pt to the left of it. The new Widget has some js code in its ```script_calc``` that auto calculates a sum of two values drawn from other fields.

```
doc = fitz.open("sheet.pdf")
page = doc[1]
for field in page.widgets():

    if "Total" in field.field_name:
        print("\nAutomating Total")
        rect = field.rect
        name = field.field_name

        widget = fitz.Widget()
        widget.text_fontsize = 0
        widget.rect = fitz.Rect(rect[0]-40, rect[1], rect[2]-40, rect[3])  # shift it over
        widget.field_type = fitz.PDF_WIDGET_TYPE_TEXT
        js = 'var T = this.getField("TCurrent").value;\n'
        js += 'var S = this.getField("SCurrent").value;\n'
        js += 'event.value = Math.floor(T / 10) + Math.floor(S / 10)'
        widget.script_calc = js
        widget.field_name = name+" New"
        widget.field_value = "test"   # this appears in the pdf to start with
        new = page.add_widget(widget)

doc.need_appearances(True)

doc.save("new_sheet.pdf",garbage=3, clean=True, deflate=True)
doc.close()
```
The code runs without error. I expect the new pdf to have a new auto-calculated form field 40 pts to the left of the original. Instead I get a regular text entry field with no auto-calculation happening in it.

Ultimately, I would also like to delete the original "Total" Widget. 
But including the line: ```next = page.delete_widget(field)``` throws an error: 

```
File "C:\Users\...\venv\lib\site-packages\fitz\fitz.py", line 1823, in __del__
    annot = getattr(self, "_annot")
AttributeError: 'Widget' object has no attribute '_annot'

```
Strange that it doesn't identify the line of my code that is responsible...

## Your configuration (mandatory)
PyMuPDF 1.20.2: Python bindings for the MuPDF 1.20.3 library.
Version date: 2022-08-13 00:00:01.
Built for Python 3.8 on win32 (64-bit).

**Comment by JorjMcKie** [comment] 2022-09-22 15:05
Maintaining javascript sources for fields is supported by PyMuPDF.
But (triggering the) **_execution_** of javascript (whether for fields or not) currently is not.
In so far this is a duplicate of the enhancement request #1763.

Removing fields via `page.delete_widget()` is supported and works. So I would need a separate new issue with resp. reproduction data for this.

**Comment by Seth-Bullock** [comment] 2022-09-23 08:37
Thanks for the quick response - I wondered whether (even though this is not supported by pymupdf) just setting the right flags or properties within the field would cause its js to be run by the pdf viewer.  But maybe there's more complicated changes to other parts of the pdf that are needed as well.  You can close this now if there's not much more to say on it. Thanks again.

**Closed** 2022-09-23 12:36 UTC
Labels: duplicate, enhancement
