### ISSUE TITLE
Again: releases removed

### ISSUE THREAD

**Issue by zopyx** [pymupdf/PyMuPDF#396] opened 2019-11-08 06:17 UTC
PyMUDPDF 1.14.19  was replaced/removed with 1.14.19.2

Why does this happen OVER AND OVER again?

When will you learn that released is released?

Are you unable to learn your lessons and stick to best practices?

RELEASED IS RELEASED:

**Comment by JorjMcKie** [comment] 2019-11-08 08:07
duplicate of #348 & #342 
And please do control your way of communication: this is far beyond the limits of courtesy and respect!

**Closed by JorjMcKie** 2019-11-08 08:07 UTC
Labels: bug, duplicate, wontfix
