### ISSUE TITLE
page.get_pixmap bug - RuntimeError: Private data too large to pack into display list node

### ISSUE THREAD

**Issue by zcakzhuu** [pymupdf/PyMuPDF#2559] opened 2023-07-27 14:40 UTC
get_pixmap worked for most of the pages in the document except a few. Page 10 is an example that failed.
The [document](https://www.allianz.com/content/dam/onemarketing/azcom/Allianz_com/sustainability/documents/Allianz_Group_Sustainability_Report_2022-web.pdf) can be downloaded from the link embedded. Here is the code I used:

```python
import fitz

filepath = <put the document path here>
doc = fitz.open(filepath)

page = doc[10]
pix = page.get_pixmap(dpi=200)
```

The error message is the following
```bash
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/var/tmp/ipykernel_23021/213934831.py](https://vscode-remote+ssh-002dremote-002bmengting-002dnlp-002dsandbox2.vscode-resource.vscode-cdn.net/var/tmp/ipykernel_23021/213934831.py) in ?()
----> 1 pix=page.get_pixmap(dpi=200)
      2 pix

[/opt/conda/envs/python38/lib/python3.8/site-packages/fitz/utils.py](https://vscode-remote+ssh-002dremote-002bmengting-002dnlp-002dsandbox2.vscode-resource.vscode-cdn.net/opt/conda/envs/python38/lib/python3.8/site-packages/fitz/utils.py) in ?(page, matrix, dpi, colorspace, clip, alpha, annots)
    891             colorspace = csRGB
    892     if colorspace.n not in (1, 3, 4):
    893         raise ValueError("unsupported colorspace")
    894 
--> 895     dl = page.get_displaylist(annots=annots)
    896     pix = dl.get_pixmap(matrix=matrix, colorspace=colorspace, alpha=alpha, clip=clip)
    897     dl = None
    898     if dpi:

[/opt/conda/envs/python38/lib/python3.8/site-packages/fitz/fitz.py](https://vscode-remote+ssh-002dremote-002bmengting-002dnlp-002dsandbox2.vscode-resource.vscode-cdn.net/opt/conda/envs/python38/lib/python3.8/site-packages/fitz/fitz.py) in ?(self, annots)
   6439 
   6440         CheckParent(self)
   6441 
   6442 
-> 6443         val = _fitz.Page_get_displaylist(self, annots)
   6444         val.thisown = True
   6445 
   6446         return val

RuntimeError: Private data too large to pack into display list node
```

**Comment by JorjMcKie** [comment] 2023-07-28 11:11
You did not provide all mandatory information - among them notably your PyMuPDF version.
Presumably, you are using a version where this issue has not been fixed.
With the current PyMuPDF I cannot reproduce the problem.
Going to close this - please re-open with **_all mandatory information_** if the error occurs again.

**Closed by JorjMcKie** 2023-07-28 11:11 UTC
Labels: not a bug
