### ISSUE TITLE
Artifact characters extracted in some PDFs

### ISSUE THREAD

**Issue by tristan19954** [pymupdf/PyMuPDF#1241] opened 2021-09-01 10:33 UTC
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/1240

<div type='discussions-op-text'>

<sup>Originally posted by **tristan19954** September  1, 2021</sup>
Hello,
I have an issue when extracting text from a pdf file. I have done this on hundred of documents with goo results, but this particular pdf has an unexpected behavior. 
Here is a look at the pdf :
![image](https://user-images.githubusercontent.com/78732745/131655986-508ea781-2d73-4fe3-b3f8-a94f9829a797.png)

and now the text extracted : 
![image](https://user-images.githubusercontent.com/78732745/131656200-c984a944-b69a-4b00-9e29-18a0c7491996.png)

As you can see, a bunch of "i" and "t" characters appeared on every line of text. I thought it might be an issue with the pdf, but when trying an online pdf converter, I didn't get those characters.

Any idea on what the issue might be?
</div>

**Comment by JorjMcKie** [comment] 2021-09-01 12:59
As I wrote in #1240: I do need a reproducer file and a code snippet for how you extracted the text.

**Comment by tristan19954** [comment] 2021-09-01 13:03
> 
> 
> As I wrote in #1240: I do need a reproducer file and a code snippet for how you extracted the text.

I just provided a code snippet in the discussion. Maybe that might help

**Comment by JorjMcKie** [comment] 2021-09-04 09:49
Caused by characters with empty bboxes. Fixed by checking this at various places.

**Comment by JorjMcKie** [comment] 2021-09-16 16:46
new version 1.18.18 now on PyPI

**Closed by JorjMcKie** 2021-09-16 16:46 UTC
Labels: bug
