### ISSUE TITLE
result = page.insertTextbox(rect, f'{t}', fontsize=size, color=color) has problem if pdf orientation is 270 

### ISSUE THREAD

**Issue by vampiresati** [pymupdf/PyMuPDF#2083] opened 2022-11-25 14:46 UTC
_**Please provide all mandatory information!**_

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Your configuration (mandatory)
 - Operating system, potentially version and bitness
 - Python version, bitness
 - PyMuPDF version, installation method (**wheel** or **generated** from source).

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment] 2022-11-25 17:43
You did not mention what the issue is.

**Comment by JorjMcKie** [comment] 2022-11-27 04:56
Closing this because of lack of information.

**Closed by JorjMcKie** 2022-11-27 04:56 UTC
