### ISSUE TITLE
installation through pip3.9 is broken

### ISSUE THREAD

**Issue by rakafo** [pymupdf/PyMuPDF#805] opened 2021-01-02 15:18 UTC
Hello,
I'm getting multiple errors when trying to import fitz - first there was an issue that 'frontend' wasn't picked up as a dependency by pip. Installing that, I'm now getting the following:

```
(venv) user1@pc ~> python3
Python 3.9.1 (default, Dec  8 2020, 00:00:00)
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/home/user1/.local/lib/venv/lib64/python3.9/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
```

**Comment by JorjMcKie** [comment] 2021-01-02 17:32
This issue is directed to the wrong package.
Duplicate of #523.

**Closed** 2021-01-02 17:32 UTC
Labels: not a bug
