### ISSUE TITLE
Rect with different behavior - Position 0,0

### ISSUE THREAD

**Issue by rvilvert** [pymupdf/PyMuPDF#2652] opened 2023-09-09 05:03 UTC
I'm working in a project where I have to draw a rect in some PDF files. It was working great till today when I run this:

p1 = fitz.Point(0,0)
p2 = fitz.Point(50,50)
page.draw_rect(fitz.Rect(p1, p2), color=(0, 1, 0), fill=(0, 1, 0), width=3)

The expected behavior was a rect on top right conner, but for this file its creating on top left corner. 

Both PDF files only have 1 page and the same orientation. 

Your configuration (mandatory)
 - Windows 11
 - python 3.11
 - pip 23.2.1
 - PyMuPDF 1.23.3
 - PyMuPDF 1.23.3: Python bindings for the MuPDF 1.23.2 library.
 - Version date: 2023-08-31 00:00:01.
 - Built for Python 3.11 on win32 (64-bit).

I'm new with PyMuPDF, did some search but no luck so far.

**Comment by JorjMcKie** [comment] 2023-09-09 05:47
Point p1 is the top-left corner isn't it?
You didn't add a reproducing file. Some pages contain awkward "geometry changes" which are still active at the end of the page's `/Contents` stream. In these cases your inserts can land wherever on the page or with an unexpected size, etc.
To prevent this from happening use `page.clean_contents()` or `page.wrap_contents()` before inserting anything.
Pease confirm and close the issue, otherwise append a reproducing file.

**Comment by rvilvert** [comment] 2023-09-09 16:37
Hi @JorjMcKie , thanks for the quick response, unfortunately it didn't work

I just created a repo with the example: https://github.com/rvilvert/PyMuPDF_2652

**Comment by JorjMcKie** [comment] 2023-09-09 17:34
This is not a bug, but works as designed.
The page is rotated by 90°.
All coordinates extracted from a page are relative to the unrotated page - and vice versa: when inserting **_anything_**, the coordintes must be given / will be interpreted as if pertaining to the unrotated page.
So if you de-rotate that page, you will see that your rectangle is at the top-left position - as you intended.
If you want the rect to **_appear_** top-left when the page is displayed, you must transform it appropriately. There exist special matrices that help you do this: `page.rotation_matrix` and `page.derotation_matrix`.
Using this will deliver the correct result ... BTW in all cases: even when the page is not rotated:
```python
pdf_page.draw_rect(
    rect * pdf_page.derotation_matrix, color=(1, 0, 0), fill=(0, 1, 0), width=3
)
```

**Closed** 2023-09-09 17:35 UTC
Labels: not a bug
