### ISSUE TITLE
Performance drop in page.draw_line() & page.draw_rect() after release 1.24.1

### ISSUE THREAD

**Issue by dcleres** [pymupdf/PyMuPDF#3800] opened 2024-08-22 08:21 UTC
### Description of the bug

I am using the `PyMuPDF` library to draw rectangles and lines on a PDF. Since the release of the 1.24.2 version, I observed a performance drop on specific files. In my use case, I am working with digitally native files as well as scanned documents on which OCR was performed. I do not observe any issues on the PDF document that originate from scans. Still, for some digital native documents, I see that the drawing of rectangles and lines can take up to 1'000 times longer when I use one or the other version of the library. 

In version 1.24.1, the average `draw_line` and `draw_rect` operations takes 0.0001s, whereas with version 1.24.2 (and the newer releases) the average `draw_line` and `draw_rect` operation takes 0.15s.

If you could look into it that would be a great help. Thank you! 

### How to reproduce the bug

Classic API calls to the `draw_line` and `draw_rect` functions on a PDF document page. 

```python
page.draw_rect(
    background_rect * page.derotation_matrix,
    width=0,
    fill=fitz.utils.getColor(color),
    fill_opacity=0.2,
)
```

or 

```python
page.draw_line(
    background_rect.top_left * page.derotation_matrix,
    background_rect.bottom_left * page.derotation_matrix,
    color=fitz.utils.getColor(depth_is_correct_color),
    width=6,
    stroke_opacity=0.5,
)
```

Sadly, I currently cannot share the PDF file as it is not part of a public dataset. The only thing I observed was that the PDFs causing issues were digitally born. 
 
                

### PyMuPDF version

1.24.2

### Operating system

MacOS

### Python version

3.12

**Comment by JorjMcKie** [comment] 2024-08-22 12:29
In version 1.24.2 we introduced `Document.bake()` which allows converting annotations and widgets to permanent page content, without appearance changes.

As an aside of this, we also introduced code that removes the need to ensure cleaning up the page geometry before insertions (of any kind, not only drawings, but also text, images, annotations).
This code checks whether the graphics state push and pop commands `q`/`Q` are in a balanced state and all geometry changes (caused by matrices) are properly wrapped in a pair of these commands.

So one no longer will need `page.clean_contents()` executions to ensure that insertions don't land in the wild. IAW insertions are now **_worry-free!_**

While I am a little surprised about a slow down of the magnitude you are reporting, **_some_** slowdown is certainly unavoidable.

If you do millions of drawings, the general recommendation certainly is to **_not do it_** via `Page.draw_*()` commands!
Every such command will do the above check!
Instead, create a `Shape` object for the page and collect all draw commands with it. When done do a `Shape.commit()` to write its content to the page - at which point the mentioned new code will be executed ... i.e. one time only.

If you see no improvement, we will need a reproducing file. You can always send that file directly to me or a maintainer colleague so it won't become publicly exposed here.

**Comment by JorjMcKie** [comment] 2024-08-22 12:44
No need to supply example files - just confirmed a significant speed difference using this script:
```python
import fitz
import time

mt = time.perf_counter
print(fitz.version)
doc = fitz.open()
page = doc.new_page()

count = int(1e4)
t0 = mt()
for i in range(count):
    page.draw_rect((0, 0, 10, 10))
t1 = mt()

print(f"page.draw_rect time {t1-t0}")
```

**Comment by JorjMcKie** [comment] 2024-08-22 12:55
Another test comparing Page.draw_rect and Shape.draw_rect:
```python
import pymupdf
import time

mt = time.perf_counter
print(pymupdf.version)
doc = pymupdf.open()
page = doc.new_page()

count = int(1e4)
t0 = mt()
for i in range(count):
    page.draw_rect((0, 0, 10, 10))
t1 = mt()

print(f"Page.draw_rect time {t1-t0}")

page = doc.new_page()
t0 = mt()
shape = page.new_shape()
for i in range(count):
    shape.draw_rect((0, 0, 10, 10))
shape.commit()
t1 = mt()

print(f"Shape.draw_rect time {t1-t0}")
```

Delivers this result:
```bash
('1.24.9', '1.25.0', '20240724000001')
Page.draw_rect time 24.83695300000545
Shape.draw_rect time 0.1714471000013873
```
Which is 145 times faster!

**Comment by dcleres** [comment] 2024-08-22 14:27
Thank you for the suggestion to use the `Shape`object to draw my annotations. This increased significantly the speed of the code under version 1.24.9 as well as in 1.24.1. 

1.24.1 is still significantly faster, but if I understood correctly, you are looking into that. 

In my setting: 
- the 1.24.1 version now runs in: 0.43s
- the 1.24.9 version runs now in: 5.72s (previously 48s) 

Thank you very much for the help I have been looking for speed improvement in this part for a while!

**Comment by JorjMcKie** [comment] 2024-08-22 15:29
* In v1.24.1 and before, Page-based draws are about 4 times slower than Shape-based ones.
* Starting with v1.24.3 the old PyMuPDF implementation based on original `fitz` code is no longer available. Page-based draws are up to 2 times slower slower now - **_not_** counting the duration of the new code around graphics command balance.
* **_However_**, for a fair timing comparison, 1.24.1 Page-based draws should have included the duration of `page.clean_contents()` because at that time, this was the only way to **_guarantee_** correct positioning. Omitting it meant accepting the risk of wrong positions of inserts at that time.
* We always had a home-grown = PyMuPDF-specific) page method "wrap_contents()` which simply always wrapped the page appearance source(s) with "q"/"Q". But this did not contain any check whether this was even necessary while also not **_guaranteeing_** success or equality of "q"/"Q" counts (it just reduced the risk of wrong insertions, albeit significantly).
* The new code since v1.24.2 ensures equality of "q" and "Q" counts and ensures that the first page appearance command is a "q" (graphics state **_push_**). The old home-grown version of `page.wrap_contents()` has been replaced with this new MuPDF-based logic and is now always invoked for any insertion of page content (drawings, text, images, annotations, ...). No unnecessary data are added to a page's appearance source (file size implications!).

**Comment by JorjMcKie** [comment] 2024-08-22 15:58
BTW I hope you do not use `page.clean_contents()`!

**Comment by dcleres** [comment] 2024-08-23 07:21
> page.clean_contents

Thank you for the warning. No I am not using this.

**Comment by JorjMcKie** [comment] 2024-08-25 09:56
I reviewed the respective again, and I must say that I do currently not see ways to improve performance beyond my recommendations above.

So I am closing this for now.

**Closed by JorjMcKie** 2024-08-25 09:56 UTC
Labels: not a bug
