### ISSUE TITLE
[cannot create /Annot for kind] is still printed despite #2345 is closed.

### ISSUE THREAD

**Issue by outstanding1301** [pymupdf/PyMuPDF#2829] opened 2023-11-22 02:06 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

- cannot create /Annot for kind: 4 is still printed despite #2345  is closed

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

- when `insert_pdf` called.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

- not printing the message.

## Additional context (optional)

---

The `1.22.1` tag applies it.
https://github.com/pymupdf/PyMuPDF/blob/858d0231021f25636a773a39a974d82213df1c04/fitz/utils.py#L1582-L1583

It's currently not applied in the `1.23.6` tag.
https://github.com/pymupdf/PyMuPDF/blob/fb67864f80f6104be7df0bf2d2386b90e7e5af8d/fitz/utils.py#L1599-L1602

So I checked History. and find out somehow v1.22.4 added that message back in.
https://github.com/pymupdf/PyMuPDF/commit/e6ff9462d56c3e711c1db2b9424c8a21d28c1c78#diff-a671948fc39dc42e44da5bcaa2201fbdf4325018b36c9d15056e354b8e5e3f34

BTW, how about using the `logging` library instead of using `print`?

That would allow users to separate the verbose messages from the ones they need based on the log level.

**Comment by julian-smith-artifex-com** [comment] 2023-11-22 11:28
Thanks for this, the problem is now fixed in 60c92e39c09.

[Regarding use of `logging`, i think the consensus here is that it's overly complicated for what we need. We already gather underlying MuPDF error and warning messages into our own store and give access to them. One other point is that we'd rather remove unhelpful messages than provide complicated ways for the user to ignore them.]

**Closed** 2023-11-30 11:42 UTC
