### ISSUE TITLE
Similar to #826 Still not resolved

### ISSUE THREAD

**Issue by sagard21** [pymupdf/PyMuPDF#2565] opened 2023-07-30 07:20 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
An eclipse / oval shape is annotated instead of rectangle. This issue is noticed on Ubuntu 22.04 but not on Mac. The issue is caused when the OCR text is used and its bounding boxes are used for annotation.

However when annotation is done on Mac using same coordinates, the rectangle looks proper.

## To Reproduce (mandatory)
Explain the steps to reproduce the behavior, For example, include a minimal code snippet, example files, etc.
```py
import fitz

doc = fitz.open(filepath)

# Iterate over each page
for page_object in doc.pages():
    # Set the last known text offset
    prev_offset = 0
    # Placeholder to save the text coordinates for entire page
    coordinates = []
    # Placeholder to save the text content
    page = []

    # Get OCR text
    res = page_object.get_textpage_ocr(
        tessdata="/usr/share/tesseract-ocr/4.00/tessdata/", full=True, dpi=300
    )

    # Iterate over every word in the page
    for block in page_object.get_text("dict", textpage=res, sort=False)[
        "blocks"
    ]:
        for line in block["lines"]:
            line_ls = []
            for span in line["spans"]:
                bbox = fitz.Rect(span["bbox"]).irect
                word = span["text"]
                line_ls.append(word)
                start = prev_offset
                end = start + len(word)
                prev_offset = end + 1
                coordinates.append(
                    {
                        "word": word,
                        "start": start,
                        "end": end,
                        "x0": bbox[0],
                        "y0": bbox[1],
                        "x1": bbox[2],
                        "y1": bbox[3],
                    }
                )
            page.append(" ".join(line_ls))

    # Get the entire page text
    text_ocr = "\n".join(page)

# Run NER
ner_predictions = ner_function(text_ocr)

ner_bounding_boxes = bounding_box_identifier(ner_predictions) # Provides list of coordinates [(121, 35, 144, 42), ...]

for b in ner_bounding_boxes:
    # Create a rectangle
    rect = fitz.Rect(b[0], b[1], b[2], b[3])
    # Add annotation to the page
    annot = page_object.add_highlight_annot(rect)
    # Update the color
    annot.set_colors(stroke=color)
    # Update the page for changes to take effect
    annot.update()

doc.save('/path/to/location.pdf')
```

For problems when building or installing PyMuPDF, give the full output of the build/install command so that, for example, all pip/compiler/linker errors/warnings can be seen.

## Expected behavior (optional)
Describe what you expected to happen (if not obvious).

## Screenshots (optional)
<img width="411" alt="image" src="https://github.com/pymupdf/PyMuPDF/assets/19332673/452f1dcf-5bda-4228-ad35-7c6be39d8259">

## Your configuration (mandatory)
 - Operating system, potentially version and bitness (Problem on Ubuntu 22.04)
 - Python version, bitness (3.10)
 - PyMuPDF version, installation method (**wheel** or **generated** from source). (1.22.5)

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
Works on mac

**Comment by JorjMcKie** [comment] 2023-07-30 09:14
Please provide a reproducing page. This is mandatory for bug reports.

**Comment by sagard21** [comment] 2023-07-30 12:23
@JorjMcKie Provided the script I used for generating the highlighted PDF. One more update - Out of 20 PDF files processed, Only 2 had this issue. Rest of the PDF files were proper. This got even more weird now :(

**Comment by JorjMcKie** [comment] 2023-08-01 10:27
Reminder:
Please provide us with a PDF page as described, so we can reproduce the problem.

**Comment by JorjMcKie** [comment] 2023-08-03 21:25
Going to close this because of missing data to reproduce the problem.

**Closed** 2023-08-03 21:38 UTC
Labels: not a bug, example required
