### ISSUE TITLE
getDrawings not extract all border

### ISSUE THREAD

**Issue by bserg66** [pymupdf/PyMuPDF#770] opened 2020-12-15 14:57 UTC
Hello.
I try extract all images and drawings from P48_29-30.pdf and insert its to other P48_29-30_imgall.pdf
But not all borders inserts in P48_29-30_imgall.pdf (around a spoon at first page and 3 borders at second page).
And color of book at first page and view of rectangles around pages numbers do not match the source.

[P48_29-30.pdf](https://github.com/pymupdf/PyMuPDF/files/5696393/P48_29-30.pdf)
[P48_29-30_imgall.pdf](https://github.com/pymupdf/PyMuPDF/files/5696398/P48_29-30_imgall.pdf)

My code  is:
```python
import fitz
import os

PATH = 'C:/PyWorks/PDF_Python/PDF/'

if __name__ == "__main__":
    FileRead = PATH + 'P48_29-30.pdf'
    DocRd = fitz.open(FileRead)
    DocWr = fitz.open()
    PCounts =  DocRd.pageCount
    for PageNumber in range(0,PCounts):
        PageRd = DocRd[PageNumber]
        PageWr = DocWr.newPage(width=PageRd.rect.width, height=PageRd.rect.height)

        # Insert text images 
        TextDict = PageRd.getText("dict")
        for block in TextDict['blocks']:
            if block["type"] == 1:
                PageWr.insertImage(block['bbox'], stream=block['image'])
        
        # Insert drawings 
        paths = PageRd .getDrawings() 
        shape = PageWr.newShape()  
        for path in paths:
            for item in path["items"]: 
                if item[0] == "l":  
                    shape.drawLine(item[1], item[2])
                elif item[0] == "re": 
                    shape.drawRect(item[1])
                elif item[0] == "c":  
                    shape.drawBezier(item[1], item[2], item[3], item[4])
                else:
                    raise ValueError("unhandled drawing", item)
            shape.finish(
                fill=path["fill"],  
                color=path["color"],  
                dashes=path["dashes"],  
                even_odd=path["even_odd"],
                closePath=path["closePath"],  
                lineJoin=path["lineJoin"],  
                lineCap=max(path["lineCap"]),  
                width=path["width"],  
                stroke_opacity=path["opacity"],  
                fill_opacity=path["opacity"] 
                )
        shape.commit()

        # Insert images
        xref = DocRd.getPageImageList(PageNumber, full=True)
        for i, x in enumerate(xref):
            rect = PageRd.getImageBbox(x)
            xref = x[0]
            img = DocRd.extractImage(xref)
            # image = Image.open(io.BytesIO(img['image']))
            # image.show()
            if i == 0:
                PageWr.insertImage(rect, stream=img['image'], overlay=False)
            else:    
                PageWr.insertImage(rect, stream=img['image'])         
        
    # Save to file
    FileExtDel = os.path.splitext(FileRead)[0]
    FileOut = FileExtDel + '_imgall.pdf' 
    DocWr.save(FileOut, deflate=True, garbage=3, clean=True) 
    DocRd.close()
    DocWr.close()```

**Comment by JorjMcKie** [comment] 2020-12-15 15:37
Duplicate of #769

**Closed** 2020-12-16 13:21 UTC
