### ISSUE TITLE
Can't install on raspberry pi 4...

### ISSUE THREAD

**Issue by EliotAmn** [pymupdf/PyMuPDF#1711] opened 2022-05-11 20:56 UTC
Hi ! 
I got this error when I install the PyMuPDF package with `pip3 install PyMuPDF` command...

Any solutions ?

Thanks and sorry for my bad english 

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyMuPDF
  Using cached https://files.pythonhosted.org/packages/9f/1d/032d24e0c774e67742395fda163a172c60e4d0f9875785d5199eb2956d5e/PyMuPDF-1.19.6.tar.gz
Building wheels for collected packages: PyMuPDF
  Running setup.py bdist_wheel for PyMuPDF ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kwzhkap7/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-mp_n7xkw --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-cpython-37
  creating build/lib.linux-armv7l-cpython-37/fitz
  copying fitz/__init__.py -> build/lib.linux-armv7l-cpython-37/fitz
  copying fitz/fitz.py -> build/lib.linux-armv7l-cpython-37/fitz
  copying fitz/utils.py -> build/lib.linux-armv7l-cpython-37/fitz
  copying fitz/__main__.py -> build/lib.linux-armv7l-cpython-37/fitz
  running build_ext
  building 'fitz._fitz' extension
  creating build/temp.linux-armv7l-cpython-37
  creating build/temp.linux-armv7l-cpython-37/fitz
  arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/freetype2 -I/usr/include/python3.7m -c fitz/fitz_wrap.c -o build/temp.linux-armv7l-cpython-37/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2755:10: fatal error: fitz.h: Aucun fichier ou dossier de ce type
   #include <fitz.h>
            ^~~~~~~~
  compilation terminated.
  error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1

  ----------------------------------------
  Failed building wheel for PyMuPDF
  Running setup.py clean for PyMuPDF
Failed to build PyMuPDF
Installing collected packages: PyMuPDF
  Running setup.py install for PyMuPDF ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kwzhkap7/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jsb36swl/install-record.txt --single-version-externally-managed --compile:
    running install
    /usr/local/lib/python3.7/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-cpython-37
    creating build/lib.linux-armv7l-cpython-37/fitz
    copying fitz/__init__.py -> build/lib.linux-armv7l-cpython-37/fitz
    copying fitz/fitz.py -> build/lib.linux-armv7l-cpython-37/fitz
    copying fitz/utils.py -> build/lib.linux-armv7l-cpython-37/fitz
    copying fitz/__main__.py -> build/lib.linux-armv7l-cpython-37/fitz
    running build_ext
    building 'fitz._fitz' extension
    creating build/temp.linux-armv7l-cpython-37
    creating build/temp.linux-armv7l-cpython-37/fitz
    arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/usr/include/freetype2 -I/usr/include/python3.7m -c fitz/fitz_wrap.c -o build/temp.linux-armv7l-cpython-37/fitz/fitz_wrap.o
    fitz/fitz_wrap.c:2755:10: fatal error: fitz.h: Aucun fichier ou dossier de ce type
     #include <fitz.h>
              ^~~~~~~~
    compilation terminated.
    error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-kwzhkap7/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jsb36swl/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-kwzhkap7/PyMuPDF/
```

**Comment by JorjMcKie** [comment] 2022-05-14 09:53
That's not a bug. As documented, your platform is not supported with a wheel. So you must install from sources, which requires you install MuPDF first - which you did not.

**Comment by JorjMcKie** [comment] 2022-06-03 08:07
Please close this issue.

**Closed** 2022-06-14 22:05 UTC
Labels: bug
