### ISSUE TITLE
"clean=True" makes objects invisible in the pdf

### ISSUE THREAD

**Issue by FelixFrog** [pymupdf/PyMuPDF#2635] opened 2023-08-31 12:17 UTC
When joining these two pdf documents everything works well until I save with `clean=True`. If I do, all the text in the page reamins selectable but isn't visible anymore. I tried with different pdf viewers (macOS preview and pdf.js) and the issue is not related to a specific one of them.

Here's the files and the code snippet to reproduce the output:
```python
import fitz
doc = fitz.Document()
for file in ["239.pdf","240.pdf"]:
     page = fitz.Document(file)
     doc.insert_pdf(page)

doc.save("out.pdf")
doc.save("out-clean.pdf", clean=True)
```

I tried joining them with `mutool merge -o out.pdf 239.pdf 240.pdf && mutool clean -g out.pdf out-clean.pdf` and the issue doesn't appear.

My configuration:
 - macOS 11.6.8
 - Python 3.11.3
 - PyMuPDF 1.23.2, wheel

Files:
[out-clean.pdf](https://github.com/pymupdf/PyMuPDF/files/12485958/out-clean.pdf)
[out.pdf](https://github.com/pymupdf/PyMuPDF/files/12485959/out.pdf)
[240.pdf](https://github.com/pymupdf/PyMuPDF/files/12485960/240.pdf)
[239.pdf](https://github.com/pymupdf/PyMuPDF/files/12485961/239.pdf)

**Comment by JorjMcKie** [comment] 2023-08-31 13:21
Thanks for the report. Let me confirm this.
As a first reaction: your mutool invocation with the verb "clean" **_does not clean the PDF_** in the same sense as the `clean=True` parameter in `doc.save()`.
"Mutool clean" just means "rewrite the file". Its CLI parameters `g`, `c`, `s`, etc. then control the details.
To achieve `doc.save(..., clean=True)` you would have to use `mutool clean -s ...` where `s` means "sanitize" and cleans each page in the same way as `page.clean_contents()` does.

**Comment by JorjMcKie** [comment] 2023-08-31 13:38
Confirming:
The problem occurs with file 240.pdf only. It happens in any of the following situations:
1. `doc.save(..., clean=True)`
2. `page.clean_contents()`
3. `mutool clean -cs ...`

This means the issue is located in the base library. I will therefore forward the issue to there.

As an immediate action for you:
Simply do not use `clean=True` when saving. It serves no tangible benefit (even when working) in this situation. Use `doc.ez_save("outfile.pdf")` to achieve all common sense compression.

**Comment by JorjMcKie** [comment] 2023-09-02 22:18
This is the issue number in MuPDF's bug sytem:https://bugs.ghostscript.com/show_bug.cgi?id=707083.

**Comment by JorjMcKie** [comment] 2023-10-05 11:47
The upstream bug has been fixed which will be reflected in the next version.

**Comment by julian-smith-artifex-com** [comment] 2023-10-13 09:30
Fixed in 1.23.5.

**Closed by julian-smith-artifex-com** 2023-10-13 09:30 UTC
Labels: upstream bug

**Comment by masteoo** [comment] 2023-11-19 13:17
@FelixFrog ciao scusa il disturbo ti ho scritto un messaggio circa blinklearning.com su Telegram, grazie

**Comment by zwitterion** [comment] 2024-09-12 20:58
I am running into the same or very similar problem. I have downloaded and built the mupdf tool and can confirm the current version of  mutool does not have this problem but I do see the problem with pymupdf 1.24.10. 

[test.pdf](https://github.com/user-attachments/files/16985311/test.pdf)
Repro steps :
pdf = fitz.open("test.pdf")
fitz.save("clean.pdf", clean=True)

The new file has the original text but it is invisible after saving with clean=True.

PyMuPdf Version  1.24.10

The file was originally created from a scan and had this problem. I have removed and redacted some data. The text was added using Adobe Pro. This does not happen if I create a file from scratch.

**Comment by JorjMcKie** [comment] 2024-09-13 00:05
@zwitterion - While this behavior represents an upstream bug, please be aware that this save option is not beneficial at all.
Its task is to clean and sanitize all contents streams of pages, annotations and Form XObjects in the whole PDF - just the same as if you would execute `page.clean_contents()` for every page.
Except some corner-case situations, this is no longer required in PyMuPDF: previously we  needed this mechanism to ensure correct positioning of insertions on the page - now (since version 1.24.2) this is taken care  of automatically.
So you can safely just not use it - it will not be beneficial for reducing a PDF's file size - maybe in contrast to what its name seems to suggest. Use `doc.ez_save()` and you will achieve the best possible compression.

If you feel however that your situation does require this cleaning please open a new issue. Some of comments above sound as you should indeed do that.
