### ISSUE TITLE
PyMuPDF 1.19.3 Page.get_text() memory leak!!!

### ISSUE THREAD

**Issue by Qsirman** [pymupdf/PyMuPDF#1490] opened 2021-12-25 16:35 UTC
I use latest PyMuPDF(1.19.3) to do parse work of large number of pdf files. But I found that my memory(16GB) will be full and cannot allocate when about 400 files are handled. I did memory analysis and find the anomalous part of my code, the analysis result is in "log.txt" I attached.

[log.txt](https://github.com/pymupdf/PyMuPDF/files/7776034/log.txt)

You can see the page_text = page.get_text() line has memory increment but never release.I found this issue https://github.com/pymupdf/PyMuPDF/issues/362 and downgrade to 1.16.2. Then this problem is magically disappeared. So I think it may be a specific bug for this version.

I am very appreciated for your contribution to this library (this lib is the best I have ever used by the way), but it seems this problem appeared in several version. So I hope you can fix it as soon as possible and once for all.

Thank you again!!!

Have a good day!!!

**Comment by JorjMcKie** [comment] 2021-12-25 17:28
This a duplicate of #1474 which will be fixed in the next version.

**Comment by JorjMcKie** [comment] 2021-12-25 17:30
You shouldn't experience this in v1.19.2 either.

**Comment by JorjMcKie** [comment] 2022-01-01 19:10
Fixed in v1.19.4 currently being uploaded.

**Closed by JorjMcKie** 2022-01-01 19:10 UTC
Labels: bug, duplicate

**Comment by ArrichM** [comment] 2022-02-15 21:16
I am currently running 1.19.5 and experiencing the exact same issue.

**Comment by JorjMcKie** [comment] 2022-02-15 23:21
@ArrichM - please open a new issue with **_all_** mandatory data: code snippet, reproducing document, version infor, OS, installation method.
Thanks.
