### ISSUE TITLE
Fails to parse epubs

### ISSUE THREAD

**Issue by mrx23dot** [pymupdf/PyMuPDF#1800] opened 2022-07-05 22:14 UTC
## Describe the bug (mandatory)
I try to extract text from these epubs, all of them fail.
zipped: https://drive.google.com/file/d/1AtZbc9V7E0IVDDBWw-Eo7DQzQbV9QQA9/view?usp=sharing
But files itself **open correctly** in SumatraPDF reader.
Lib could parse other epubs, just not these.
Seems to me this lib is to strict to the standard or something.

## To Reproduce (mandatory)
```
import fitz
  with fitz.open(fn) as doc:
    for page in doc:
      pass
```
gives 
```
    with fitz.open(fn) as doc:
  File "C:\py38_64\lib\site-packages\fitz\fitz.py", line 4005, in __init__
    _fitz.new_Document(
fitz.fitz.FileDataError: cannot open broken document
```

## Your configuration (mandatory)
win7 x64,
PyMuPDF  from pip3 install -r requirements.txt  PyMuPDF==1.19.6

**Comment by JorjMcKie** [comment] 2022-07-06 08:31
Thank you!

**Comment by JorjMcKie** [comment] 2022-07-06 08:37
BTW: I used MuPDF's own viewer `mupdf-gl.exe` to see what it has to say to these files.
And suspicion confirmed: except for the mobi file, two of the EPUBs where reported to be DRM-protected, the 3rd one opened but only showed garbage.

SumatraPDF is in so far not a reliable counterproof, because it contains code beyond MuPDF to handle extra document types: MOBI, CHM, ...

**Comment by JorjMcKie** [comment] 2022-07-06 09:00
The DRM-related message is obviously wrong in this case - otherwise SumatraPDF couldn't have accessed it.
I also used Calibre to access those files - and they all work. Calibre can also convert between e-book formats (and a few others). After converting MOBI -> EPUB, and EPUB -> MOBI -> EPUB with Calibre, (Py-) MuPDF can process the results.
So indeed: the DRM-message is wrong and may be part of the problem.

Currently, the MuPDF open error message is not directly reported, but accessible in this way:
```python
import fitz
doc=fitz.open("Pandora (Grant Joshua) (z-lib.org).epub")
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    doc=fitz.open("Pandora (Grant Joshua) (z-lib.org).epub")
  File "C:\Users\haral\AppData\Local\Programs\Python\Python310\lib\site-packages\fitz\fitz.py", line 3876, in __init__
    _fitz.Document_swiginit(self, _fitz.new_Document(filename, stream, filetype, rect, width, height, fontsize))
fitz.fitz.FileDataError: cannot open broken document
print(fitz.TOOLS.mupdf_warnings(reset=0))
EPUB is locked by DRM
```
So in case of an exception during open, you want to consider displaying this message yourself.
But I will talk to the other maintainers, if we can do this automatically.

**Comment by JorjMcKie** [comment] 2022-07-06 09:26
As per
> I can't even find the PyMuPDF lib files in C:\Python37\Lib\site-packages
site-packages\PyMuPDF-1.19.6.dist-info

This is because the top level name of PyMuPDF is `fitz`. You will have the installation material here: `...\Lib\site-packages\fitz`. The content is this:
![grafik](https://user-images.githubusercontent.com/8290722/177518148-4b02ab81-fe0f-4d3d-85b2-3c85bf1489db.png)

**Comment by JorjMcKie** [comment] 2022-07-12 09:10
I suggest we mark this as "postponed" and close the issue for now - until a solution is being provided ba MuPDF.

**Closed as completed** 2022-07-12 09:17 UTC
Labels: postpone, upstream bug

**Comment by JorjMcKie** [comment] 2022-07-12 09:19
Thank you, I will.
Also MuPDF will respond to your bug report once they have addressed the issue.
