### ISSUE TITLE
Can not make widget (checkbox) to read-only by adding flags PDF_FIELD_IS_READ_ONLY

### ISSUE THREAD

**Issue by remove158** [pymupdf/PyMuPDF#2278] opened 2023-03-06 18:49 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
Can not make widget in types of (PDF_WIDGET_TYPE_CHECKBOX, PDF_WIDGET_TYPE_RADIOBUTTON) to read-only by adding flags `widget.field_flags |= fitz.PDF_FIELD_IS_READ_ONLY`  
> question is: is that normal behavior? do you have any work-around solution if I want to disable the checkbox or radio?

## To Reproduce (mandatory)
```py
doc = fitz.open(name)
for page in doc:
    widgets = page.widgets()
    for widget in widgets :
        widget.field_flags |= fitz.PDF_FIELD_IS_READ_ONLY
        widget.update()
 ```

## Expected behavior (optional)
I want to make any widgets read-only by adding flags `fitz.PDF_FIELD_IS_READ_ONLY`

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/23172564/223202070-1bd265f6-b58f-47e8-946f-db01f38cd38e.png)

## Your configuration (mandatory)
 - Operating system, potentially version, and bitness window 11 education 22H2
 - Python version, bitness 3.11.2
 - PyMuPDF version, installation method ^1.21.1

**Comment by JorjMcKie** [comment] 2023-03-10 06:04
There is an error in handling the field flags. This technically is a duplicate of #2208 and thus will be fixed in next release.

**Comment by shantanu-d** [comment] 2023-03-27 06:50
Hi @JorjMcKie, 
Is there any planned date for this release?

**Comment by JorjMcKie** [comment] 2023-03-27 06:55
We're waiting for the release of MuPDF-1.22.0. When that's out we'll release PyMuPDF a day or two later. There's no fixed date yet for the MuPDF release, but I'm hoping it'll be in the next 2-3 weeks.
[With all the usual caveats that things can slip etc.]

**Comment by shantanu-d** [comment] 2023-03-27 08:21
> We're waiting for the release of MuPDF-1.22.0. When that's out we'll release PyMuPDF a day or two later. There's no fixed date yet for the MuPDF release, but I'm hoping it'll be in the next 2-3 weeks. [With all the usual caveats that things can slip etc.]

is there any temporary workaround using `xref_set_key` for disabling the checkbox?

**Closed** 2023-04-14 18:12 UTC
Labels: duplicate
