### ISSUE TITLE
Segmentation fault when calling "apply_redactions" method, when trying to redact a specific document. 

### ISSUE THREAD

**Issue by andreasbvillumsen** [pymupdf/PyMuPDF#1869] opened 2022-08-11 08:11 UTC
## Describe the bug (mandatory)
Python crashes when calling "apply_redactions" method, when trying to redact a specific document. 

## To Reproduce (mandatory)
- Open document.
- Loop pages.
- Find sensitive information using regex.
- Add redact annotation
- Apply redactions

Sample file will be sent to your email, as well as code snippet.

## Your configuration (mandatory)
 - macOS Monterey, 12.5, Mac Mini M1
 - 3.8.9, 64 bit ARM
 - PyMuPDF version 1.20.1, wheel

## Additional context (optional)
This issue is related to discussion #1867

**Comment by JorjMcKie** [comment] 2022-08-11 11:08
A duplicate of #1824

**Comment by julian-smith-artifex-com** [comment] 2022-08-13 13:57
This should be fixed in PyMuPDF-1.20.2, released a few hours ago.

**Closed** 2022-08-25 11:50 UTC
Labels: duplicate, upstream bug
