### ISSUE TITLE
pix.color_topusage  raise Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ytcpub** [pymupdf/PyMuPDF#3994] opened 2024-10-28 07:21 UTC
### Description of the bug

[test3.pdf](https://github.com/user-attachments/files/17538685/test3.pdf)

I test diffirent colorspace, and reduce the bbox， it always raise "Segmentation fault", I don't know why

### How to reproduce the bug
```
import fitz
doc = fitz.open('test3.pdf')
page = doc[0]
txt_blocks = [blk for blk in page.get_text('dict')['blocks'] if blk['type']==0]
for blk in txt_blocks:
	pix = page.get_pixmap(clip=fitz.Rect([int(v) for v in blk['bbox']]), colorspace=fitz.csRGB, alpha=False)
	percent, color = pix.color_topusage()
```
### PyMuPDF version

1.24.12

### Operating system

Linux

### Python version

3.12

**Comment by JorjMcKie** [comment] 2024-10-28 10:18
I cannot reproduce your problem: everything works fine under Windows and Linux.
However, there is a known issue (fixed in next version):

The method crashes the interpreter if the clip represents an empty rectangle or leads to an empty pixmap.
Your bizarre way of computing rectangles with integer coordinates may well lead to this condition.
So please for now check this condition yourself.
Why don't you use `IRect` by the way?
```python
import pymupdf

doc = pymupdf.open("test.pdf")
page = doc[0]
txt_blocks = [blk for blk in page.get_text("dict")["blocks"] if blk["type"] == 0]
for blk in txt_blocks:
    clip = pymupdf.Rect([int(v) for v in blk["bbox"]])
    if clip.is_empty:
        print(f"this is empty: {clip=}")
        continue
    pix = page.get_pixmap(
        clip=clip,
        colorspace=pymupdf.csRGB,
        alpha=False,
    )
    print(f"{pix.color_topusage()=}")
```

You do not **_need_** to convert to an integer rectangle - the method can deal with lists of tuples of 4 numbers directly: just pass `blk["bbox"]`.
And instead of creating zillions of pixmaps (one for each text block), you can create **_one pixmap for the whole page_** and then use the clip parameter of `.color_topusage()`.
```python
import pymupdf

print(pymupdf.version)
doc = pymupdf.open("test.pdf")
page = doc[0]
pix = page.get_pixmap()
txt_blocks = [blk for blk in page.get_text("dict")["blocks"] if blk["type"] == 0]
for blk in txt_blocks:
    clip = blk["bbox"]
    print(f"{pix.color_topusage(clip=clip)=}")
```

**Comment by JorjMcKie** [comment] 2024-10-28 10:26
BTW a colleague also tried on a Mac and doesn't see a segv either.

**Comment by ytcpub** [comment] 2024-10-29 02:50
> BTW a colleague also tried on a Mac and doesn't see a segv either.

I am sorry, I upload wrong file,  this is the file
[test3.pdf](https://github.com/user-attachments/files/17550960/test3.pdf)

**Comment by ytcpub** [comment] 2024-10-29 03:08
import fitz
doc = fitz.open("test3.pdf")
page = doc[0]
txt_blocks = [blk for blk in page.get_text("dict")["blocks"] if blk["type"] == 0]
for blk in txt_blocks:
    clip = fitz.Rect([int(v) for v in blk["bbox"]])
    if clip.is_empty:
        print(f"this is empty: {clip=}")
        continue
    pix = page.get_pixmap(
        clip=clip,
        colorspace=fitz.csRGB,
        alpha=False,
    )
	print(clip)
    print(f"{pix.color_topusage()=}")

I see a txt_block bbox that x1 is larger than the page width： Rect(35.0, 636.0, 63.0, 738.0), the page width is page.get_text('dict')['width']   612, but the x1 is 636

**Comment by JorjMcKie** [comment] 2024-10-29 08:42
Ok, now that we have that file, here again my recommendation to use the function with more care until we have immunized it against wrong calls:
```python
import pymupdf

doc = pymupdf.open("test3.pdf")
page = doc[0]

txt_blocks = page.get_text("dict", flags=pymupdf.TEXTFLAGS_TEXT)["blocks"]
for blk in txt_blocks:
    clip = pymupdf.IRect(blk["bbox"]) & page.rect  # only inside visible page!
    if clip.is_empty:  # and never with empty clips!
        print(f"empty: {clip=}")
        continue
    pix = page.get_pixmap(clip=clip)
    pix.color_topusage()
```
Shows this:
```bash
empty: clip=IRect(35, 636, 63, 612)
empty: clip=IRect(523, 618, 536, 612)
empty: clip=IRect(132, 637, 142, 612)
empty: clip=IRect(159, 725, 169, 612)
empty: clip=IRect(167, 693, 177, 612)
empty: clip=IRect(288, 633, 298, 612)
empty: clip=IRect(334, 633, 344, 612)
empty: clip=IRect(395, 612, 405, 612)
empty: clip=IRect(426, 619, 435, 612)
empty: clip=IRect(464, 612, 474, 612)
empty: clip=IRect(502, 612, 512, 612)
empty: clip=IRect(514, 735, 527, 612)
```
> Note: Text written outside the page rectangle is not illegal and sometimes used by PDF creators to store hidden information. So we must make sure that the color count is happening on the visible part of the page only.

**Comment by JorjMcKie** [comment] 2024-10-29 08:45
In the future, please provide us code properly indented in a code block like this:
![image](https://github.com/user-attachments/assets/d61482b7-4235-432a-b812-2eda538ebb33)

**Comment by julian-smith-artifex-com** [comment] 2024-10-29 16:25
Fixed in 1.24.13.

**Closed by julian-smith-artifex-com** 2024-10-29 16:25 UTC
Labels: Fixed in next release

**Comment by ytcpub** [comment] 2024-10-30 03:40
thanks very much! 
another point,  if color_topusage support one input param like n  maybe more usable， maybe want get top 1 or top 2 colors

**Comment by JorjMcKie** [comment] 2024-10-30 07:56
> thanks very much! another point, if color_topusage support one input param like n maybe more usable， maybe want get top 1 or top 2 colors

Take the `pix.color_count` method and build your own evaluator around its output.

**Comment by ytcpub** [comment] 2024-10-30 08:39
> > thanks very much! another point, if color_topusage support one input param like n maybe more usable， maybe want get top 1 or top 2 colors
> 
> Take the `pix.color_count` method and build your own evaluator around its output.

got , very thanks ~~
