### ISSUE TITLE
Unable recognize merged cells in table

### ISSUE THREAD

**Issue by heiseon** [pymupdf/PyMuPDF#3790] opened 2024-08-19 07:19 UTC
### Description of the bug

pymupdf4llm is unable to correctly recognize merged cells when processing files that contain tables, such as in the following document：
<img width="412" alt="image" src="https://github.com/user-attachments/assets/4a9df374-03d8-4cae-9b43-d49d8d535dd3">
the result is：
<img width="751" alt="image" src="https://github.com/user-attachments/assets/e873131c-cd8c-460d-8382-a659a2d9623d">
Additionally, when a table spans across pages in the PDF, it fails to accurately recognize it. 
Am I using the wrong method? Do you have any suggestions for optimization? 
Here is my code:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/28179be2-b661-487e-ac5e-8b23e1282091">

### How to reproduce the bug

1、process files that contain tables with merged cells
2、process files that contain a table spans across pages in the PDF

### PyMuPDF version

1.24.9

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment] 2024-08-19 09:03
This is not a bug but works as intended.

PyMuPDF4LLM uses PyMuPDF's `Table.to_markdown()` method. This function turns all `None` values to empty strings - and strings are required for this output type.

The `Page.find_tables()` in PyMuPDF always returns tables with the maximum values of column and row lengths encountered in any table. Any missing cell rectangles and values (because of merged rows or columns) are represented by respctive `None` items.
Merged cells must be identified by downstream (i.e.: programmer) logic - this is not done by the table finder.

There is not way to recognize table segments that are spread across page boundaries. A failsafe recognition would be extremely complex. Therefore, this is also a programmer's / downstream task.

I understand that this post actually refers to PyMuPDF and not PyMuPDF4LLM.
Please report pymupdf4llm issues in that repository.

**Closed by JorjMcKie** 2024-08-19 09:03 UTC
Labels: not a bug
