### ISSUE TITLE
Not geting colors of a shape

### ISSUE THREAD

**Issue by vgenov-py** [pymupdf/PyMuPDF#1931] opened 2022-09-19 14:13 UTC
Hi!

First of all, I'd like to take the time that this PDF library is by FAR the best that I've ever proven, so THANKS!

I'm having a problem getting the color for what I believe is a shape and painting it:

The code is the following:

`
import fitz
import requests as req
import re
import os

CWD = "./views/trans/to_trans"
exceptions = ("id: ", "explorer", "(g)", "pr")

def go_translate(source: str, target: str, text: str) -> str:
    params = {'sl': source, 'tl': target, 'q': text}
    headers = {"Charset":"UTF-8","User-Agent":"AndroidTranslate/5.3.0.RC02.130475354-53000263 5.1 phone TRANSLATE_OPM5_TEST_1"}
    url = "https://translate.google.com/translate_a/single?client=at&dt=t&dt=ld&dt=qca&dt=rm&dt=bd&dj=1&hl=es-ES&ie=UTF-8&oe=UTF-8&inputm=2&otf=2&iid=1dd3b944-fa62-4b55-b330-74909a99969e"
    res = req.post(url, data=params, headers=headers)
    if res.status_code == 200:
        sentences = res.json().get("sentences")
        if sentences:
            sentences = [(sentence["orig"], sentence["trans"]) for sentence in sentences if sentence.get("trans")]
            return sentences
        return False
    return False
# translations = go_translate("en", "es", "all_text")
def read_pdf(pdf_document: str) -> tuple:
    doc = fitz.open(pdf_document)
    page = doc.load_page(0)
    blocks = page.get_textpage().extractDICT()["blocks"]
    all_text = page.get_textpage().extractText()

    return (doc, blocks, all_text)

def write_pdf(pdf_document: str, new_name: str=None) -> None:
    '''
    report_en:
    '''
    doc, blocks, all_text = read_pdf(pdf_document)
    is_clinic = True if all_text.lower().find("clinica") >= 0 else False
    page = doc.load_page(0)
    translations = go_translate("en", "es", all_text)
    if not translations:
        return {"success": False, "msg": "El PDF no ha podido ser traducido debido a que no se pudo extraer el texto del mismo."}
    '''
    write:
    '''
    new_doc = fitz.open()
    new_page = new_doc.new_page(width=page.rect[2],height=page.rect[3])
    tw = fitz.TextWriter(page.rect)

    '''
    imgs:
    '''
    img_info = page.get_image_info()
    img_info.reverse()
    for img, img_size in zip(page.get_images(), img_info):

        img_code = img[0]
        img_size = fitz.Rect(img_size["bbox"])
        b_img = doc.extract_image(img_code)
        file_img = open(f'{CWD}/{img_code}.{b_img["ext"]}', "wb")
        file_img.write(b_img["image"])
        file_img.close()
        new_page.insert_image(img_size,filename=f'{CWD}/{img_code}.{b_img["ext"]}')
        os.remove(f'{CWD}/{img_code}.{b_img["ext"]}')
    '''
    shapes:
    '''
    shapes = page.get_drawings()
    shapes_c = page.get_cdrawings()
    shapes_svg = page.get_svg_image()
    print(shapes_svg)
    shapes_contest = page.get_contents()
    shape_display = page.get_pixmap()

    for shape in shapes:
        new_shape = new_page.new_shape()
        x= shape["items"][0]
        fill = shape["fill"]
        if x[0] == "l":
            new_shape.draw_line(fitz.Point(x[1]), fitz.Point(x[2]))
            new_shape.finish(
                color=shape["color"], 
                fill=(0.75,1,0.75),
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
        elif x[0] == "re":
            new_shape.draw_rect(x[1])
            new_shape.finish(
                color=(shape["color"]), fill=fill,
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
        elif x[0] == "c":
            new_shape.draw_circle(x[1] - (4.5,0.0),4)
            new_shape.finish(
                color=shape["color"], fill=fill,
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
    '''
    txt:
    '''
    months_en = ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
    months_es = ("enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre")
    for block in blocks:
        lines = block["lines"]
        for line in lines:
            if line["dir"] == (1.0, 0.0):
                for span in line["spans"]:
                    origin = span["origin"]
                    if not is_clinic:
                        pass
                        # Y = origin[1] - 50
                        # origin = (origin[0], Y)
                    text: str = span["text"]
                    if text.lower().find("clinica") >= 0:
                        print("A")
                    # if  text.find("Source:") >= 0:
                    #     print(text)
                    is_date = False
                    month_to_change = None
                    is_number = True if re.fullmatch("\d{2}", text) else False
                    for i, month in enumerate(months_en):
                        month_position = text.find(month)
                        if month_position >= 0:
                            text.replace(month, f"/ {i + 1} /")
                            is_date = True
                            month_to_change = months_es[i]

                    is_allow = True

                    for forbidden in exceptions:
                        if text.lower().find(forbidden) >= 0:
                            is_allow = False
                    try:
                        # check this
                        trans_i = [translation[0].strip().replace("\n","") for translation in translations].index(text.strip())
                        text = translations[trans_i][1] if is_allow else text
                        text = translations[trans_i][0] if is_number else text

                    except ValueError:
                        pass
                        try:
                            if text.find("Source:") >= 0:
                                text = translations[trans_i +1][1] + translations[trans_i +2][1] + translations[trans_i +3][1]

                        except ValueError:
                            pass
                    if is_date:

                        start, end = re.search("\d{2}\ de \w{1,10}\ de \d{4}|\d{2}\ \w{1,10}\ \d{4}", text).span()
                        day = text[start: start + 2]
                        year = text[end -4:end]
                        text = text.replace(text[start:end],f"{day}/{months_es.index(month_to_change) + 1}/{year}")
                    tw.append(origin, text.replace("\n",""), fontsize=span["size"], font=fitz.Font("figbo") if span["font"].lower().find("bold") >= 0 else None)
            else:
                for span in line["spans"]:
                    origin = span["origin"]
                    text = span["text"]
                    try:
                        trans_i = [translation[0].replace("\n","") for translation in translations].index(text)
                        text = translations[trans_i][1].replace("\n", "")
                    except ValueError:
                        pass
                    # dir = span["dir"]
                    tw.appendv(fitz.Point(origin), text, fontsize=span["size"])
    tw.write_text(new_page)
    if new_name:
        pass
        new_doc.ez_save(new_name)
        return {"success": True}

if __name__ == "__main__":
    CWD = "./"
    write_pdf("blue.pdf", "green_traducido.pdf")
`
This is the PDF that I'm working with:
[https://eu.pythonanywhere.com/user/vgenovpy/files/home/vgenovpy/deamadrid/views/trans/to_trans/PEDROANTONIO.pdf](url)

**Comment by JorjMcKie** [comment] 2022-09-19 15:16
Thanks for the compliments - nice words!

But I must say, that I cannot dig through 299 lines of code. Please try to come up with a simple reproducer of the problem itself - no external / internet dependencies other packages, etc.

**Comment by vgenov-py** [comment] 2022-09-19 15:22
I'm sorry

Long story short from a PDF I want to reproduce the next graph:
![image](https://user-images.githubusercontent.com/65721163/191053094-932fa4d7-70a6-414e-bf8f-bfd910cab068.png)

What I'm doing is working fine, until getting the color from this graph, the part that my code does is the following:
```python
for shape in shapes:
        new_shape = new_page.new_shape()
        x= shape["items"][0]
        fill = shape["fill"]
        if x[0] == "l":
            new_shape.draw_line(fitz.Point(x[1]), fitz.Point(x[2]))
            new_shape.finish(
                color=shape["color"], 
                fill=(0.75,1,0.75),
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
        elif x[0] == "re":
            new_shape.draw_rect(x[1])
            new_shape.finish(
                color=(shape["color"]), fill=fill,
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
        elif x[0] == "c":
            new_shape.draw_circle(x[1] - (4.5,0.0),4)
            new_shape.finish(
                color=shape["color"], fill=fill,
                width=shape["width"], fill_opacity=shape["fill_opacity"], even_odd=shape["even_odd"]
            )
            new_shape.commit()
```

Is very odd for me, because sometimes I can get the color just fine (see example below)
![image](https://user-images.githubusercontent.com/65721163/191053516-d4178f4e-a203-4a89-8fe7-401a9eeebff4.png)

but sometimes it doesn't

**Comment by JorjMcKie** [comment] 2022-09-19 15:38
Ah, I see what you mean now.

There is one general comment about the "reproduction power" of drawings with the `Shape` class:

**It is not perfect!**

The original drawings may be arbitrarily complex especially concerning colors. There are many influencers like color on-off-switching via the non-zero-winding and even-odd rules, implications of clipping areas (which I ingore completely during extraction), etc., etc.
Simply hopeless if one doesn't want to write a full-blown PDF interpreter - which I don't believe will happen (although the owner has tha final say).

The drawing (reproduction) capabilities of `Shape` are also limited - a lot can be done with it, but not everything.

So I am afraid I have to turn down this issue with "won't fix" ...

**Comment by JorjMcKie** [comment] 2022-09-19 15:57
> It is not the main concern for me and I can't be more grateful for your library, so I hope not to make you feel wrong!

Thank you very much indeed! I appreciate your acknowledgement.

Since PyMuPDF is now being owned by Artifex itself, the creator of MuPDF, the base library of PyMuPDF, its continued development and maintenance is secured by a highly professional team of experts, and we will see major functional enhancements and extensions in the near future.

**Closed** 2022-09-19 16:34 UTC
