### ISSUE TITLE
Question / Comment: What is the option garbage for

### ISSUE THREAD

**Issue by sant527** [pymupdf/PyMuPDF#655] opened 2020-09-12 21:33 UTC
In this function which is used for joining multiple pdfs what is garbage option for

```
def doc_join(args):
    """Join pages from several PDF documents.
    """
    doc_list = args.input  # a list of input PDFs
    doc = fitz.open()  # output PDF
    for src_item in doc_list:  # process one input PDF
        src_list = src_item.split(",")
        password = src_list[1] if len(src_list) > 1 else None
        src = open_file(src_list[0], password, pdf=True)
        pages = ",".join(src_list[2:])  # get 'pages' specifications
        if pages:  # if anything there, retrieve a list of desired pages
            page_list = get_list(",".join(src_list[2:]), src.pageCount + 1)
        else:  # take all pages
            page_list = range(1, src.pageCount + 1)
        for i in page_list:
            doc.insertPDF(src, from_page=i - 1, to_page=i - 1)  # copy each source page
        src.close()

    doc.save(args.output, garbage=4, deflate=True)
    doc.close()
```

I found garbage=0, the pdf is made very fast

where as with garbase=4 at save() it pauses. It takes time. Can we have some indicator here. whats happening

**Comment by JorjMcKie** [comment] 2020-09-13 00:30
This option controls the effort level to reduce the PDF size. Level 1 and 2 are indeed fast, because more or less only omit objects not referenced by anything in the document. Usually sufficient.
Option 3 looks around for object having different xrefs, but otherwise are equal. If e.g. XREF2 is found to a duplicate of XREF1, then XREF2 is deleted and reference to it is replaced with a reference to XREF1.
Option 4 looks for equality of (usually large) binary objects  - often images, but also fonts and more. Again, duplicates are omitted.
Method ``insertPDF`` technically work like so:
* Look at a to-be-copied source page and recursively determine all source PDF objects referenced by it (again: images, fonts, ...)
* Copy the source page to the target PDF **_together with all referenced objects_**.
* To avoid copying the same objects multiple times, an internal array is maintained, that logs which source object have already been copied, and suppresses repeated copies. So the same image or font will not be copied again.

Sounds good so far, doesn't it. This duplicates omission however is active during **_one_** ``insertPDF`` execution. A potential second one - even from the same source PDF - will know nothing about it.

Also, if the source PDF is poorly optimized (i.e. has object duplicates), that won't be cured during the copy.

Garbage selection is also generally required to get physically rid of deleted objects: every change in a PDF will produce new data, but will not physically remove data that have been replaced. This will only happen with garbage>=1.

If all of this is not your concern, you can use any option. It will not influence the functional behaviour of the PDF. Try different options and look at the file size results to determine if differences are attractive.
Superficially looking at your code snippet, it seems, garbage=3 should be quite ok already.

**Comment by sant527** [comment] 2020-09-14 19:14
I tried garbage=0 then the output file size is very huge. The reason is it embedds font multiple times.

**Comment by JorjMcKie** [comment] 2020-09-15 13:28
> Ideally it should first load all the files trigger the font optimization and then collect the pages and club them

No! That would imply a lot of unwanted things - most importantly an uncontrolled memory consumption.
Apart from the fact that such code would have to be written from scratch - which I certainly will not do.

**Comment by JorjMcKie** [comment] 2020-09-15 13:29
> which I certainly will not do

But you are more than welcome to develop something and contribute it to the repo!

**Comment by JorjMcKie** [comment] 2020-09-16 20:53
The question in the issue title is answered, isn't it?

**Closed** 2020-09-18 16:19 UTC
Labels: question
