### ISSUE TITLE
Not able to preserve font in fields

### ISSUE THREAD

**Issue by gregersn** [pymupdf/PyMuPDF#1184] opened 2021-08-01 09:28 UTC
I am filling out fields in a PDF, that uses a non-standard font for its field, then saving with saveIncr()
PyMuPDF changes what font is used for that field to the default.

Looking at the generated(?) Python code in the installed package, I saw that the function
`_adjust_font` never seem to take into concern the list of fonts that is available in `FormFonts`.

So as a test, I commented out the call to `_adjust_font` in the `update` function, and the fonts in the PDF is preserved.

**Comment by JorjMcKie** [comment] 2021-08-01 09:48
Please let me have minimal reproducing material.

**Comment by gregersn** [comment] 2021-08-01 09:54
Open PDF in Acrobat Reader, e.g. [Character Sheet from Call of Cthulhu](https://www.chaosium.com/content/FreePDFs/CoC/Character%20Sheets/1920s/Character%20Sheet%20-%201920s%20-%20basic%20autocalc%20-%20Call%20of%20Cthulhu%207th%20Ed.pdf)

Fill in field "CON", observe font

```
import sys
import fitz

pdf = fitz.open(sys.argv[1])

for page in pdf:
    for field in page.widgets():
        if field.field_name == 'CON':
            field.field_value = '50'
            field.update()
pdf.saveIncr()

```
Reopen in Acrobat Reader, observe font is different.

**Comment by JorjMcKie** [comment] 2021-08-01 09:57
thanks - will look into it

**Comment by gregersn** [comment] 2021-08-01 09:59
I see that the line here never considers what is in the `FormFonts` list: 
https://github.com/pymupdf/PyMuPDF/blob/d7f55b35c8157ed20924de5d5fe543f34f1c05f5/fitz/helper-fields.i#L948

**Comment by JorjMcKie** [comment] 2021-08-01 10:37
> I see that the line here never considers what is in the FormFonts list: 

Exactly. Just changed that function.
Background: fields created under (Py_) MuPDF yet only support the Base-14 fonts. What I forgot to consider are existing widgets, which may come in with their own fonts - which should simply be accepted.
Theat function now reads:

```python
    def _adjust_font(self):
        """Ensure text_font is correct.

        So it must be either from Document.FormFonts, or (new field) a Base-14 font.
        """
        if not self.text_font:
            self.text_font = "Helv"
            return
        doc = self.parent.parent
        for f in doc.FormFonts + ["Cour", "TiRo", "Helv", "ZaDb"]:
            if self.text_font.lower() == f.lower():
                self.text_font = f
                return
        self.text_font = "Helv"
        return
```

**Comment by gregersn** [comment] 2021-08-01 15:37
This looks to be working (partially) well. But now I get a strange result where the font is correct in fields when I select to edit them. But when I move focus out of them, they get a different font.

**Comment by JorjMcKie** [comment] 2021-08-01 16:18
Yes, there indeed is a different behaviour here between programmatic changes of the field content and changes via user interface (PDF viewer):
For each field (and annotation), there are at least 2 PDF objects defining it. Object 2 is the so-called appearance dictionary `/AP`, which is responsible for the actual visual appearance.
In your case, object 1 of the "CON" field has defined font = "BrittanicBold", but the `/AP` **_has font "Helv"_** defined in its definition - which is the actual weird thing. Therefore, after **_programmtic_** changes, the "50" is shown in Helvetica - as PyMuPDF does not look around for any such inconsistencies. It you place the cursor into it via some PDF viewer however, that is changed to BrittanicBold - whether you enter something in the empty field, or if the field has content.
Saving after changes of PDF viewers, the `/AP` font has been changed to BrittanicBold, too.

**Comment by gregersn** [comment] 2021-08-01 16:34
Is it possible to get access to/change the appearance dictionary from PyMuPDF? 

I tried using `need_appearances()` now, which breaks the possibility to still have it a fillable as a form in acrobat reader. 
Maybe there is no good solution fort this at all?

**Comment by JorjMcKie** [comment] 2021-08-01 16:53
> Saving after changes of PDF viewers, the /AP font has been changed to BrittanicBold, too.

The reason for this is, that PDF UIs (with field update support) completely rebuild the `/AP` which PyMuPDF cannot do today.

**Comment by JorjMcKie** [comment] 2021-08-01 17:23
> Is it possible to get access to/change the appearance dictionary from PyMuPDF?

Technically not too difficult, but risky. **_After_** an UI update,
* The font referenced in object 1 is only by its name, BrittanicBold, which must be one of the FormFonts.
* The font referenced in the `/AP/N` is by a name **_and_** an xref, where the name **_need not be equal_** to "BrittanicBold", but the xref will point to (potentially a version of) "BrittanicBold". The detail behaviour depends on the chosen UI (PDF viewer).

So the only fairly safe time to establish consistency would be a virgin state of the document. Then the following could be done:
1. get font name from object 1
2. look name up in document object AcroForm/DR/Font to extract the font xref
3. look up xref of `/AP/N` within object 1 of field
4. in the `/AP/N` object perform 2 steps:
    * remove "/Resources/Font" (which will remove any inconsistent font there)
    * insert "/Resources/Font/BrittanicBold" with the font xref as value

Code snippet:
```python
cat_xref = doc.pdf_catalog()
form_fonts = doc.xref_get_key(cat_xref, "AcroForm/DR/Font")
>>> cat_xref=doc.pdf_catalog()
>>> form_fonts=doc.xref_get_key(cat_xref, "AcroForm/DR/Font")
>>> form_fonts[1]  # if successful:
'<</BritannicBold 515 0 R/Helv 132 0 R/MinionPro-Regular 133 0 R/MyriadPro-Regular 134 0 R/ZaDb 662 0 R>>'
>>> # extract string "/BritannicBold 515 0 R" from this
>>> # now get the `/AP/N` object xref:
>>> apn = doc.xref_get_key(field.xref, "AP/N")
>>> apn
('xref', '1321 0 R')
>>> doc.xref_set_key(1321, "Resources/Font", "null")
>>> doc.xref_set_key(1321, "Resources/Font/BrittanicBold", "515 0 R")
```
The above worked for your example.

**Comment by gregersn** [comment] 2021-08-02 08:06
I might have misunderstood your answer, or maybe I am demanding too much of  this. But I can't seem to get this to work. I am able to change all the fields with `xref_set_key`. But seems like Acrobat Reader don't agree with the settings. Anyway, it is not really that important. I can fill out the sheet with data, and the calculations still work. Thank you for your help.

**Comment by JorjMcKie** [comment] 2021-08-02 08:11
You are welcome.
Anyway - it was of course hacky.
You bug will be officially resolved in the next version, so thank you for reporting it.

**Comment by JorjMcKie** [comment] 2021-08-08 06:43
New vesion 1.18.16 uploaded to [PyPI](https://pypi.org/project/PyMuPDF/).

**Closed by JorjMcKie** 2021-08-08 06:43 UTC
Labels: bug

**Comment by yunotruong-novobi** [comment] 2022-07-04 09:27
Hi @JorjMcKie, When I update the field_value of a widget and use widget.update() function to update the widget data
This will re-generate a `/AP/N` , but the font was generated is not the font of object 1, I tried to update the source font in the object2, but seem the stream did not update too.

This makes the file generated by doc.save show a font `hev` default for my bock

**Comment by JorjMcKie** [comment] 2022-07-04 09:58
You did not provide reproduction data, but if I understand your situation right, everything behaves as designed:
If you update a field that has a font other than Helvetica (normal) or Times-Roman (normal), that font will be changed to Helvetica (normal).
The reason is that the appearance stream `/AP/N` must be rebuilt upon `.udate()`, so only the MuPDF-supported font can come out.

**Comment by yunotruong-novobi** [comment] 2022-07-04 10:32
yes, I fixed this case by updating the font in `APN` by the object 1 font type and the source font point in the widget's annot
```
cat_xref = template_pdf.pdf_catalog()
form_fonts = template_pdf.xref_get_key(cat_xref, "AcroForm/DR/Font")
form_fonts = form_fonts[1].split("/") if form_fonts[1] else []

for field in fields:
     if field.field_name == key and content:
     field.field_value = content
     field.update()

     if form_fonts:
     font_point = next(filter(lambda font_point: font_point.startswith(field.text_font), form_fonts), None)
     apn = template_pdf.xref_get_key(field.xref, "AP/N")
     apm_ref = apn[1].split()[0]
     template_pdf.xref_set_key(int(apm_ref), "Resources/Font", "null")
     template_pdf.xref_set_key(int(apm_ref), "Resources/Font/%s" % (field.text_font), " ".join(font_point.split()[-3:]))
     apn = field._annot._getAP()
     field._annot._setAP(apn.replace(b"Helv", (field.text_font.encode())))
```
