### ISSUE TITLE
Fitz Pylance İntelliSense( auto suggestions) is not working correctly. (only on fitz) 

### ISSUE THREAD

**Issue by kahvecci** [pymupdf/PyMuPDF#4024] opened 2024-11-05 10:19 UTC
### Description of the bug

When PyMuPDF is running, some methods are not listed on Pylance and return properties are not working properly.

### How to reproduce the bug

```python
import fitz

path = "document.pdf"

doc = fitz.Document(path)

for p in doc.pages():
    text = p.get_text() # Returned but suggestions are not working.
    s_text = text.split("\n") # Working but Pylance doesn't know this is a string.
    print(s_text) # Working
```

https://github.com/user-attachments/assets/3c50b2ea-ce6c-4da0-8c03-3b1fc7c3aa00

### PyMuPDF version

1.24.9

### Operating system

Windows

### Python version

3.11

**Comment by julian-smith-artifex-com** [comment] 2024-11-05 10:50
Duplicate of #2883

**Closed** 2024-11-05 10:51 UTC

**Comment by julian-smith-artifex-com** [comment] 2024-11-05 11:06
@JorjMcKie has just pointed out that Intellisense works better if using `pymupdf` rather than the obsolete `fitz` alias. It's still not perfect, but i'd encourage you to use `pymupdf` rather than `fitz`.

Also, any improvements we make in this area will only apply to `pymupdf`, not `fitz`.
