### ISSUE TITLE
apply_redactions() move pdf text to right after redaction

### ISSUE THREAD

**Issue by Muskan0905** [pymupdf/PyMuPDF#2210] opened 2023-02-03 09:54 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
During the redaction of a pdf document, the text is misplaced from its original position to the right. The redaction annotations are placed correctly but after applying the apply_redactions() function, this issue occurs.

## To Reproduce (mandatory)

- Open document.
- Loop pages.
- Find sensitive information using regex.
- Add redact annotation
- Apply redactions

I will send the sample file via email.

## Your configuration (mandatory)

3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]

 win32

PyMuPDF 1.19.6: Python bindings for the MuPDF 1.19.0 library.
 Version date: 2022-03-03 00:00:01.
Built for Python 3.10 on win32 (64-bit).

**Comment by JorjMcKie** [comment] 2023-02-04 09:30
I have taken a look at your file: there is a bug in `.apply_redactions()` which causes wrong positioning of text that survives redacting.
To get this resolved you must submit an example file to MuPDF's issue site. So your data protection concerns must be addressed in one way or the other. If you can provide a file that can be used as an example, I can help prepare it to make error tracking easier.

**Comment by JorjMcKie** [comment] 2023-02-06 09:41
> You can use this file as a sample [Pages from oid22sid900007513did34803163v8.pdf](https://github.com/pymupdf/PyMuPDF/files/10661476/Pages.from.oid22sid900007513did34803163v8.pdf)

Thank you! I will submit the bug report then and keep you in informed.

**Comment by JorjMcKie** [comment] 2023-02-06 10:54
I think your issue could be a duplicate of #2108 in which case it will definitely be fixed in the next version. I need to confirm this.

**Comment by JorjMcKie** [comment] 2023-02-08 09:42
Confirming: your issue is a duplicate of #2108 and thus will be fixed in next version.

**Comment by Muskan0905** [comment] 2023-02-09 11:36
Thanks for the update!!

**Closed** 2023-04-14 18:19 UTC
Labels: duplicate
