### ISSUE TITLE
What does line['dir'] identify / How to add tilted/rotated text on pdf page

### ISSUE THREAD

**Issue by rafayaar** [pymupdf/PyMuPDF#3947] opened 2024-10-15 10:39 UTC
### Discussed in https://github.com/pymupdf/PyMuPDF/discussions/3946

<div type='discussions-op-text'>

<sup>Originally posted by **rafayaar** October 15, 2024</sup>
Hi @JorjMcKie 

### Point 1
I am extracting a pdf where I have rotated text. I have extracted the text using get_text method. I assume line['dir'] that I am getting is telling about direction/rotation of text. Please confirm how to use it

### Point 2
After extraction, I would want to add that text to some new pdf. And would want to add as according to original pdf. I think Matrix is to be used to implement this. Not sure!

Please help!</div>

**Comment by JorjMcKie** [comment] 2024-10-15 11:06
This is not an issue, but adequately to be posted as a Discussions item - which you did!
So I guess I don't understand why you made two identical posts ...?

Anyway - I have answered your Discussions post and am going to close this issue labelled as "not a bug".

**Closed by JorjMcKie** 2024-10-15 11:06 UTC
Labels: not a bug
