### ISSUE TITLE
Performance issue when opening/reading a document

### ISSUE THREAD

**Issue by mihajlo-metis** [pymupdf/PyMuPDF#3726] opened 2024-07-25 08:45 UTC
### Description of the bug

Hello,

I have this doc:  [en-epc-guidelines-2024-hyperlinked.pdf](https://github.com/user-attachments/files/16373109/en-epc-guidelines-2024-hyperlinked.pdf) and I open/read it like so:

```
if isinstance(file_or_stream, str):
    pages = pymupdf.open(file_or_stream, filetype='pdf')
else:
    pages = pymupdf.open(stream=file_or_stream, filetype='pdf')

text_by_page = []
for page in pages:
    text = page.get_text('text')
```

but at exactly page 635 the processing is slowed way down, 1 sec per page and when it gets to ~900th page, it takes ~4secs to process a page. All the pages in question are pretty standard pages - mostly text.

### How to reproduce the bug

Provided in the description

### PyMuPDF version

1.24.7

### Operating system

MacOS

### Python version

3.11

**Comment by JorjMcKie** [comment] 2024-07-25 14:06
I am afraid there is no way to change anything about this.
It always depends on how complicated / sub-optimal the page appearance has been constructed.
The fact that there is no general problem with text extraction, underpins that this situation is a peculiarity of this specific file.

As you have observed, no problems occur before page 640 thereabouts. It is also clear that the PDF makes use of StructureTree (a super structure containing information about the logical document structure). There is no way of knowing upfront what the PDF creator has done here.

If you need a way out of some actual problem, the following trick may help you. What I am doing here is copying the page to a temporary new PDF and then extract the text from that page copy.
The output of the program is `"maximum time per page: 0.023934299999382347"` on my machine.

Given the involved overhead of creating and deleting a temporary PDF and copying a page into it, this is another demonstration, that the problem is your PDF, not (Py-) MuPDF.


```python
import pymupdf
import time


def speed_text(page):
    doc = pymupdf.open()
    doc.insert_pdf(page.parent, from_page=page.number, to_page=page.number,
                   annots=False, links=False)
    return doc[0].get_text()


times = []
doc = pymupdf.open("en-epc-guidelines-2024-hyperlinked.pdf")
for page in doc:
    t0 = time.perf_counter()
    _ = speed_text(page)
    t1 = time.perf_counter()
    times.append(t1 - t0)

print(f"maximum time per page: {max(times)}")
```

**Comment by JorjMcKie** [comment] 2024-07-26 11:59
Closing this because of no apparent issue encountered with PyMuPDF nor MuPDF.

**Closed by JorjMcKie** 2024-07-26 11:59 UTC
Labels: not a bug
