### ISSUE TITLE
Subsetting fonts in some PDFs messes up horizontal glyph placement

### ISSUE THREAD

**Issue by brechtm** [pymupdf/PyMuPDF#1081] opened 2021-06-07 09:56 UTC
## Describe the bug (mandatory)

Subsetting fonts using `subset_fonts()` in PDFs produced by [rinohtype](https://github.com/brechtm/rinohtype) changes the horizontal placement of individual glyphs. An example PDF with embedded fonts is [google_fonts.pdf](https://raw.githubusercontent.com/brechtm/rinohtype/master/tests_regression/rst/google_fonts.pdf).

## To Reproduce (mandatory)

```
import fitz
d = fitz.open('google_fonts.pdf')
d.subset_fonts()
d.save('gf_subset.pdf', garbage=3, deflate=True)
```

```
$ python subset.py
Subset built for 'Asap-Bold'.
Subset built for 'NotoSerif'.
Subset built for 'NotoSerif-Italic'.
Subset built for 'NotoSerif-Bold'.
Subset built for 'RobotoMono-Regular'.
Subset built for 'RobotoMono-Medium'.

```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/652887/120997050-30e8af00-c787-11eb-826d-94aff773a9bd.png)

## Your configuration (mandatory)

```
3.9.5 (default, May 26 2021, 10:31:42)
[Clang 12.0.0 (clang-1200.0.32.29)]
 darwin

PyMuPDF 1.18.14: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-01 08:11:38.
Built for Python 3.9 on darwin (64-bit).
```

```
Collecting pymupdf
  Downloading PyMuPDF-1.18.14-cp39-cp39-macosx_10_9_x86_64.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 3.6 MB/s
Installing collected packages: pymupdf
Successfully installed pymupdf-1.18.14
```

**Comment by JorjMcKie** [comment] 2021-06-07 10:58
Confirmed.
This error is font-dependent, i.e. it will happen for some fonts only - haven't yet detected any common patterns when this fails. The problem happens because of wrong or missing character width information stored with the subsetted font.

You may have followed the relevant code: I am building font subsets by deleting unused glyphs from the font, but keeping the original glyph id numbers.
What I obviously also need to do is copying over the character width dictionary (`/W`) from the original to the subsetted font.

**Comment by JorjMcKie** [comment] 2021-06-07 17:06
You can download a pre-version fixing this from here: https://github.com/pymupdf/PyMuPDF-wheels/tree/osx

**Comment by JorjMcKie** [comment] 2021-06-07 20:23
This is the PDF subsetted with the mentioned corrections:
[google_fonts_subsetted.pdf](https://github.com/pymupdf/PyMuPDF/files/6611801/google_fonts_subsetted.pdf)

**Comment by brechtm** [comment] 2021-06-09 12:01
Wow! Many thanks for the quick fix.

As a test I've [diffed](https://github.com/brechtm/rinohtype/blob/master/tests_regression/helpers/diffpdf.py) that PDF with the original, and it's indeed identical.

**Comment by JorjMcKie** [comment] 2021-06-09 13:44
As an aside question:
Are you considering to use PyMuPDF as the PDF output vehicle for rinohtype?

**Comment by JorjMcKie** [comment] 2021-06-09 14:04
Here is a script using PyMuPDF to confirm equality of each single character, span, line and block position:
[diff-checker.zip](https://github.com/pymupdf/PyMuPDF/files/6624308/diff-checker.zip)

**Comment by brechtm** [comment] 2021-06-09 15:51
> Are you considering to use PyMuPDF as the PDF output vehicle for rinohtype?

No, sorry. 😄  I want to keep dependencies to a minimum and pure-Python. It's just that rinohtype doesn't support font subsetting (yet), so I was looking for a tool to do this post rendering.

> Here is a script using PyMuPDF to confirm equality of each single character, span, line and block position:
diff-checker.zip

Thanks! That might come in handy in the future.

**Comment by brechtm** [comment] 2021-06-11 15:57
Update: I just noticed that small caps are missing from the subsetted PDF.

**Comment by JorjMcKie** [comment] 2021-06-11 16:05
> small caps are missing from the subsetted PDF

Interesting point! That may be a major gap of mine.
May I ask for another example file?

> Thanks! That might come in handy in the future.

My example was grotesquely complicated. Really sufficient would be just one statement:

``assert doc1[0].get_text("dict") == doc2[0].get_text("dict")``

**Comment by brechtm** [comment] 2021-06-11 20:58
Here's a PDF with some small capitals: [google_fonts.pdf](https://github.com/pymupdf/PyMuPDF/files/6640956/google_fonts.pdf)

**Comment by JorjMcKie** [comment] 2021-06-11 21:53
Thanks for the example ... but it **_does work_** (in this case).
[small-caps-subset.pdf](https://github.com/pymupdf/PyMuPDF/files/6641113/small-caps-subset.pdf)

**Comment by brechtm** [comment] 2021-06-12 06:56
Sorry about that! I was in a rush and didn't check with that particular file (I noticed it in a file that I can't share here). This one does show the issue: [google_fonts.pdf](https://github.com/pymupdf/PyMuPDF/files/6641791/google_fonts.pdf)

One difference between this and the last google_fonts.pdf is that this one has a font with TrueType outlines, where the last had CFF outlines.

**Comment by JorjMcKie** [comment] 2021-06-12 07:29
This one is interesting. As you may have noticed, the heart of the subsetting logic is determining the subset of used unicodes per font. To this end, I am extract all text and store the detected unicodes in a list, which I then hand over to fontTools.

In the current case however, text extraction **_fails_** for the small caps (a base library incapability). When this happens, I am receiving the error unicode 0xfffd for each unrecognized character. In consequence, the subsetted output has nothing to show for the respective character places.

So what I need to do is **_excluding_** the font from subsetting, when encountering error unicodes in text extraction.

**Comment by JorjMcKie** [comment] 2021-06-12 07:41
Interestingly, MuPDF **_does recognize_** the small caps glyphs though. It just does not reflect them as unicodes in text extraction:

```xml
<fill_text colorspace="DeviceRGB" color="0 0 0" transform="1 0 0 -1 85.03937 138.37537">
    <span font="PlayfairDisplay-Regular" wmode="0" bidi="0" trm="10 0 0 10">
        <g unicode="S" glyph="S" x="40.827764" y="-24.15" adv=".54"/>
        <g unicode="�" glyph="m.smcp" x="46.227766" y="-24.15" adv=".851"/>
        <g unicode="�" glyph="a.smcp" x="54.737764" y="-24.15" adv=".616"/>
        <g unicode="�" glyph="l.smcp" x="60.897764" y="-24.15" adv=".573"/>
        <g unicode="�" glyph="l.smcp" x="66.62776" y="-24.15" adv=".573"/>
        <g unicode=" " glyph="space" x="72.357769" y="-24.15" adv=".249"/>
        <g unicode="C" glyph="C" x="75.287769" y="-24.15" adv=".688"/>
        <g unicode="�" glyph="a.smcp" x="82.16776" y="-24.15" adv=".616"/>
        <g unicode="�" glyph="p.smcp" x="88.32777" y="-24.15" adv=".566"/>
        <g unicode="�" glyph="i.smcp" x="93.94777" y="-24.15" adv=".339"/>
        <g unicode="�" glyph="t.smcp" x="97.33777" y="-24.15" adv=".631"/>
        <g unicode="�" glyph="a.smcp" x="102.997768" y="-24.15" adv=".616"/>
        <g unicode="�" glyph="l.smcp" x="109.15777" y="-24.15" adv=".573"/>
        <g unicode="�" glyph="s.smcp" x="114.88777" y="-24.15" adv=".535"/>
    </span>
```
In the above, the glyph names are correctly shown "a.smcp" = "'a' small caps".
So in a future version I might take the above output instead of my text extraction for shaping the input to fontTools.

**Comment by JorjMcKie** [comment] 2021-06-12 08:00
It was a no-brainer change:
[small-caps-subset2.pdf](https://github.com/pymupdf/PyMuPDF/files/6641860/small-caps-subset2.pdf)
The corresponding output log looks like this:
```python
>>> doc=fitz.open("google-fonts-sc2.pdf")
>>> doc.subset_fonts()
Subset built for 'Asap-Bold'.
Cannot subset 'PlayfairDisplay-Regular'.
Subset built for 'PlayfairDisplay-Italic'.
Subset built for 'PlayfairDisplay-Bold'.
Subset built for 'RobotoMono-Regular'.
Subset built for 'RobotoMono-Medium'.
981244
>>> doc.ez_save("small-caps-subset2.pdf")
>>> 
```

**Comment by brechtm** [comment] 2021-06-12 10:28
Hmm, rinohtype could be to blame here. Copying the 'Small Capitals' from both PDFs (TTF and CFF) produces a proper string for the CFF version but gibberish for the TTF version. I haven't looked into how this is specifically handled in the code.

Perhaps it is safer to perform subsetting based on the glyphs, not the unicode character codes. Otherwise, I suspect you may be perhaps dependent on the ToUnicode mapping defined for the font, which could be dependent on the PDF producer. For example both regular and small caps glyphs could be mapped to the same unicode index.

**Comment by JorjMcKie** [comment] 2021-06-12 10:57
I understand. But from a PyMuPDF perspective I am actually pleased to see a case for how to improve it.
As I wrote: the glyph-id **_is detectable_** - just not with the means I am currently using: text extraction.
I need to use / make a MuPDF device, which outputs glyph-ids as well.
For the purpose of subsetting, I need not bother about text position, color, or other crab. Just the font and the set of glyphs used from it.

**Comment by JorjMcKie** [comment] 2021-06-12 11:02
>  analyze a PDF with (true) small capitals

This is another missing feature in PyMuPDF: MuPDF does offer a text output option "use small caps if present in font".
So for me our conversation is important ... 👍

**Comment by JorjMcKie** [comment] 2021-06-12 12:50
I was able to find a solution:
I now hand over glyph ids to fontTools. This addresses your issue:
[small-caps-subset2.pdf](https://github.com/pymupdf/PyMuPDF/files/6642189/small-caps-subset2.pdf)
I am curently building another set of pre-version wheels, so you can download your OSX version soon for more tests if you want.

**Comment by JorjMcKie** [comment] 2021-06-12 13:05
Interesting to see, that with the new approach the subsetted PDF is even smaller for the subset of the "well-behaving" PDF too.
Not sure why this is so ...

**Comment by JorjMcKie** [comment] 2021-06-12 13:12
OSX wheels are available now.

**Comment by JorjMcKie** [comment] 2021-06-12 13:13
good luck!

**Comment by brechtm** [comment] 2021-06-16 13:57
I'm still seeing small caps disappear in a document (that I can't share publicly) featuring the Segoe UI font. It takes some extra effort to create a small test file, so I haven't done that yet.

The wheels I'm using seem to indicate that it's not the latest version you created 4 days ago though:
```
PyMuPDF 1.18.15: Python bindings for the MuPDF 1.18.0 library.
Version date: 2021-06-07 11:05:35.
```

I disabled pip's caching using `--no-cache-dir`, but that didn't help...

**Comment by JorjMcKie** [comment] 2021-06-19 11:37
Don't know if it helps:
Just built support of small caps in PyMuPDF and tried outputting Segoe UI with it on Windows.
Result: None of the Segoe UI fonts on Windows 10 supports / has small caps ...

**Comment by brechtm** [comment] 2021-06-19 20:04
I didn't have time to look into the issue further. I've sent you a PDF with Segoe UI small caps by email. You can use fonttools to dump the font to TTX and search for the _smcp_ feature tag to see that it does include small caps.

**Comment by JorjMcKie** [comment] 2021-06-20 10:31
I have generated new wheels. To test them, download your OSX wheel from [here](https://github.com/pymupdf/PyMuPDF-wheels/tree/osx).
It correctly subsetting the PDF you sent to my e-mail. For a reason unknown to me, subsetting Wingdings Regular does not work. This font is used with only one glyph in your PDF (id 21 = unicode 61490 / 0xF032), which I pass correctly to fontTools subsetter. But this guy outputs a font subset with **_zero glyphs!_** After intercepting this condition, the produced output includes a not subsetted Wingdings, so the file looks good.

**Comment by brechtm** [comment] 2021-06-30 07:47
Forgot to follow up on this... I can confirm that the Segoe UI small caps subsetting now works correctly. The Wingdings glyph is missing, indeed.

**Comment by JorjMcKie** [comment] 2021-06-30 18:30
> "symbol-cmap"

Is a good hint though, thanks! I will try it out - the parameter does exist may - hopefully - lead to success.

**Comment by JorjMcKie** [comment] 2021-07-10 22:10
Fixed in new version finally.

> will try it out - the parameter does exist may - hopefully - lead to success.

btw: still does not work, but the mentioned workaround does.

**Closed by JorjMcKie** 2021-07-10 22:10 UTC
Labels: bug
