### ISSUE TITLE
Can't export subtitle

### ISSUE THREAD

**Issue by mrx23dot** [pymupdf/PyMuPDF#1717] opened 2022-05-18 12:55 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I'm extracting text from attached pdf, mostly works but subtitles won't decode.

## To Reproduce (mandatory)
```
import fitz # install using: pip install PyMuPDF
with fitz.open("my.pdf") as doc:
    text = ""
    for page in doc:
        text += page.get_text()
print(text)
```
![extract](https://user-images.githubusercontent.com/4163396/169043071-32fba613-398c-4f1a-9c61-cf23f1152421.jpg)
![real1](https://user-images.githubusercontent.com/4163396/169043206-4b465aa4-399e-4a9e-8aef-90b303c21505.jpg)
![real2](https://user-images.githubusercontent.com/4163396/169043214-ce22a141-777e-4fe2-888a-eb7f774e8f44.jpg)

[ige.pdf](https://github.com/pymupdf/PyMuPDF/files/8716354/ige.pdf)

## Your configuration (mandatory)
 - Operating system, potentially version and bitness  win10 x64
 - Python version, bitness Python 3.7.0 64bit
 - PyMuPDF version, installation method (**wheel** or **generated** from source).  PyMuPDF-1.19.6-cp37-cp37m-win_amd64.whl  pip

**Comment by JorjMcKie** [comment] 2022-05-25 11:15
Not a bug: This is a problem of the document itself: the font used in these places has no glyph-to-unicode table.
Please close the issue.

**Comment by JorjMcKie** [comment] 2022-05-25 12:02
It is displayed as text: what you see are the results of drawing commands for each character's appearance.
But the font has no provision to back-translate to the originating Unicode.
So yes: only OCR will solve this.

Please close the issue.

**Closed as completed** 2022-05-25 12:19 UTC
Labels: bug

**Comment by zacharysyoung** [comment] 2022-05-25 16:39
@JorjMcKie, I was really curious to see what the outcome of this "issue" was. Can you point to some resources for being able to debug this, or what The Spec has to say about it? Were you able to use PyMuPDF to see what was going on?

**Comment by JorjMcKie** [comment] 2022-05-25 17:39
@zacharysyoung - I am the author of PyMuPDF, so for sure I know how to use it.
In simple words, a font can have (at least) two major components:
1. A set of drawing instructions for (combinations of) unicodes it wants to support. These instructions e.g. represent the unicode `0x44` of the capital "D" by drawing a vertical line "|" folowed by the curve of a left-open semi-circle. Each of these sets of drawings is called a "glyph". So if a program wants to write a "D", it uses the Unicode number to find the corresponding glyph number.
2. An optional mapping glyph number ==> unicode. Sometimes this is not directly needed (e.g. for the Base-14 fonts, or when the encoding is known). Sometimes this is not even desired by the PDF creator (e.g. in order to prevent or impede copy-paste actions).

The font in question of this example does contain the key `/ToUnicode` (glyph ==> unicode mapping), but the object is empty.
This can be easily detected using PyMuPDF:
```python
doc=fitz.open("ige.pdf")
page=doc[0]
print(page.get_text())
฀���������
�����������������
���������������

pprint(page.get_fonts())
[(13,
  'cid',
  'Type0',
  'GYNTBZ+Polo22Halbfett-Identity-H-Identity-H',
  'R13',
  'Identity-H')]

# just one font, xref 13
print(doc.xref_object(13))
<<
  /BaseFont /GYNTBZ+Polo22Halbfett-Identity-H-Identity-H
  /ToUnicode 230 0 R
  /Type /Font
  /Encoding /Identity-H
  /DescendantFonts [ 14 0 R ]
  /Subtype /Type0
>>
# look at the content of xref 230:
print(doc.xref_stream(230).decode())
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CMapType 2 def
/CMapName/R230 def
1 begincodespacerange
<0000><ffff>
endcodespacerange
1 beginbfrange
<0000><0000><0e00>
endbfrange
endcmap
CMapName currentdict /CMap defineresource pop
end end
```
The mapping is empty ...
