### ISSUE TITLE
Size of pdf grows enourmously

### ISSUE THREAD

**Issue by kavin-1098** [pymupdf/PyMuPDF#546] opened 2020-07-02 19:05 UTC
I have requirement of creating a pdf from other pdf with specific pages alone

This is windows 10 . I am using python 3.7 and latest pymupdf version

The source pdf size is 51 MB .The output which i create from it is 700 Mb

cluster_page_numbers is a list which has all the page numbers to be present in the output

for cluster_page_number in cluster_page_numbers:
                    if cluster_page_number <= source_file_handle.pageCount:
                        cluster_file_handle.insertPDF(source_file_handle, from_page=cluster_page_number - 1,
                                                      to_page=cluster_page_number - 1)

Finally save cluster_file_handle

Please assist on this

**Comment by kavin-1098** [comment] 2020-07-02 19:24
More Details

One particular page in the pdf is getting converted into 53 MB which is actually some kbs in size

**Comment by JorjMcKie** [comment] 2020-07-02 22:32
From your description it is not yet quite clear what you want to achieve:
I understood you want to create a sub-PDF with only selected pages from a given one. If this impression is correct, you have at least 3 ways to achieve this:
1. Use ``insertPDF`` to copy over the wanted pages into a new empty PDF (as you did)
2. Simply execute ``doc.select(cluster_page_numbers)`` and then save ``doc`` under a new filename
3. Similar to 2., loop over the reversed (back to front!) page sequence of ``doc`` and delete every page whose number does not occur in ``cluster_page_numbers``.

From a performance and filesize point of view options 2. and 3. are preferrable. The reason is probably evident: nothing is copied over to a new file, the resulting sub-PDF can by no means become any larger. On the contrary: with some luck, images or even fonts exclusively used on some deleted page may be deleted ... these are typically the large objects of a PDF.
In any case make sure to use save options ``garbage=3, deflate=True``.

If you can share the file and your script, I am willing to look at it.

**Comment by kavin-1098** [comment] 2020-07-03 17:30
[1.pdf](https://github.com/pymupdf/PyMuPDF/files/4870832/1.pdf)
If I try to create a new pdf from the attached pdf using insertPDF() . The resulting pdf size bubbles to 50 MB though the source pdf is 17 KB

**Comment by kavin-1098** [comment] 2020-07-03 17:44
Below is the script used

source_file_handle = fitz.open(path)
cluster_file_handle = fitz.open()
cluster_file_handle.insertPDF(source_file_handle, from_page=0,
to_page=0)
cluster_file_handle.save('1.pdf')

**Comment by JorjMcKie** [comment] 2020-07-03 17:50
A short command log:
```python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import os, fitz
>>> old = fitz.open("1.pdf")
>>> os.stat("1.pdf").st_size
16535
>>> new1 = fitz.open()
>>> new1.insertPDF(old)
>>> new1.save("2.pdf")
>>> os.stat("2.pdf").st_size
13427
>>> new2=fitz.open()
>>> new2.insertPDF(old, from_page=0, to_page=0)
>>> new2.save("3.pdf")
>>> os.stat("3.pdf").st_size
13427
>>> 
```
So I really wonder what is going on at your site ...

**Comment by kavin-1098** [comment] 2020-07-04 08:51
Hey @JorjMcKie , Even I am getting the same result in my system ,apologies for the confusion

 The attachment "1.pdf" is one of the page of the big PDF which I cant share .

If I try to split this one page alone from big PDF using insertPDF()  ,The resulting PDF size is 50 MB 

Code - 

import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=148,
                                  to_page=148)
    cluster_file_handle.save(os.path.join('Big_bursted.pdf'))
    print(os.stat('Big_bursted.pdf').st_size)

OUTPUT - 54603418 ie > 53 MB

NOTE: If i cut that page alone from PDF and test, the size of the resulting pdf looks good like you have shared

**Comment by JorjMcKie** [comment] 2020-07-04 09:24
Hard to track down problems without supporting data ... So I just can guess and suggest a few things.

The ``insertPDF`` method copies the page object **_as they are_** - recursively stepping down to all objects referenced in the page's object definition. This includes any references to objects **inherited** from parent definitions. This may e.g. apply to the page's ``/Resurces`` object: such an object may exist in some parent object and in turn may contain references to large images and what not.
``insertPDF`` does not check if all of these references are actually needed and will include them "just in case".
To shave off unneeded / unreferenced objects, by all means do use ``garbage=3, deflate=True`` when you save ``cluster_file_handle``.
If I understand you right, then file ``1.pdf`` represents page 148 of ``source_file_handle``? If so, how did you manage creating it with a size of just 16 MB?

**Comment by kavin-1098** [comment] 2020-07-04 09:37
Yes that's correct, file 1.pdf represents page 148 of source_file_handle

**Comment by kavin-1098** [comment] 2020-07-04 09:38
I splited it using adobe acrobat pro software

**Comment by kavin-1098** [comment] 2020-07-04 09:41
I had tried garbage=3, deflate=True while saving 

import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=148,
                                  to_page=148)
    cluster_file_handle.save(os.path.join('Big_bursted.pdf'),garbage=3, deflate=True)
    print(os.stat('Big_bursted.pdf').st_size)

OUTPUT - 54506614 ie > 53 MB

Issue still exists

Could you please suggest any other approach to get rid of this

**Comment by JorjMcKie** [comment] 2020-07-04 09:52
please ``print(cluster_file_handle.xrefObject(cluster_file_handle[0]))`` to show the object definition of the page in the resulting PDF, and the same of the original page's definition in `source_file_handle`.
And I hope you share the file of `source_file_handle`.

**Comment by JorjMcKie** [comment] 2020-07-04 10:04
sorry: I meant cluster_file_handle[0].**xref**, the page's xref.

**Comment by kavin-1098** [comment] 2020-07-04 10:12
import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=148,
                                  to_page=148)
    cluster_file_handle.save(os.path.join('Big_bursted.pdf'),garbage=3, deflate=True)
    print("Source File XREF "+str(source_file_handle[0].xref))
    print("OUTPUT File XREF "+str(cluster_file_handle[0].xref))

Output:

Source File XREF 1
OUTPUT File XREF 3921

**Comment by JorjMcKie** [comment] 2020-07-04 10:18
No, misunderstanding, this one:

```python
page148 = source_file_handle[148]
print(source_file_handle.xrefObject(page148.xref)) # page definition in source file

page0 = cluster_file_handle[0]
print(cluster_file_handle.xrefObject(page0.xref)) # page definition in target file
```
And also the file `Big_bursted.pdf` please.

**Comment by kavin-1098** [comment] 2020-07-04 10:24
import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=148,
                                  to_page=148)
    page148 = source_file_handle[148]
    print(source_file_handle.xrefObject(page148.xref)) # page definition in source file

    page0 = cluster_file_handle[0]
    print(cluster_file_handle.xrefObject(page0.xref))

Output

<<
  /Annots 886 0 R
  /Contents 907 0 R
  /CropBox [ 0 0 612 1008 ]
  /MediaBox [ 0 0 612 1008 ]
  /Resources 916 0 R
  /Rotate 0
  /Type /Page
  /Parent 735 0 R
>>
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 12 0 R
  /MediaBox [ 0 0 612 1008 ]
  /CropBox [ 0 0 612 1008 ]
  /Rotate 0
  /Annots [ 50 0 R 58 0 R 59 0 R 64 0 R 69 0 R 70 0 R 71 0 R ]
  /Parent 2 0 R
>>

**Comment by kavin-1098** [comment] 2020-07-04 10:27
Source File xref
<<
  /Annots 886 0 R
  /Contents 907 0 R
  /CropBox [ 0 0 612 1008 ]
  /MediaBox [ 0 0 612 1008 ]
  /Resources 916 0 R
  /Rotate 0
  /Type /Page
  /Parent 735 0 R
>>

Output file xref
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 12 0 R
  /MediaBox [ 0 0 612 1008 ]
  /CropBox [ 0 0 612 1008 ]
  /Rotate 0
  /Annots [ 50 0 R 58 0 R 59 0 R 64 0 R 69 0 R 70 0 R 71 0 R ]
  /Parent 2 0 R
>>

**Comment by JorjMcKie** [comment] 2020-07-04 10:38
Well, this cannot be the page in `1.pdf`:

```python
>>> print(doc.xrefObject(page.xref))
<<
  /Annots 6 0 R # different number of annotations, see below!
  /Contents 11 0 R
  /CropBox [ 0 0 612 792 ]  # different page size! Height=792 not 1008
  /MediaBox [ 0 0 612 792 ]  # different page size!
  /Parent 3 0 R
  /Resources 7 0 R
  /Rotate 0
  /Type /Page
>>
>>> print(doc.xrefObject(6)) # different number of annotations:
[ 9 0 R 10 0 R ] # only 2 annotations, not 7!
>>> 
```

**Comment by kavin-1098** [comment] 2020-07-04 10:45
Oh!!

I didn't share xref of 1.pdf

**Comment by kavin-1098** [comment] 2020-07-04 10:45
I can share it also

**Comment by JorjMcKie** [comment] 2020-07-04 10:48
> I didn't share xref of 1.pdf

never mind - had no problem finding it out with PyMuPDF. What I showed you in previous post **_was_** the xref of the page in `1.pdf`.

I also now need
```python
print(source_file_handle.xrefObject(916)) # the old page resources object
print(cluster_file_handle.xrefObject(12)) # the new page resources object
cont148 = page148.readContents()decode()
print(cont148) # the old page painting commands
cont0 = pgae0.readContents().decode()
print(cont0) # the new page painting commands

**Comment by kavin-1098** [comment] 2020-07-04 10:48
import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=332,
                                  to_page=332)
    page332 = source_file_handle[148]
    print(source_file_handle.xrefObject(page332.xref)) # page definition in source file

    page0 = cluster_file_handle[0]
    print(cluster_file_handle.xrefObject(page0.xref))

Output

<<
  /Annots 886 0 R
  /Contents 907 0 R
  /CropBox [ 0 0 612 1008 ]
  /MediaBox [ 0 0 612 1008 ]
  /Resources 916 0 R
  /Rotate 0
  /Type /Page
  /Parent 735 0 R
>>
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 4 0 R
  /MediaBox [ 0 0 612 792 ]
  /CropBox [ 0 0 612 792 ]
  /Rotate 0
  /Annots [ 9 0 R 13 0 R ]
  /Parent 2 0 R
>>

**Comment by kavin-1098** [comment] 2020-07-04 10:49
Page number 332 is the 1.pdf

**Comment by JorjMcKie** [comment] 2020-07-04 10:50
> Page number 332 is the 1.pdf

NO! you still do ``page332 = source_file_handle[148]``!

**Comment by kavin-1098** [comment] 2020-07-04 10:53
my bad!!

**Comment by kavin-1098** [comment] 2020-07-04 10:55
import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=332,
                                  to_page=332)
    page332 = source_file_handle[332]
    print(source_file_handle.xrefObject(page332.xref)) # page definition in source file

    page0 = cluster_file_handle[0]
    print(cluster_file_handle.xrefObject(page0.xref))

Output

<<
  /Annots 2457 0 R
  /Contents 2461 0 R
  /CropBox [ 0 0 612 792 ]
  /MediaBox [ 0 0 612 792 ]
  /Resources 2462 0 R
  /Rotate 0
  /Type /Page
  /Parent 2448 0 R
>>
<<
  /Type /Page
  /Contents 3 0 R
  /Resources 4 0 R
  /MediaBox [ 0 0 612 792 ]
  /CropBox [ 0 0 612 792 ]
  /Rotate 0
  /Annots [ 9 0 R 13 0 R ]
  /Parent 2 0 R
>>

**Comment by kavin-1098** [comment] 2020-07-04 11:04
> import fitz
> import os
> if **name** == '**main**':
> source_file_handle = fitz.open('C:\Big_bursted_blobs.pdf')
> cluster_file_handle = fitz.open()
> cluster_file_handle.insertPDF(source_file_handle, from_page=332,
> to_page=332)
> page332 = source_file_handle[148]
> print(source_file_handle.xrefObject(page332.xref)) # page definition in source file
> 
> ```
> page0 = cluster_file_handle[0]
> print(cluster_file_handle.xrefObject(page0.xref))
> ```
> 
> Output
> 
> <<
> /Annots 886 0 R
> /Contents 907 0 R
> /CropBox [ 0 0 612 1008 ]
> /MediaBox [ 0 0 612 1008 ]
> /Resources 916 0 R
> /Rotate 0
> /Type /Page
> /Parent 735 0 R
> 
> > >
> 
> <<
> /Type /Page
> /Contents 3 0 R
> /Resources 4 0 R
> /MediaBox [ 0 0 612 792 ]
> /CropBox [ 0 0 612 792 ]
> /Rotate 0
> /Annots [ 9 0 R 13 0 R ]
> /Parent 2 0 R
> 
> > >

Code
import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=332,
                                  to_page=332)
    page332 = source_file_handle[332]
    # print(source_file_handle.xrefObject(page332.xref)) # page definition in source file

    page0 = cluster_file_handle[0]
    # print(cluster_file_handle.xrefObject(page0.xref))
    print(source_file_handle.xrefObject(916)) # the old page resources object
    print(cluster_file_handle.xrefObject(12)) # the new page resources object
    cont148 = page332.readContents().decode()
    print(cont148) # the old page painting commands
    cont0 = page0.readContents().decode()
    print(cont0) # the new page painting commands

Output

<<
  /ColorSpace <<
    /Cs6 851 0 R
    /Cs8 917 0 R
  >>
  /ExtGState <<
    /GS1 853 0 R
  >>
  /Font <<
    /TT1 920 0 R
    /TT10 926 0 R
    /TT3 932 0 R
    /TT5 934 0 R
    /TT6 936 0 R
    /TT8 942 0 R
    /TT9 944 0 R
  >>
  /ProcSet [ /PDF /Text /ImageC /ImageI ]
  /XObject <<
    /Im1 950 0 R
  >>
>>
[ 9 0 R 13 0 R ]
/GS1 gs
BT
/TT2 1 Tf
36 0 0 36 154.26 686.22 Tm
0 g
0 Tc
.0001 Tw
(Flood Cert )Tj
ET

/GS1 gs
BT
/TT2 1 Tf
36 0 0 36 154.26 686.22 Tm
0 g
0 Tc
.0001 Tw
(Flood Cert )Tj
ET

**Comment by JorjMcKie** [comment] 2020-07-04 11:18
Ok, the picture is getting clearer:
As you can see, there are several fonts (TT1, TT10, TT3, TT5, TT6, TT8, TT9) and one image (Im1) named in the target page definition. However, the page uses only 1 font and no image!
So please try this to clean up the mess:

```python
cluster_file_handle.insertPDF(source_file_handle, from_page=332, to_page=332)
newpage = cluster_file_handle[-1] # the page just inserted
newpage.cleanContents() # synchronize page definition and page painting instructions
cluster_file_handle.save(...)
```

**Comment by JorjMcKie** [comment] 2020-07-04 11:27
And again: if you are looking for an efficient way to remove a list of pages from a PDF and then save it under a new name, then the following should be a lot less troublesome:

```python
pagelist = [...] # list of pages to remove from the PDF
for page in reversed(source_file_handle):  # iterate back to front!
    if page.number not in pagelist:  # keep this page
        continue
    source_file_handle.deletePage(page.number)

source_file_handle.save("Big_bursted.pdf", garbage=4, deflate=True) # save under the new name
# original file will remain untouched!
```
This ensures that the file will not become any bigger at least, and (probably) smaller instead.
It is **_important_** to iterate back to front, because after each page delete, the numbers of subsequent pages will change.

**Comment by JorjMcKie** [comment] 2020-07-04 11:31
A similar script may be used to create a PDF with **only the deleted** pages. Use it if our discussion does not lead to a satisfying result.

**Comment by kavin-1098** [comment] 2020-07-04 11:37
> Ok, the picture is getting clearer:
> As you can see, there are several fonts (TT1, TT10, TT3, TT5, TT6, TT8, TT9) and one image (Im1) named in the target page definition. However, the page uses only 1 font and no image!
> So please try this to clean up the mess:
> 
> ```python
> cluster_file_handle.insertPDF(source_file_handle, from_page=332, to_page=332)
> newpage = cluster_file_handle[-1] # the page just inserted
> newpage.cleanContents() # synchronize page definition and page painting instructions
> cluster_file_handle.save(...)
> ```

import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\Big_bursted_blobs.pdf')
    cluster_file_handle = fitz.open()
    cluster_file_handle.insertPDF(source_file_handle, from_page=332,
                                  to_page=332)
    newpage = cluster_file_handle[-1] # the page just inserted
    newpage.cleanContents() # synchronize page definition and page painting instructions
    cluster_file_handle.save('1.pdf')

Still the size is same

**Comment by kavin-1098** [comment] 2020-07-04 11:43
> And again: if you are looking for an efficient way to remove a list of pages from a PDF and then save it under a new name, then the following should be a lot less troublesome:
> 
> ```python
> pagelist = [...] # list of pages to remove from the PDF
> for page in reversed(source_file_handle):  # iterate back to front!
>     if page.number not in pagelist:  # keep this page
>         continue
>     source_file_handle.deletePage(page.number)
> 
> source_file_handle.save("Big_bursted.pdf", garbage=4, deflate=True) # save under the new name
> # original file will remain untouched!
> ```
> 
> This ensures that the file will not become any bigger at least, and (probably) smaller instead.
> It is **_important_** to iterate back to front, because after each page delete, the numbers of subsequent pages will change.

This approach is fine if only one pdf to be created from the given one

My requirement is to create multiple pdfs from given PDF so is the source pdf is deleted once i cant create multiple output pdfs

**Comment by kavin-1098** [comment] 2020-07-04 11:44
> A similar script may be used to create a PDF with **only the deleted** pages. Use it if our discussion does not lead to a satisfying result.

Can you share that script also

**Comment by JorjMcKie** [comment] 2020-07-04 11:54
Well, you just have to change what you want to keep:

```python
pagelist = [...] # list of pages to remove from the PDF
for page in reversed(source_file_handle):  # iterate back to front!
    if page.number in pagelist:  # keep the pages in pagelist
        continue
    source_file_handle.deletePage(page.number)  # delete all others

source_file_handle.save(...)
# original file will remain untouched!
```

I would have loved to understand the reason for this unusal behaviour. It almost certainly is caused by the source PDF.
But your restriction is forcing me to fly blind ...

**Comment by JorjMcKie** [comment] 2020-07-04 12:06
If you need both files (the one without the deleted pages **and** a new one with **only** the deleted pages), then just execute those two snippets one after the other ... **but** close and re-open the source file in between!

```python
# snippet 1
...
source_file_handle.close()
source_file_handle = fitz.open(source_file_handle.name)
# snippet 2
```

Again the question: can you please share the 53 MB one-page PDF? Maybe this also gives me a clue.

**Comment by kavin-1098** [comment] 2020-07-04 12:10
Sure I can share that

My only concern with this approach is opening and closing the source pdf many times and it would consume lot of memory

**Comment by kavin-1098** [comment] 2020-07-04 12:12
Seems github has restriction to share only upto 10 mb

can i have your mail id so that i can mail you

**Comment by JorjMcKie** [comment] 2020-07-04 12:12
> My only concern with this approach is opening and closing the source pdf many times and it would consume lot of memory.

Why that? I thought you have one list of pages to be removed? If that is so, then the source file will only be opend twice.

**Comment by JorjMcKie** [comment] 2020-07-04 12:13
sure: it is listed in the repo: jorj.x.mckie@outlook.de

**Comment by JorjMcKie** [comment] 2020-07-04 12:22
You can also do this:
Open the same source file **two times** as different fitz ``Documents``.

```python
pagelist = ... # list of pages to remove

doc1 = fitz.open("source.pdf")
doc2 = fitz.open("source.pdf")  # same file, but different document!

for page in reversed(doc1):
    if page.number in pagelist:
        doc1.deletePage(page.number)
    else:
        doc2.deletePage(page.number)
doc1.save("without-pagelist.pdf")
doc2.save("pagelist.pdf")
```
This will simultaneously create 2 PDFs with sources pages separated from each other.

**Comment by kavin-1098** [comment] 2020-07-04 12:23
It is not limited to opening two times

**Comment by JorjMcKie** [comment] 2020-07-04 12:25
Then why not apply my recipe from previous post? Same file, 2 different documents.

**Comment by JorjMcKie** [comment] 2020-07-04 12:27
If it helps, I can also sign some non-disclosure agreement and have a look at that obscure PDF.

**Comment by kavin-1098** [comment] 2020-07-04 12:31
That's what I am refering to 

I mean I will have many lists with which i need to create many output pdfs

So i would need to open the source that many times which may consume the container memory and make the container to restart frequently

Right now I am doing doc2 = fitz.open("source.pdf") once and insertPDF() many times

As per your approach I will use delete() many times as well as fitz.open("source.pdf") which may inrease memory consumption

**Comment by kavin-1098** [comment] 2020-07-04 12:32
> If it helps, I can also sign some non-disclosure agreement and have a look at that obscure PDF.

I am mailing you . Thanks for your patience

**Comment by JorjMcKie** [comment] 2020-07-04 12:36
Ok, now I understand.

**Comment by JorjMcKie** [comment] 2020-07-04 12:49
> Right now I am doing doc2 = fitz.open("source.pdf") once and insertPDF() many times

How about not doing `insertPDF()` immediately, but instead storing the respective page numbers in a list. Then, towards the end of all processing, excute those deletions using the accumulated page number list.

**Comment by JorjMcKie** [comment] 2020-07-05 00:20
I have massaged the code behind ``page.cleanContens()`` to become more effective. If you want I can send you a wheel for your Windows version to try if the following code snippet (we had it before) is more successful:

```python
cluster_file_handle.insertPDF(source_file_handle, from_page=332, to_page=332)
newpage = cluster_file_handle[-1] # the page just inserted
newpage.cleanContents() # synchronize page definition and page painting instructions
```

**Comment by JorjMcKie** [comment] 2020-07-05 00:36
Let me just give it a try:
[PyMuPDF-1.17.3-cp37-cp37m-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/4874228/PyMuPDF-1.17.3-cp37-cp37m-win_amd64.zip)
Rename the extension from "zip" to "whl" and execute `python -m pip install -U PyMuPDF-1.17.3-cp37-cp37m-win_amd64.whl`.

**Comment by kavin-1098** [comment] 2020-07-06 14:14
I have python 3.8.1 64 bit in my windows 10 64 bit system

ERROR: PyMuPDF-1.17.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

I am getting the above error when trying to install the whl file you provided

**Comment by JorjMcKie** [comment] 2020-07-06 14:26
Oh, I looked at your initial post and saw Python 3.7.
I will upload another wheel then in a few minutes.

Jorj

Von: kavin-1098<mailto:notifications@github.com>
Gesendet: Montag, 6. Juli 2020 10:15
An: pymupdf/PyMuPDF<mailto:PyMuPDF@noreply.github.com>
Cc: Jorj X. McKie<mailto:jorj.x.mckie@outlook.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [pymupdf/PyMuPDF] Size of pdf grows enourmously (#546)


I have python 3.8.1 64 bit in my windows 10 64 bit system

ERROR: PyMuPDF-1.17.3-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

I am getting the above error when trying to install the whl file you provided

**Comment by JorjMcKie** [comment] 2020-07-06 14:28
[PyMuPDF-1.17.3-cp38-cp38-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/4879525/PyMuPDF-1.17.3-cp38-cp38-win_amd64.zip)

**Comment by kavin-1098** [comment] 2020-07-06 15:06
Thanks for the super fast response

**Comment by kavin-1098** [comment] 2020-07-06 15:10
Ran with new whl file still the size bubbles for certain pages in the doc

import fitz
import os
if __name__ == '__main__':
    source_file_handle = fitz.open('C:\source.pdf')
    for i in range(466):
        cluster_file_handle = fitz.open()
        cluster_file_handle.insertPDF(source_file_handle, from_page=i,
                                      to_page=i)
        j = i+1
        newpage = cluster_file_handle[-1] # the page just inserted
        newpage.cleanContents() # synchronize page definition and page painting instructions
        cluster_file_handle.save(str(j)+'.pdf',garbage=4,deflate=True)
        cluster_file_handle.close()

**Comment by JorjMcKie** [comment] 2020-07-06 15:16
Well, that's all I can think of, given the circumstances of this blind flight.
Please send me one of the bloated page PDFs so I can see what keeps them so big ...
You should still have my e-mail address.

**Comment by kavin-1098** [comment] 2020-07-06 15:27
yup i will

**Comment by kavin-1098** [comment] 2020-07-07 22:29
Hey @JorjMcKie  

I have observed that insertPDF() method is extremely faster in execution than delete() and other methods

Is there any way to achieve the same performance of insertPDF() method using delete() or deletePageRange() or move() or copy()

**Comment by JorjMcKie** [comment] 2020-07-08 03:20
What happened to the filesize problem? I haven't seen an example page yet ...

As per the ``deletePage`` performance:
The delete itself is actually very fast. What I am also doing however is:
1. Remove all links of  all remaining pages that point to the deleted page
2. Look at the table of contents and remove items pointing to the deleted page. Any such "blind" entry then leads to rebuilding the complete table of contents

The efforts of these two actions is almost the same for one as for many pages, therefore one should always try to use `deletePageRange`.

**Comment by kavin-1098** [comment] 2020-07-08 12:48
The issue creating pages have many fillable forms in them . Will that be a clue for you to find out the root cause

**Comment by kavin-1098** [comment] 2020-07-08 13:07
For example :-

http://myndm.com/wp-content/uploads/Acknowledgement%20of%20Intent%20to%20Proceed.pdf

http://myndm.com/wp-content/uploads/Acknowledgement%20of%20Intent%20to%20Proceed.pdf

**Comment by JorjMcKie** [comment] 2020-07-08 15:48
> The issue creating pages have many fillable forms in them . Will that be a clue for you to find out the root cause

Not really, cannot think of anything why that might be.
By the way, those files are not very big: under 1 MB and also seem identical ...

**Comment by JorjMcKie** [comment] 2020-07-08 17:18
Looked at the one-page file:
Its size of 913 KB can be reduced to 484 KB by `doc.save(fname, garbage=4, deflate=True)`.
The option garbage=4 causes identical **_binary_** be found and replaced by just one copy. In this case, the Arial font with **_780 KB_** uncompressed, **_450 KB_** compressed size was there two times. The remaining stream object sizes are minor.
**_But now comes the interesting fact:_**
This font is exlusively used by one or two FreeText annotations, the widgets (form fields) only use "Helvetica" (a built in font which needs no extra space at all).
I have marked the annotation rectangles red and the widgets rects blue. So the text within red box accounts for 450 KB (compressed!) file size of a total of 484 KB - **_after_** garbage collection.
If the annotation creator would have chosen Helvetica instead of Arial (those fonts are **very** similar), the filesize could have been as small as ca. 35 KB.
But as I mentioned before, ``insertPDF`` has no choice but copying all resources required by the page(s) along with the pages, so 450KB Arial will be copied to the that poor one page PDF, just to show the two words "signature" and "name" ...
One can suppress annotations when using ``insertPDF``, but that would of course change the page's appearance. Using `garbage=4` should be used in any case.


![grafik](https://user-images.githubusercontent.com/8290722/86948697-8487ee00-c11b-11ea-9365-9453dd34160e.png)

**Comment by JorjMcKie** [comment] 2020-07-08 17:24
This is how the page would look like if using
```python
>>> doc.insertPDF(src, from_page=xxx, to_page=xxx, annots=False)
>>> doc.save("out.pdf", garbage=4, deflate=True)
```
![grafik](https://user-images.githubusercontent.com/8290722/86950439-2e687a00-c11e-11ea-8306-f125b1146d8a.png)

The filesize is now **_22 KB_**.

**Comment by JorjMcKie** [comment] 2020-07-08 18:31
I think we are at a point where we can say it's not a bug of PyMuPDF.
The reason for everything is buried in the input files.

**Comment by kavin-1098** [comment] 2020-07-08 22:51
Thanks for the clarity @JorjMcKie 

Will using deletepageRange will remove the annotations or will it retain those annotations

**Comment by kavin-1098** [comment] 2020-07-08 23:05
Can you tell how you are getting the size of annotations and widgets in a
page

**Comment by JorjMcKie** [comment] 2020-07-09 00:33
> Will using deletepageRange will remove the annotations or will it retain those annotations

This method will only remove the page(s) and the **_links_** on other pages pointing to one of the removed pages.

> Can you tell how you are getting the size of annotations and widgets in a page

Annotations and widgets have a `rect` property - as simple as that.
With rect you can use `page.drawRect(rect)` or `shape.drawRect(rect)`. The difference between them being, that `Shape` is like a canvas which accepts an arbitrary number of draw commands and lets you assign common properties to the drawn objects. I used it like so:
```python
shape=page.newShape()
for annot in page.annots():
    rect = annot.rect
    shape.drawRect(rect)
shape.finish(color=(1,0,0))  # make all annot rects red bordered
for widget in page.widgets():
    rect = widget.rect
    shape.drawRect(rect)
shape.finish(color(0,0,1))  # make all field rects blue bordered
shape.commit()  # write all draw commands to the page /Contents
doc.save(...)
```

**Comment by JorjMcKie** [comment] 2020-07-09 15:55
> Will using deletepageRange will remove the annotations or will it retain those annotations

Sorry, didn't see this.
Annotations like links and form fields are associated with their page. Deleting the page will also remove them.
This does not automatically mean that resources used by those objects will also be gone: e.g. a font might be in use by several annotations on different pages and will therefore only be deleted if nothing references it anymore.

**Comment by kavin-1098** [comment] 2020-07-12 15:05
190_pymupdf.pdf
<https://drive.google.com/file/d/1YNEci8n-cQUk2zoZiiEwGtk2KuQK9yP-/view?usp=drivesdk>

  190_pypdf.pdf
<https://drive.google.com/file/d/1T-X_MU5DvO01ta-J1T1gJKXeaOPV956c/view?usp=drivesdk>

**Comment by kavin-1098** [comment] 2020-07-12 15:12
Hi @JorjMcKie 

I have attached two pdfs above

190_pymupdf is created using insertPDF() in pymupdf and 190_pypdf is created using pypdf2

The size of 190_pymupdf is 53 mb where as the size of the other pdf is 17 kb

I think this would give you more clarity on this issue

**Comment by kavin-1098** [comment] 2020-07-12 16:39
You will have the access now

**Comment by JorjMcKie** [comment] 2020-07-12 17:04
Thanks, got it. Amazing difference indeed.
Finally found the problem:
When I copy the source page, I am also copying its annotations, if this wasn't excluded via ``annots=False``. But each annot contains a pointer back to its parent page - and I do not update **_this_** to point to the new page!
So - because of the recursivity of the copy process - the old source page, its parents and what not are also copied 😡😡😡!

I am re-labelling this issue back to bug now.
Thanks for being so persistent - it is an important finding!

**Comment by JorjMcKie** [comment] 2020-07-12 17:06
You can confirm what I posted, if you try `insertPDF`  with ``annots=False``.

**Comment by kavin-1098** [comment] 2020-07-12 17:10
Oh that is great !!

I have tried annots=false but I will certainly loose many important content
if I do so

It is great that you had identified the bug , when can I expect a fix for
this?

Also is there any alternative approach in pymupdf to prevent this from
happening temporarily?

**Comment by JorjMcKie** [comment] 2020-07-12 17:57
The fix was easy - I already have a version which produces the correct result.
You have Windows and Py 3.8 64bit right?
I can attach a wheel here like before ...

**Comment by JorjMcKie** [comment] 2020-07-12 17:58
> Also is there any alternative approach in pymupdf to prevent this from happening temporarily?

After the fix, it should no longer happen actually - or did I misunderstand?

**Comment by kavin-1098** [comment] 2020-07-12 18:00
> > Also is there any alternative approach in pymupdf to prevent this from happening temporarily?
> 
> After the fix, it should no longer happen actually - or did I misunderstand?

I thought it would take time

**Comment by kavin-1098** [comment] 2020-07-12 18:01
> The fix was easy - I already have a version which produces the correct result.
> You have Windows and Py 3.8 64bit right?
> I can attach a wheel here like before ...

Thanks please share it here

**Comment by JorjMcKie** [comment] 2020-07-12 18:04
[PyMuPDF-1.17.4-cp38-cp38-win_amd64.zip](https://github.com/pymupdf/PyMuPDF/files/4909061/PyMuPDF-1.17.4-cp38-cp38-win_amd64.zip)

Good luck!

**Comment by kavin-1098** [comment] 2020-07-12 19:04
Thanks

Can you provide the wheel for linux os also

I will be parallely testing both

**Comment by JorjMcKie** [comment] 2020-07-12 22:34
Linux is being generated via Travis.
Pls look for **_v1.17.4_** in [this](https://github.com/pymupdf/PyMuPDF-wheels/tree/linux) branch in 15 minutes or so.

**Comment by JorjMcKie** [comment] 2020-07-12 22:35
When you save the new file filled via `insertPDF`, do not forget to use `garbage=4`!

**Comment by kavin-1098** [comment] 2020-07-13 08:25
The fix works for this page 

It is failing for many other pages which i have

**Comment by kavin-1098** [comment] 2020-07-13 08:25
Can you give it is a more generalised fix

**Comment by JorjMcKie** [comment] 2020-07-13 08:58
not without more data to reproduce

**Comment by JorjMcKie** [comment] 2020-07-13 09:03
This is becoming a highly iterative excercise. Can you not just give the problem file or some file that reproduces the problem?
I swear I keep it confidential!

**Comment by JorjMcKie** [comment] 2020-07-18 12:11
Closing this for now.
Please do not hesitate to re-open or submit a new issue, once you can provide me reasonable test data for error reproduction.

**Closed by JorjMcKie** 2020-07-18 12:11 UTC
Labels: bug

**Comment by pachhaipurna** [comment] 2023-10-27 07:17
> And again: if you are looking for an efficient way to remove a list of pages from a PDF and then save it under a new name, then the following should be a lot less troublesome:
> 
> ```python
> pagelist = [...] # list of pages to remove from the PDF
> for page in reversed(source_file_handle):  # iterate back to front!
>     if page.number not in pagelist:  # keep this page
>         continue
>     source_file_handle.deletePage(page.number)
> 
> source_file_handle.save("Big_bursted.pdf", garbage=4, deflate=True) # save under the new name
> # original file will remain untouched!
> ```
> 
> This ensures that the file will not become any bigger at least, and (probably) smaller instead. It is **_important_** to iterate back to front, because after each page delete, the numbers of subsequent pages will change.

@JorjMcKie I used this logic to delete few pages, but the file size is not decreasing. I need annotation of pages except deleted pages. Any idea on this, If I use garbage =4 the program will be so slow, It needs huge time to save even a single pdf page.
