### ISSUE TITLE
Looking for font supporting Nepali

### ISSUE THREAD

**Issue by arjunpaudyal** [pymupdf/PyMuPDF#398] opened 2019-11-10 02:58 UTC
`a = "बाह्यसम्पर्कतन्तु, आर्थिककेन्द्रत्वेन वर्तते"        # sanskrit  `
`aa = u"बाह्यसम्पर्कतन्तु, आर्थिककेन्द्रत्वेन वर्तते"        # sanskrit  `
`ab = "बाह्यसम्पर्कतन्तु, आर्थिककेन्द्रत्वेन वर्तते".encode('utf8')        # sanskrit  `
`b = "normal ascii"                      # normal ascii`
`c = "sòmé lâtîn!"                       # latin-1 `
`e = "Euro sign €"                       # ascii and 1 unicode char`
`f = "测试"                               # Chinese`
`g = "Фёдор Михайлович Достоевский"      # Russian`

`import fitz`
`doc = fitz.open()`
`doc.insertPage(-1)      # insert first page with default settings`
`p = doc.loadPage(-1)`

`x0,y0 = 30, 50`
`fsize = 6`

`p.insertText(fitz.Point(x0, y0+10), a, fontsize = fsize)  # tried aa, ab, does not work`

`p.insertText(fitz.Point(x0, y0+20), b, fontsize = fsize)`
`p.insertText(fitz.Point(x0, y0+30), c, fontsize = fsize)  # this is the only thing that works`

`p.insertText(fitz.Point(x0, y0+50), e, fontsize = fsize)`
`p.insertText(fitz.Point(x0, y0+60), f, fontsize = fsize)`
`p.insertText(fitz.Point(x0, y0+70), g, fontsize = fsize)`

`m = {"author": b, "producer": c, "subject": e, "title": a, "creator": g,
     "keywords": a} # Code from documentation example, works on Metadata and TOC, No Issues`

`doc.setMetadata(m)`

`toc = [[1, a, 1],`
`       [1, b, 1],`
`       [1, c, 1],`
`       [1, e, 1],`
`       [1, f, 1],`
`       [1, g, 1],`
`      ]`

`doc.setToC(toc)`

`doc.save("TTTT.pdf")`

 I expected the variables a,b,c, e,f,g to be transferred to page. They re not transferred.  Your piece of code to set metadata, and set TOC works as expected.

Please help me.

My os is windows 10, Python 3.6, Pymupdf 1.16

**Comment by arjunpaudyal** [comment] 2019-11-10 02:59
[TTTT.pdf](https://github.com/pymupdf/PyMuPDF/files/3828012/TTTT.pdf)
This is the output of above code. I ex

**Comment by JorjMcKie** [comment] 2019-11-10 09:14
In ``page.insertText(...)`` and ``page.insertTextbox(...)`` use a font which supports the characters used in the text. The Base14 fonts ("Helvetica", "Times-Roman", "Courier") only support character codes less than 256.
On Windows you probably have installed a lot of fonts for other character sets like for Chinese, Japanese, Korean or Sanskrit. You must find out yourself which one you need.

Here is an example snippet which puts some text in Hindi in a PDF:

[devanagari-text.zip](https://github.com/pymupdf/PyMuPDF/files/3828255/devanagari-text.zip)

**Comment by arjunpaudyal** [comment] 2019-11-10 18:22
![PDFRender](https://user-images.githubusercontent.com/4165417/68548553-547d2500-03ab-11ea-8e0a-148c777aac61.png)
Thank you JorjMcKie.

It solved some of the problems, while it faced new challenges. Text is not properly rendered in the generated PDF. In attached image, I want the Expected line as is  in PDF, not the second line. 

Sadly, when I copy the text generated in PDF (your attachment) to some other text editor with capabilities of UTF-8 encoding (windows notepad, and Notepad++), it works as expected. I generated the text back from PDF with added code `text = doc.getPageText(0) # doc: our document with unicode devnagari insertion`, python IDLE prints the text in expected manner.

Thank you.

**Comment by JorjMcKie** [comment] 2019-11-10 18:40
Please post the script you are working with here.

**Comment by JorjMcKie** [comment] 2019-11-10 19:45
The fact, that ``page.getText()`` correctly prints the original text, shows that it is correctly coded in the PDF.
But the translation to the glyphs (graphical appearance of each character) is incorrect. So we are still using the wrong font. The font is responsible for exactly doing this: translating the character code (``chr(char)``) to some graphical representation, called the "glyph".
Same thing happens if you insert "Hello, world!" using the ``ZapfDingBats`` font for example.

**Comment by arjunpaudyal** [comment] 2019-11-10 20:51
[SampleWithFonts.zip](https://github.com/pymupdf/PyMuPDF/files/3828999/SampleWithFonts.zip)

I tested with multiple fonts that (do not)/have Devnagari block. Despite issues in page rendering, Unicode Text in TOC works fine as expected. Same as metadata. Attached file is nearly 2 MB as it includes all the fonts.
    
    import fitz
    
    fontfiles = [
        ("Devnagari", "./includes/DEVAB_.TTF", 150, 100),       # No Unicode Devnagari block
        ("Mangal", "./includes/mangal.ttf", 150, 130),          # Yes
        ("Sanskrit", "./includes/Sanskr.ttf", 150, 160),        # yes
        ("Utsaah", "./includes/utsaah.ttf", 150, 190),          # Yes
        ("Himalaya", "./includes/himalaya.ttf", 150, 220),      # No Devnagari block
        ("Aparajita", "./includes/aparaj.ttf", 150, 250),       # Yes
        ]
    
    doc = fitz.open()  # new PDF
    fsize = 10  # fontsize
    
    engText = "Thank you JoriMcKie for free knowledge."
    nepText = "नि:शुल्क ज्ञानको लागी JoriMcKie लाई धन्यबाद |"
    
    page = doc.newPage()
    
    page.insertText(fitz.Point(150, 70), engText) # use base 14 default point
    
    for finfo in fontfiles:
        fname, ffile, x0, y0 = finfo   # 
        fsize = 10                     # define font size 
        point = fitz.Point(x0,y0)      # define insertion point
    
        # insert the font on the page
        page.insertFont(fontname=fname, fontfile=ffile)
        # TODO: Test: if the atcual font name, or coder-specified name makes difference
        
    
        # insert Font Name:
        page.insertText(fitz.Point(60, y0), fname)
    
        # inset unicode text
        page.insertText(point, nepText, fontname=fname,fontsize=fsize )
        
    # insert actual image in pdf for comparison
    rect = fitz.Rect(150, y0+30, 50+363, y0+30+49) # I know the dimension of image
    pix = fitz.Pixmap("./includes/Expected.png")
    page.insertImage(rect, pixmap=pix, overlay=True)
    
    # Rendering in Page Failed, try with page Title
    m = {"title": nepText,}
    doc.setMetadata(m) # renders good
    
    # Try to set in Page TOC:
    TOC = [[1, nepText, 1]]
    doc.setToC(TOC)
    
    """
    Problem:
        page.insertText did not work as expected. Rendering is not proper.
    
    Contrary:
        setMetadata and InserToC work fine as expected.
    
    FunFact:
        Copied text from im-properly rendered text, is rendered properly in :
            IDLE display,
            Text Editors,
            Chrome Browser
    
    TODO:
        Check on Raspbian
    """
    
    
    
    doc.save(__file__ + ".pdf", garbage=3, deflate=True)

**Comment by JorjMcKie** [comment] 2019-11-10 21:18
The rendering of metadata and TOC entries works, because of the PDF-internal mechanism.
So no surprise there.
I am hesitating to download the big PDF: did you find **any** font at all which works satisfactorially?

**Comment by arjunpaudyal** [comment] 2019-11-13 00:12
@JorjMcKie 
I have tested couple of tests to figure out where is the problem. I did not succeed but it might be helpful to narrow down the scope of problem. Mostly it is Windows based.

Test Text = नि:शुल्क ज्ञानको लागी JoriMcKie लाई धन्यबाद |
1. Print to PDF from Notepad using Microsoft Print to PDF.)
2. Use LibreOffice Writer to generate PDF (Export to PDF)

In both cases, it worked fine. Font embedded. (Microsoft PDF - embedded **CID+F1 Font**, while LibreOffice embedded the actual font  - Aparajita, Mangal or so on.

I can confirm that - it is not the Font issue.

**Encoding**:
PDF generated from PyMuPDF is encoded as **Identity-H.**  I

I need to test something related to Encoding.

**Comment by JorjMcKie** [comment] 2019-11-13 11:03
Ah okay, I see. Microsoft also uses ``Identity-H``, while Libre doesn't, as you write.
It is an issue with (Py-) MuPDF's font **_handling / support_** then.
As I wrote: it cannot be a unicode support problem, because you can extract the original text in its correct, original form.

I am afraid I am out of advice here now. Especially because not all glyphs are wrong - just some, right? What I am doing in PyMuPDF is converting a unicode character to a 2 or 4 byte hexadecimal string. Which integer to take for this conversion depends on the font characteristics which I get from MuPDF. So I suspect the issue is inside MuPDF ☹.

**Comment by JorjMcKie** [comment] 2019-11-13 14:45
When comparing the PDF output of LibreOffice, Word and PyMuPDF, I can see, that the office software kind of know when to combine two or more characters in a row into **one new joint glyph**. If you look at the ``/ToUnicode`` object for the fonts there, you will find things like (Libre example):

```
16 beginbfchar
<01> <0928093F>  % 2 unicodes form one glyph, addressed as 0x01
<03> <0936>
<04> <0941>
<05> <0932094D0915>  % 3 unicodes form one glyph, addressed as 0x05
<06> <091C094D091E>  % 3 unicodes form one glyph, addressed as 0x06
<07> <093E>
<08> <0915>
<09> <094B>
<0A> <0932>
<0B> <0917>
<0C> <0940>
<0D> <0908>
<0E> <0927>
<0F> <0928094D092F>  % 3 unicodes form one glyph, addressed as 0x0F
<10> <092C>
<11> <0926>
endbfchar
```
Doing this kind of thing requires knowledge of the underlying language of course.
In contrast, PyMuPDF translates each single character of a text string separately to a glyph ... and will consequently fail to produce the right appearance.
As I said: I have currently no idea how to address this issue, and it may well be that there will never be a solution I am afraid.

**Comment by JorjMcKie** [comment] 2019-11-14 07:14
A take-away from our discussion is that I should more closely look at PyMuPDF's handling of text insertion. You have put your finger on a weakness there.

In the meantime, I have found that the base library MuPDF does support this type of thing - how much is something to find out.
Also found confirmed that improvements are only possible by offering a way to specify the **_language_** of a text - the font alone is not sufficient as we have seen with your examples.

Thank you for bringing this up!

**Comment by arjunpaudyal** [comment] 2019-11-14 15:12
@JorjMcKie Is it somehow related to the default encoding set (encoding=0) in the text insertion ?
from FAQ: (https://pymupdf.readthedocs.io/en/latest/faq/)

The valid encoding values are TEXT_ENCODING_LATIN (0), TEXT_ENCODING_GREEK (1), and TEXT_ENCODING_CYRILLIC (2, Russian) with Latin being the default. Encoding can be specified by all relevant font and text insertion methods.

I wanted to test it by setting it to Devnagari, or remove the default encoding. I do not know how-to for both of the concerns.

(PS: I figured - encoding = 4, 5, or even 6 - that are not available, work without producing error, but no change in PDF file).

**Comment by JorjMcKie** [comment] 2019-11-15 19:47
> The valid encoding values are ...

These flags only play a role for the 3 Base14 PDF fonts Times-Romas, Courier and Helvetica ... to create variants for other than Latin encodings.
In every other case they are ignored.

**Comment by JorjMcKie** [comment] 2019-11-19 13:50
Sorry - didn't mean to close this!

**Comment by arjunpaudyal** [comment] 2019-11-19 14:00
How does (Py-)MuPDF handle Ligatures in font ? I was looking for it in MuPDF documentation, that talks about the extraction-handling only.

Core-problem here, as i figured out is the ligatures defined in font are not handled well, so the letters as shown as typed.

**Comment by JorjMcKie** [comment] 2019-11-19 14:34
>  was looking for it in MuPDF documentation, that talks about the extraction-handling only.

This is the only place where there is some support.

I know that you are still looking for a way to solve your issue. But **_ligatures_** is not it and "choosing the **_right font_**" is not it either - in contrast to my earlier opinion. And it's definitely not any issue in the area **_lack of unicode support_**.

No:
Some software piece becoming active in the translation chain ``unicode characters -> ... -> displayed glyphs`` has to know and react to the fact "the language in use is Nepali". Only if something in that chain reacts like "if uncode **_a_** is followed by unicode **_b_**, **_and_** the language is Nepali, then produce glyph **_g_** and continue with the unicode following **_b_**", we will see the desired result.

This does not happen now, because I did not implement a way to enter and pass on language information in PyMuPDF. MuPDF does accept language codes, and I hope the result would improve once I find a way to pass on language codes. And I honestly have no hope to solve this in any other way.

Unfortunately this is not trivial, because I will have to change all of the current font handling internally and with respect to the programmer API ... a major effort.

**Comment by PushpaYa** [comment] 2019-12-10 07:39
Hi ,
I am looking for hindi pdf data extraction with bbox details.I am not able to get right example .I am attaching PDF .
[hindi.pdf](https://github.com/pymupdf/PyMuPDF/files/3943545/hindi.pdf)

**Comment by JorjMcKie** [comment] 2019-12-10 11:13
@PushpaYa  - what have you tried so far?
I just wrote this snippet:

```python
>>> import fitz
>>> doc=fitz.open("hindi.pdf")
>>> outtext = open("hindi.txt", "wb")
>>> from operator import itemgetter  # for sorting
>>> for page in doc:
	blocks=page.getText("blocks")  # read textblocks with position info
	blocks.sort(key=itemgetter(1))  # sort them by ascening y coordinate
	for b in blocks:  # now iterate through the block items
            if b[-2] == 1:
                continue  # ignore image blocks
	    outtext.write(b[4].encode())  # this contains the text lines of one blocks
	outtext.write(bytes((12,)))  # write a formfeed at end of page
>>> outtext.close()
```
Depending on the complexity of your page layout, you may need to write more sophisticated sorting - e.g. also by horizontal coordinates. Or you may need to adapt to a two column page layout, etc.
For all of this there are ``getText(opt)`` options helping you.
Please read the relevant docu chapters.

**Comment by PushpaYa** [comment] 2019-12-11 11:16
Thanks for the reply.
I had already tried some thing like above ,I am reading blocks and putting it into csv.
But my problem is not reading data ,it is language !
is there a way where hindi font is read as hindi by Pymupdf?
I am attaching csv file for pdf I had attached earlier.

Thanks,
Pushpa


"""get block data into csv"""    
        
def get_block_data(fname):
    pagenum =0
    doc = fitz.open(fname)
    block_data = pd.DataFrame(columns=['x0', 'y0', 'x1', 'y1', "lines in blocks", 'block_type', 'block_no',"no_token"])
    for page in doc:
        blocks = page.getTextBlocks()
        sb = sorted(blocks, key=itemgetter(1, 0))
        pagenum=pagenum+1
        for i,b in enumerate(sb):      
        # Pass the row elements as key value pairs to append() function 
            block_data = block_data.append({'x0' : b[0]  , 'y0' : b[1],'x1' : b[2]  , 'y1' : b[3],'lines in blocks' :str
[hindi.pdf_.zip](https://github.com/pymupdf/PyMuPDF/files/3950031/hindi.pdf_.zip)

(b[4] ), 'block_type' : b[6],'block_no':b[5],"no_token":len(b[4].split()),"pageno":pagenum} , ignore_index=True)
    base=os.path.basename(fname)
    file=os.path.splitext(base)[0]
    block_data.to_csv(temp_file_path+file+"_block"+".csv")
    return (temp_file_path+file+"_block"+".csv")

**Comment by JorjMcKie** [comment] 2019-12-11 13:02
> But my problem is not reading data ,it is language !
is there a way where hindi font is read as hindi by Pymupdf?

I guess I do not understand. All PyMuPDF can do is returning the text (data) and - when choosing the "dict" option - the name of the font used by that text. It cannot determine the language used.

Use packages which can find out (actually always only by **_guessing_**) languages from text data.

**Comment by JorjMcKie** [comment] 2019-12-16 07:46
@PushpaYa - still waiting for your reaction.
I have looked into the files of your zip: when opening them with an editor, they do look like hindi letters (which I am unable to read).
So it seems the text extraction works correctly as it should.

> Use packages which can find out (actually always only by *guessing*) languages from text data.

Concerning this previous comment of mine, have a look at #409 where I mentioned half a dozen of packages which can detect languages for a given character string.

**Comment by arjunpaudyal** [comment] 2020-03-08 05:41
Holding the issue for a while -  due to lack of understanding - where the problem is, exactly - mupdf, pymyupdf, OS, font, or unicode handling.

**Comment by JorjMcKie** [comment] 2020-03-08 09:44
After some research I think MuPDF probably supports language-aware text output.

I would have to rewrite major parts of PyMuPDF text output to make use of this however.
Once this has achieved, a new text output function in PyMuPDF would need a font **_and_** a language code.

I currently cannot say when I will be able to implement this ...

**Comment by PushpaYa** [comment] 2020-03-11 13:27
Thanks for the reply ,will look into it  #409
<https://github.com/pymupdf/PyMuPDF/issues/409>.

**Comment by JorjMcKie** [comment] 2020-04-04 19:34
@PushpaYa - I am currently testing a new text insertion function, which uses the respective MuPDF functions more directly.
Most notably it will support an optional ``language`` parameter. When given, it should conform to the ISO 639 standard, sub-standards 1, 2, 3 or 5.
I have tried your example strings from above with it, and - most regrettably - it does not seem to solve the problem 😞.
Will keep you posted.

**Comment by JorjMcKie** [comment] 2020-07-02 13:02
@PushpaYa - I want to give your problem one more try.
Another user has just figured out a way to patch the font CMAP (character translation map) in a PDF font, #530 
So I was thinking about a potential way to solve your issue:
We were talking about unicode -> glyph translations, which are not properly handled. From my memory it seems to be a specific combination of 2 (or morer?) unicode characters, which need to be **commonly** translated to one glyph, right?

Do you have  a list of cases of unicode pairs or triples, which need to be translated into certain glyphs?
Once I have these I may be able to modify the CMAP of the font to correctly make those translations ...

**Comment by PushpaYa** [comment] 2020-07-03 05:21
Thanks @JorjMcKie ,I will try and update you soon.

**Comment by PushpaYa** [comment] 2020-07-08 14:35
Hi ,

unicode to Krutidev translation is needed for Hindi langauge

https://docs.microsoft.com/en-us/typography/script-development/devanagari

Thanks,
Pushpa

**Comment by JorjMcKie** [comment] 2020-07-20 15:41
Thanks for the information. I have read over it a few times, and what I finally understood is this (and maybe I am still wrong ...):

* Writing Devanagari text to a PDF is not trivial as is character-by-character. On the contrary, there exist complex rules, which determine when and how single glyphs have to be reordered in the presence of so-called "half-forms".
* Someone / something must take over the task to (1) analyze the incoming text, and (2) put out a new sequence of glyphs, which is being built based on the previous rule.

This seems to be what the **_Indic shaping engine_** on the provided MS web site does.
I know of no such engine which I could use. Apart from the fact that I am not at all certain about the point in time to call such engine.
* Do you have access to such an engine?
* Is it possible for you to **_pre-process_** your text with it and then output it using PyMuPDF?

**Comment by JorjMcKie** [comment] 2020-07-22 13:46
I am experimenting with the following:
Try to develop an algorithm that re-orders the characters in an Devanagari string before putting it on a PDF page. I took your string and looked at its unicode by character:
```python
>>> text = "नि:शुल्क ज्ञानको लागी लाई धन्यबाद"
>>> for c in text:
	print(c, "=", ord(c))

	
न = 2344
ि = 2367
: = 58
श = 2358
ु = 2369
ल = 2354
् = 2381
क = 2325
  = 32
ज = 2332
् = 2381
ञ = 2334
ा = 2366
न = 2344
क = 2325
ो = 2379
  = 32
ल = 2354
ा = 2366
ग = 2327
ी = 2368
  = 32
ल = 2354
ा = 2366
ई = 2312
  = 32
ध = 2343
न = 2344
् = 2381
य = 2351
ब = 2348
ा = 2366
द = 2342
>>> 
```
Then I tried this:
```python
def switch_chars(text):
    halves = (2367, 2366, 2379, 2368)  # unicodes that seem to modfy the preceeding char
    newtext = [c for c in text]

    for i in range(1, len(text)):
        ordi = ord(newtext[i])
        if ordi in halves:  # revert the sequ with previous char
            newtext[i - 1], newtext[i] = newtext[i], newtext[i - 1]
    return "".join(newtext)
```
When I then write the string ``switch_chars(text)`` instead of `text`, the output starts look better, although it is still far from the final goal:
very wrong: 
![grafik](https://user-images.githubusercontent.com/8290722/88183353-5a482d00-cbff-11ea-80b4-bed2f9750010.png)
somewhat better:
![grafik](https://user-images.githubusercontent.com/8290722/88183461-7d72dc80-cbff-11ea-9146-69816a6c2807.png)
final goal:
![grafik](https://user-images.githubusercontent.com/8290722/88183693-c6c32c00-cbff-11ea-9a57-79b05eda28c5.png)

For me this looks like a promising path to go. I think you are in a better position to help complete the rules that must be implemented in some function like `switch_chars` above ...!

**Comment by arjunpaudyal** [comment] 2020-08-07 21:41
I have not tried, but i think it will be a challenging idea, though not impossible.

some issues are font level.

Take an example : ज्ञ seems to be single character (and is in language). (taken from : ज्ञानको)
(1 byte in language, but 3 bytes in unicode)

from Unicode Table, it is formed with combination of 3 characters : ज = 2332 + ् = 2381 + ञ = 2334
again, same complex character is furthur modified to make it : ज्ञा, which is combination of  ज = 2332 + ् = 2381 + ञ = 2334 + ा = 2366

Each font is free to define its ligature in its codepage. I think this is font level, meaning it may NOT have a global integer value. 

You are already one step ahead than i thin i could help you.

**Comment by JorjMcKie** [comment] 2020-08-08 10:32
>  i think it will be a challenging idea, though not impossible.

I agree. The Microsoft website you pointed me to explains exactly such an algorithm (on an abstreact level unfortunately). Obviously a complex algorithm, and your recent post confirms this.
However, such an algorithm **_is doable_**, that's for sure - it is implemented in LibreOffice and all the other examples.
The problem is, finding the source code of such an algorithm. The rest would be more or less straightforward.
Maybe I can take allok at LibreOffice source. Should be possible, because it is open source free software.

**Closed** 2020-12-10 15:07 UTC
Labels: enhancement, question
