### ISSUE TITLE
When uwsgi recycled the process, pymupdf caused the process to crash.

### ISSUE THREAD

**Issue by b-ing** [pymupdf/PyMuPDF#3749] opened 2024-08-03 01:19 UTC
### Description of the bug

When uwsgi recycled the process, pymupdf caused the process to crash.
Environment:
python 3.8.17
PyMuPDF 1.24.9
PyMuPDFb 1.24.9

### How to reproduce the bug

!!! uWSGI process 10107 got Segmentation Fault !!!
*** backtrace of 10107 ***
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_backtrace+0x2f) [0x55e7a70d1baf]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_segfault+0x23) [0x55e7a70d1f83]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bf90) [0x7fd349a0bf90]
/usr/local/lib/python3.8/site-packages/pymupdf/libmupdf.so.24.8(fz_drop_icc_profile+0xc) [0x7fd3267787ac]
/usr/local/lib/python3.8/site-packages/pymupdf/libmupdf.so.24.8(fz_drop_colorspace_imp+0x5d) [0x7fd32677a30d]
/usr/local/lib/python3.8/site-packages/pymupdf/libmupdfcpp.so.24.8(_ZN5mupdf21ll_fz_drop_colorspaceEP13fz_colorspace+0x5b) [0x7fd32cd60b3b]
/usr/local/lib/python3.8/site-packages/pymupdf/libmupdfcpp.so.24.8(_ZN5mupdf12FzColorspaceD2Ev+0xc) [0x7fd32cd2f71c]
/usr/local/lib/python3.8/site-packages/pymupdf/_mupdf.so(+0x26fe57) [0x7fd325900e57]
/usr/local/lib/python3.8/site-packages/pymupdf/_mupdf.so(+0x2d4f83) [0x7fd325965f83]
/usr/local/lib/libpython3.8.so.1.0(+0x15874c) [0x7fd349d0b74c]
/usr/local/lib/libpython3.8.so.1.0(+0x164961) [0x7fd349d17961]
/usr/local/lib/libpython3.8.so.1.0(+0x15874c) [0x7fd349d0b74c]
/usr/local/lib/libpython3.8.so.1.0(+0x1a45ff) [0x7fd349d575ff]
/usr/local/lib/libpython3.8.so.1.0(+0x1c1d61) [0x7fd349d74d61]
/usr/local/lib/libpython3.8.so.1.0(_PyGC_CollectNoFail+0x32) [0x7fd349d752d2]
/usr/local/lib/libpython3.8.so.1.0(PyImport_Cleanup+0x15b) [0x7fd349d68eeb]
/usr/local/lib/libpython3.8.so.1.0(Py_FinalizeEx+0x7a) [0x7fd349d6e84a]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_plugins_atexit+0x71) [0x55e7a70d0101]
/lib/x86_64-linux-gnu/libc.so.6(+0x3e435) [0x7fd349a0e435]
/lib/x86_64-linux-gnu/libc.so.6(+0x3e5aa) [0x7fd349a0e5aa]
xxx_xxx_prod_uwsgi uWSGI worker 2(+0x3df4f) [0x55e7a7087f4f]
xxx_xxx_prod_uwsgi uWSGI worker 2(simple_goodbye_cruel_world+0x59) [0x55e7a70d1519]
xxx_xxx_prod_uwsgi uWSGI worker 2(+0x87558) [0x55e7a70d1558]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_close_request+0x54f) [0x55e7a7088c4f]
xxx_xxx_prod_uwsgi uWSGI worker 2(simple_loop_run+0xc0) [0x55e7a70cdba0]
xxx_xxx_prod_uwsgi uWSGI worker 2(simple_loop+0x7b) [0x55e7a70cdc6b]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_ignition+0x279) [0x55e7a70d22b9]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_worker_run+0x25b) [0x55e7a70d68db]
xxx_xxx_prod_uwsgi uWSGI worker 2(uwsgi_run+0x43a) [0x55e7a70d6e2a]
xxx_xxx_prod_uwsgi uWSGI worker 2(+0x3adde) [0x55e7a7084dde]
/lib/x86_64-linux-gnu/libc.so.6(+0x2718a) [0x7fd3499f718a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7fd3499f7245]
xxx_xxx_prod_uwsgi uWSGI worker 2(_start+0x21) [0x55e7a7084e01]
*** end of backtrace ***
worker 2 killed successfully (pid: 10107)

### PyMuPDF version

1.24.9

### Operating system

Linux

### Python version

3.8

**Comment by JorjMcKie** [comment] 2024-08-03 06:06
This post cannot be handled because of insufficient information: no reproducing file, no reproducing code.

**Comment by b-ing** [comment] 2024-08-03 09:11
Thank you for replying to me.
I am using this code, but the route does not point to the code, and only uses files containing the Fitz module
code:

`
    def sign_lease_info_back_sec(self, request: Request, *args, **kwargs):
    
        dpi = request.data.get("dpi")
        pdf_path = request.data.get("pdfurl")
        config_list = request.data.get("config")
        pdf_file = pdf_path.split('media/')[-1]
        file_path = os.path.join(settings.BASE_DIR, "media", pdf_file)
        doc = fitz.open(file_path)
        plat_form = platform.system()
        if plat_form == "Windows":
            pme_file = BASE_DIR + "\\static\\rest_framework\\fonts\\AlibabaPuHuiTi-3-45-Light.ttf"
        elif plat_form == "Linux":
            pme_file = BASE_DIR + "/static/rest_framework/fonts/AlibabaPuHuiTi-3-45-Light.ttf"
        else:
            pme_file = BASE_DIR + "/static/rest_framework/fonts/AlibabaPuHuiTi-3-45-Light.ttf"
        for i in config_list:
            if i.get("type") == "text":
                page_num = int(i.get("pageNum")) - 1
                page = doc[page_num]
                text_pos = (i.get("x"), i.get("y"))  
                page.insert_font(fontname='AlibabaPuHuiTi', fontfile=pme_file, set_simple=False,
                                 encoding=0)
                page.insert_text(text_pos, text=i.get("content"), fontsize=12, rotate=0,
                                 fontname="AlibabaPuHuiTi") 
            if i.get("type") == "image":
                rect = fitz.Rect(i.get("x"), i.get("y"), i.get("x") + i.get("width"), i.get("y") + i.get("height"))
                page_num = int(i.get("pageNum")) - 1
                page = doc[page_num]
                image_path = i.get("content")
                image_path = image_path.split('media/')[-1]
                image_path = os.path.join(settings.BASE_DIR, "media", image_path)
                page.insert_image(rect, filename=image_path)
        url = pdf_save_file(doc, dpi=dpi if dpi else None)
        file_url = API_ADDRESS + "/media/" + url
        return SuccessResponse(data={"url": url, "file_url": file_url})
`

**Comment by JorjMcKie** [comment] 2024-08-03 15:59
This is still not enough information. An example file showing the problem is also needed.
When submitting a bug report, please make sure to always supply all information needed to reproduce the error.

**Comment by b-ing** [comment] 2024-08-05 02:00
> This is still not enough information. An example file showing the problem is also needed. When submitting a bug report, please make sure to always supply all information needed to reproduce the error.

Is the error message refer to the stack error?

```shell
Thread 1 (LWP 4752):
#0  0x00007fd3267787ac in fz_drop_icc_profile () from /usr/local/lib/python3.8/site-packages/pymupdf/libmupdf.so.24.8
#1  0x00007fd32677a30d in fz_drop_colorspace_imp () from /usr/local/lib/python3.8/site-packages/pymupdf/libmupdf.so.24.8
#2  0x00007fd32cd60b3b in mupdf::ll_fz_drop_colorspace(fz_colorspace*) () from /usr/local/lib/python3.8/site-packages/pymupdf/libmupdfcpp.so.24.8
#3  0x00007fd32cd2f71c in mupdf::FzColorspace::~FzColorspace() () from /usr/local/lib/python3.8/site-packages/pymupdf/libmupdfcpp.so.24.8
#4  0x00007fd325900e57 in _wrap_delete_FzColorspace () from /usr/local/lib/python3.8/site-packages/pymupdf/_mupdf.so
#5  0x00007fd325965f83 in SwigPyObject_dealloc () from /usr/local/lib/python3.8/site-packages/pymupdf/_mupdf.so
#6  0x00007fd349d0b74c in ?? () from /usr/local/lib/libpython3.8.so.1.0
#7  0x00007fd349d17961 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#8  0x00007fd349d0b74c in ?? () from /usr/local/lib/libpython3.8.so.1.0
#9  0x00007fd349d575ff in ?? () from /usr/local/lib/libpython3.8.so.1.0
#10 0x00007fd349d74d61 in ?? () from /usr/local/lib/libpython3.8.so.1.0
#11 0x00007fd349d752d2 in _PyGC_CollectNoFail () from /usr/local/lib/libpython3.8.so.1.0
#12 0x00007fd349d68eeb in PyImport_Cleanup () from /usr/local/lib/libpython3.8.so.1.0
#13 0x00007fd349d6e84a in Py_FinalizeEx () from /usr/local/lib/libpython3.8.so.1.0
#14 0x000055e7a70d0101 in uwsgi_plugins_atexit ()
#15 0x00007fd349a0e435 in __run_exit_handlers (status=0, listp=0x7fd349ba2820 <__exit_funcs>, run_list_atexit=<optimized out>, run_dtors=<optimized out>) at ./stdlib/exit.c:61
#16 0x00007fd349a0e5aa in __run_exit_handlers (status=0, listp=0x61ea8675d7026, run_list_atexit=<optimized out>, run_dtors=<optimized out>) at ./stdlib/exit.c:103
#17 0x0000000000000000 in ?? ()
```

**Comment by JorjMcKie** [comment] 2024-08-05 07:35
It is a segfault for sure. But without the PDF page causing the error it all remains guesswork.
If you cannot provide an example page, I am afraid we must close this bug report.

**Comment by JorjMcKie** [comment] 2024-08-13 10:00
Closed because of an extended time period without response.

**Closed by JorjMcKie** 2024-08-13 10:00 UTC
Labels: Waiting for information
