### ISSUE TITLE
Replace image in PDF (Question)

### ISSUE THREAD

**Issue by DenisSouth** [pymupdf/PyMuPDF#1017] opened 2021-04-19 12:25 UTC
I try to replace top image (xref 24) with middle one (xref 25)  on page 2 

but instead of replacing - I got smaller and vertical flipped  version of image (xref 25) on the bottom of page 2

What is wrong with my rectangle definition?

I already read https://github.com/pymupdf/PyMuPDF/discussions/936 but I think it is about some text replacement
```

import fitz
from PIL import Image
import io

doc = fitz.Document("0.pdf")
page = doc.loadPage(2)

def pic_getinfo(doc,page, item):
  xref, _, width, height, _, _, _, name , _ = item

  rect = page.get_image_bbox(name)
  img = Image.open(io.BytesIO(doc.extractImage(xref)['image']))
  return {"height":height,"width":width,"xref":xref, "name":name, "rect":rect,"img":img }
  

ImageList = page.getImageList()
ImageList

>> [(24, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image1', 'DCTDecode'),
>>  (25, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image2', 'DCTDecode'),
>>  (26, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image3', 'DCTDecode'),
>>  (27, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image4', 'DCTDecode'),
>>  (28, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image5', 'DCTDecode'),
>>  (29, 0, 1275, 273, 8, 'DeviceRGB', '', 'Image6', 'DCTDecode'),
>>  (30, 0, 1275, 122, 8, 'DeviceRGB', '', 'Image7', 'DCTDecode')]

pic0 = pic_getinfo(doc,page, ImageList[0])
pic0
>>  {'height': 273,
>>   'xref': 24,
>>   'img': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1275x273 at 0x7F45D000>,
>>   'name': 'Image1',
>>   'rect': Rect(0.0, 11.64, 595.32, 139.20),
>>   'width': 1275}
 
pic1 = pic_getinfo(doc,page, ImageList[1])
pic1
>>   {'height': 273,
>>    'xref': 25,
>>    'img': <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1275x273 at 0x7F45D001>,
>>    'name': 'Image2',
>>    'rect': Rect(0.0, 138.72, 595.32, 266.16),
>>    'width': 1275}

pic1['img'].save("i1.jpg")
page.insert_image(pic0['rect'], filename="i1.jpg")
doc.save("1.pdf")

```

**Comment by JorjMcKie** [comment] 2021-04-19 12:35
Since you did not provide the PDF, I am forced to guess:
Probably your page has an uncontained "geometry change", which causes subsequent insertions (of anything - not only images), to land at unexpected places.
To be sure, use `page.clean_contents()` before you insert anything.

Presumably, you also want to get rid of the image xref 24 altogether, so you want to consider using a redaction to remove it.

**Comment by DenisSouth** [comment] 2021-04-19 12:48
thanks. how can I set "geometry change" and remove  old xref 24 pic ? 

I think it will not help me with this task 

```
page.addRedactAnnot(rect, text=" ")
page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_REMOVE)
```

**Comment by JorjMcKie** [comment] 2021-04-19 13:40
1. geometry change: `page.clean_contents()` should do it
2. get rectangle of image at xref 24: ``bbox = page.get_image_bbox("Image1")``
3. `page.addRedactAnnot(bbox)`, then `page.apply_redactions(images=fitz.PDF_IMAGE_REMOVE)` - will remove that image
4. then extract image at xref 25 like you did, then insert that image in former bbox of xref 24

**Comment by DenisSouth** [comment] 2021-04-19 17:19
> 1. geometry change: `page.clean_contents()` should do it
> 2. get rectangle of image at xref 24: `bbox = page.get_image_bbox("Image1")`
> 3. `page.addRedactAnnot(bbox)`, then `page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_REMOVE)` - will remove that image
> 4. then extract image at xref 25 like you did, then insert that image in former bbox of xref 24

Thanks a lot, it is working )

**Comment by JorjMcKie** [comment] 2021-04-19 18:00
Great. Impressive - because I haven't been overly verbose I must confess.

**Comment by DenisSouth** [comment] 2021-04-20 05:45
> Great. Impressive - because I haven't been overly verbose I must confess.

May I ask you other piece of advice here?)
This code works fine, but it removes all text boxes (original document is scanned book after OCR, it was searchable)
how can I prevent text and other things from being deleted along with old images? 

I want just to edit pictures and leave other elements intact.
```
import fitz
from PIL import Image
import io
import numpy as np
import os
import cv2

def pic_getinfo(doc_, page_, item_):
    xref, _, width, height, _, _, _, name, _ = item_
    rect = page_.get_image_bbox(name)
    img = Image.open(io.BytesIO(doc_.extractImage(xref)['image']))
    return {"height": height, "width": width, "xref": xref, "name": name, "rect": rect, "img": img}

def equalizeHist_rgb(rgb_img):
    ycrcb_img = cv2.cvtColor(rgb_img, cv2.COLOR_RGB2YCrCb)
    ycrcb_img[:, :, 0] = cv2.equalizeHist(ycrcb_img[:, :, 0])
    return cv2.cvtColor(ycrcb_img, cv2.COLOR_YCrCb2RGB)

def im_proc(bitmap):
    return equalizeHist_rgb(bitmap)

doc = fitz.Document("1.pdf")

for ind in range(0, 10): #doc.page_count
    page = doc.loadPage(ind)
    print( doc.page_count - ind)

    temp_insert = []
    for ind_l, ImageList_part in enumerate(page.getImageList()):

        try:
            img_data = pic_getinfo(doc, page, ImageList_part)
            img_name = f"temp/{ind}_{ind_l}.png"

            image_mod = im_proc(bitmap=np.array(img_data['img']))
            Image.fromarray(image_mod).save(img_name)
            temp_insert.append([img_data["rect"], img_name])

            page.addRedactAnnot(img_data["rect"])
        except Exception as E:
            print(E, ind_l, ImageList_part)

    page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_REMOVE)

    for temp in temp_insert:
        page.clean_contents()
        page.insert_image(temp[0], filename=temp[1])
        os.remove(temp[1])

doc.save("1v1.pdf")
```

**Comment by JorjMcKie** [comment] 2021-04-20 08:50
I think this is a duplicate of this one #952

**Comment by DenisSouth** [comment] 2021-04-21 07:02
> I think this is a duplicate of this one #952

how can I insert page.get_text("dict", flags=0) back to the page?

with "blocks" I can do that:

```
temp_insert.append(page.get_text("blocks", flags=0))
........

for temp in temp_insert:
        page.clean_contents()

        for i in temp:
           rect = i[:4]
           text = i[4]
           page.insert_textbox(rect, text, fontsize =i[5], color =i[6])
```

but sometimes it looses some text, sometimes its font or size

**Comment by JorjMcKie** [comment] 2021-04-22 08:04
To "replace" an image shown in a rectangle by another one is also achievable by a more "hacky" approach, involving PyMuPDF's low-level capabilities. The basic steps are:

1. Clean the page's `/Contents` objects. This will unify possible multiple contents into one and standardize the command syntax.
2. Check the reference name of the to-be-replaced image again in list `page.get_images()`, because it will have changd due to the cleaning.
3. "Hunt-and-destroy" the display command of that image in the resulting `/Contents` source.
4. Insert the new image in the old image's rectangle.

The "hunt-and-destroy" step works like this:
Assuming that the reference name to the image is "Im1", then you will find a line `b"/Im1 Do"` in the `/Contents` source (which is a `bytes` object). Replace that line by `b""`.

```python
page.clean_contents()
# determine the (changed) image ref name - say it now is "Im1"
xref = page.get_contents()[0]  # xref of contetns source
cont = bytearray(doc.xref_stream(xref))  # read and make modifyable
cont = cont.replace(b"/Im1 Do", b"")  # remove image invocation
doc.update_stream(xref, cont)  # write back contents object
# now insert new image
```

**Comment by DenisSouth** [comment] 2021-04-22 11:46
Thanks a lot. I nearly finish my [project](https://github.com/DenisSouth/pdf_image_processing), but I found few strange bugs.


(b"/Im1 Do", b"")  That string isn't able to find any image in few cases, but I solved it

Images may have names  "Bg", "Bg, CL" and "Im1" and maybe some else, but I haven't found them yet.

Example with  "Bg" (PDF-A saved by old FineReader)  text were random generated, printed, then scanned.
 [fr_A.pdf](https://github.com/DenisSouth/pdf_image_processing/blob/main/fr_A.pdf)

Example with  "Bg, CL" (PDF saved by old FineReader) text were random generated, printed, then scanned.
[fr_std.pdf](https://github.com/DenisSouth/pdf_image_processing/blob/main/fr_std.pdf)


Example with  "Im1" 
file from issue https://github.com/pymupdf/PyMuPDF/discussions/952
[example.pdf](https://github.com/pymupdf/PyMuPDF/files/6203567/in.pdf)

My code works fine "with fr_A.pdf" and "example.pdf"

but with "Bg, CL" (images fr_std.pdf)  some really strange things happen.

Instead of one picture per page. It founds two pictures, one of them are blurred background, and other - some grayscale multigradient surface. [bug fr_std_bug.jpg ](https://github.com/DenisSouth/pdf_image_processing/blob/main/fr_std.jpg)

Here is my code [main.py](https://github.com/DenisSouth/pdf_image_processing/blob/main/main.py)

**Comment by JorjMcKie** [comment] 2021-04-22 12:45
You misunderstood:
In order to have a clean syntax, I suggested to first clean the page.
**_Then_** look again for the image names, because they change b/o cleaning:

```python
>>> pprint(doc.get_page_images(0))
[(8, 0, 773, 1125, 8, 'DeviceRGB', '', 'Bg', 'JPXDecode'),
 (9, 10, 387, 563, 8, 'DeviceRGB', '', 'CL', 'JPXDecode')]
>>> page=doc[0]
>>> page.clean_contents()
>>> pprint(doc.get_page_images(0))
[(8, 0, 773, 1125, 8, 'DeviceRGB', '', 'Im1', 'JPXDecode'),
 (9, 10, 387, 563, 8, 'DeviceRGB', '', 'Im2', 'JPXDecode')]
>>>
```
So after clean you no longer have "Bg", etc.

**Comment by DenisSouth** [comment] 2021-04-22 13:05
I edited the code as you said and names become normal, thanks)  

But issue with this document still exist

[fr_std.pdf](https://github.com/DenisSouth/pdf_image_beautifier/blob/main/fr_std.pdf)

[bug.jpg](https://github.com/DenisSouth/pdf_image_beautifier/blob/main/bug.jpg)

my code [main.py](https://github.com/DenisSouth/pdf_image_beautifier/blob/main/main.py)

**Comment by DenisSouth** [comment] 2021-04-22 14:57
I think that I find some kind of solution 
```
mat = fitz.Matrix(7, 7)
pix = page.getPixmap(matrix=mat,alpha = False)
pix.writePNG("page.png" % page.number)
```
and after that I can resize or crop it, this works fine

**Closed** 2021-04-22 16:47 UTC
Labels: question

**Comment by PasaOpasen** [comment] 2022-08-16 12:36
@JorjMcKie  Hello!

Thanks for this discussion, it helped me to solve a big part of my problems recently! And I wanna to say that this library is really monster powerful tool!

My task is the replacing pdf images with theirs compressed forms (keeping text layer and so on) to downsize pdf about 5-10 times. I'm using the code from upper and it works well on a big part of documents. Unfortunately, sometimes the code

```python
xref = page.get_contents()[0] 
cont = bytearray(doc.xref_stream(xref))
cont = cont.replace(f"/{name} Do".encode(), b"")  
```

actually does nothing because there is no Name sequence in `cont` bytes (it's true without `page.clean_contents()` too). Next block shows that there is a one image on page, but I cannot find it in main stream (and cannot remove):

```python
page.get_images()
Out[4]: [(16, 0, 2302, 3080, 8, 'DeviceRGB', '', 'Img3', 'FlateDecode')]
page.get_contents()
Out[5]: [17]
xref = 17
cont = bytearray(doc.xref_stream(xref)); len(cont)
Out[7]: 64391
cont.find(b'Img3')
Out[8]: -1
```

Also applying `doc.save(path, deflate=True, garbage=4, clean=True)` (trying to clean) before running that code -- has no effect.

My question is how to clean/rebuild this doc by fitz to solve that problem with undeletable image (fix xrefs, meta)? I can do this by `ghostscript` but this way has other kind of problems...

My fitz version is `('1.19.5', '1.19.0', '20220201000001')`. Here is the document example (page 0):  https://github.com/PasaOpasen/report_docs_collection/blob/main/fitz_cannot_rm_image.pdf

**Comment by JorjMcKie** [comment] 2022-08-16 13:17
The problem probably is that the image is inside some Form XObject and the page only displays it indirectly. If you do `page.get_images(True)` you will see an extended list with an integer xref of that xobject as lest item.
But what counts is that you already have the image xref.
I have developed a solution for replacing (and pseudo-deleting) images for such a case [here](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/image-replacement/replacer.py).
Hope you can use it.

**Comment by PasaOpasen** [comment] 2022-08-16 13:42
Thank u!! That works amazing!!!
