### ISSUE TITLE
Destination point not set for named links in toc

### ISSUE THREAD

**Issue by blenzi** [pymupdf/PyMuPDF#2088] opened 2022-11-28 10:00 UTC
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
If a pdf outline / toc contains named links, the destination point ("to") is not set

## To Reproduce (mandatory)

Compile with pdflatex or paste in your browser the command below to get the pdf (rename it to `named_outline.pdf` for the following):

```
latexonline.cc/compile?url=https://gist.githubusercontent.com/blenzi/5d4338d4b384fd0d1495a6341b534eb5/raw/0bb0da6deb3d74a1e67aabf8f7a61d5ab8e5b438/named_outline.tex
```

Open the pdf and get the toc:

```python
>>> import fitz
>>> doc = fitz.open("named_outline.pdf")
>>> doc.get_toc(simple=False)[0][3]
{'kind': 4, 'xref': 4, 'name': 'page=1&zoom=nan,133.768,229.479', 'collapse': True, 'zoom': 0.0}
```

To fix it, it is probably enough (although I am not sure how safe it is) to get the last two items of `"name"` [here](https://github.com/pymupdf/PyMuPDF/blob/9d2af43230f6d9944734320813acc79abe95d514/fitz/utils.py#L919):

```python
pnt.x, pnt.y = map(float, ln.dest.named.split(",")[-2:])
nl["to"] = pnt
```

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: MacOsX 
 - Python version, bitness: 3.11.0
 - PyMuPDF version, installation method (**wheel** or **generated** from source): 1.21.0

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

**Comment by JorjMcKie** [comment] 2022-11-28 11:01
Thanks for report this.

The problem is an error parsing the `uri` field in class `linkDest`. This class is responsible for providing **_all_** link properties - including link kind.
The correct result would be `LINK_GOTO` in the end, because internal symbolic names are always resolved to page number / point destinations.

**Comment by JorjMcKie** [comment] 2022-11-28 11:14
Have a fix. Problem will be corrected in next version.
Drop me a note if you would like to make a local patch.

**Comment by julian-smith-artifex-com** [comment] 2022-12-13 14:30
Fixed in PyMuPDF-1.21.1.

**Closed by julian-smith-artifex-com** 2022-12-13 14:30 UTC
Labels: bug

**Comment by JorjMcKie** [comment] 2023-12-08 10:04
@thomascerbelaud - you should find this issue resolved if you use the import statement `import fitz_new as fitz`.
This will invoke the new PyMuPDF implementation which contains a full PDF name resolution. This is also used in TOC extraction.

**Comment by thomascerbelaud** [comment] 2023-12-08 11:31
It's working indeed, great thanks! A last question though: is it planned to release a version of `fitz` that does not include `fitz_new`? Should we always import `fitz_new` instead of `fitz` from now on?

**Comment by JorjMcKie** [comment] 2023-12-08 11:38
> It's working indeed, great thanks! A last question though: is it planned to release a version of `fitz` that does not include `fitz_new`? Should we always import `fitz_new` instead of `fitz` from now on?

No, this is a temporary situation. We are planning to swap versions classic <> rebased ("fitz_new") very soon. In that next phase, the current/classic version will still be available as `import fitz_old as fitz`.
In the final phase (several weeks out), the classic version will then be dropped.

**Comment by julian-smith-artifex-com** [comment] 2023-12-08 11:56
Also see: #2680
